### ISSUE TITLE
Unique constraint failed on the fields: (`view_id`)

### ISSUE THREAD

**Issue by jakobbouchard** [umami-software/umami#1295]
I just moved my Umami install from Vercel, and my database from Supabase to Fly.io and I started getting these errors any time a view tries to get recorded.

Here is the command I used to migrate the DB:

```shell
pg_dump postgresql://postgres:PASSWORD@db.XXX.supabase.co:5432/postgres | psql postgres://user:password@xxx.fly.dev:5432/database
```
I assumed it migrated correctly since all my users, websites, historical data have been showing up correctly. The Prisma migration also ran without a problem when it first launched.

**Comment by jakobbouchard** [comment]
Also, pretty sure it's unrelated, but Firefox doesn't seem to call the collect endpoint at all. Safari does too, and gets the same 500 error.

**Comment by mikecao** [comment]
Can you post the entire error message?

**Comment by jakobbouchard** [comment]
```log
2022-07-13T19:23:42.759 app[13fb951f] yul [info] PrismaClientKnownRequestError: Unique constraint failed on the fields: (`view_id`)
2022-07-13T19:23:42.759 app[13fb951f] yul [info] at RequestHandler.request (/app/node_modules/@prisma/client/runtime/index.js:49022:15)
2022-07-13T19:23:42.759 app[13fb951f] yul [info] at async PrismaClient._request (/app/node_modules/@prisma/client/runtime/index.js:49919:18)
2022-07-13T19:23:42.759 app[13fb951f] yul [info] at async __WEBPACK_DEFAULT_EXPORT__ (/app/.next/server/pages/api/collect.js:248:9)
2022-07-13T19:23:42.759 app[13fb951f] yul [info] at async Object.apiResolver (/app/node_modules/next/dist/server/api-utils/node.js:182:9)
2022-07-13T19:23:42.759 app[13fb951f] yul [info] at async NextNodeServer.runApi (/app/node_modules/next/dist/server/next-server.js:386:9)
2022-07-13T19:23:42.759 app[13fb951f] yul [info] at async Object.fn (/app/node_modules/next/dist/server/base-server.js:488:37)
2022-07-13T19:23:42.759 app[13fb951f] yul [info] at async Router.execute (/app/node_modules/next/dist/server/router.js:228:32)
2022-07-13T19:23:42.759 app[13fb951f] yul [info] at async NextNodeServer.run (/app/node_modules/next/dist/server/base-server.js:600:29)
2022-07-13T19:23:42.759 app[13fb951f] yul [info] at async NextNodeServer.handleRequest (/app/node_modules/next/dist/server/base-server.js:307:20)
2022-07-13T19:23:42.759 app[13fb951f] yul [info] at async Server.<anonymous> (/app/server.js:16:5) {
2022-07-13T19:23:42.759 app[13fb951f] yul [info] code: 'P2002',
2022-07-13T19:23:42.759 app[13fb951f] yul [info] clientVersion: '3.15.2',
2022-07-13T19:23:42.759 app[13fb951f] yul [info] meta: { target: [ 'view_id' ] }
2022-07-13T19:23:42.759 app[13fb951f] yul [info] }
```

Here it is! Sorry if the formatting is odd, I'm on mobile.

**Comment by mikecao** [comment]
I might be due to the autogeneration of the view id field. If the count starts at 1 and view id 1 already exists it will complain. I think you'll have to reset it, see https://www.postgresql.org/docs/current/sql-altersequence.html

**Comment by jakobbouchard** [comment]
That did fix it thanks! Weird that the sequence broke when migrating though. As for the Firefox issue, that's on me. I don't know why, but I had do-not-track to true and had it enabled in my browser settings. I usually never do that.
