### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by rohandebsarkar** [umami-software/umami#1411]
I have created a click event for an external link on my website and wanted to monitor it.

The post methods to the umami instance are failing with the following error message:
```
Access to fetch at 'https://***.vercel.app/collect' from origin 'https://rohandebsarkar.github.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

**Comment by mikecao** [comment]
Can you post the request headers?

**Comment by rohandebsarkar** [comment]
Request Headers:
```
:authority: ***.vercel.app
:method: POST
:path: /mitto
:scheme: https
accept: */*
accept-encoding: gzip, deflate, br
accept-language: en-GB,en-US;q=0.9,en;q=0.8
content-length: 200
content-type: application/json
origin: https://rohandebsarkar.github.io
referer: https://rohandebsarkar.github.io/
sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="104"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Linux"
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: cross-site
user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.79 Safari/537.36
```

**Comment by mikecao** [comment]
When I send a request through Insomnia it runs fine. But from your website, the email button, I get a 500 errors. Can you check your vercel logs to see what it says?

**Comment by rohandebsarkar** [comment]
### Vercel logs:
```
ERROR	PrismaClientKnownRequestError: The column `event_name` does not exist in the current database.    
at RequestHandler.handleRequestError (/var/task/node_modules/@prisma/client/runtime/index.js:28658:13)    
at RequestHandler.request (/var/task/node_modules/@prisma/client/runtime/index.js:28640:12)    
at async consumer (/var/task/node_modules/@prisma/client/runtime/index.js:29618:18)    
at async PrismaClient._request (/var/task/node_modules/@prisma/client/runtime/index.js:29639:16)    
at async __WEBPACK_DEFAULT_EXPORT__ (/var/task/.next/server/pages/api/collect.js:251:9)    
at async Object.apiResolver (/var/task/node_modules/next/dist/server/api-utils/node.js:184:9)    
at async NextNodeServer.runApi (/var/task/node_modules/next/dist/server/next-server.js:381:9)    
at async Object.fn (/var/task/node_modules/next/dist/server/base-server.js:491:37)    
at async Router.execute (/var/task/node_modules/next/dist/server/router.js:213:36)    
at async NextNodeServer.run (/var/task/node_modules/next/dist/server/base-server.js:610:29) {  code: 'P2022',  clientVersion: '4.1.1',  meta: { column: 'event_name' }}

ERROR	PrismaClientKnownRequestError: The column `event_name` does not exist in the current database.    
at RequestHandler.handleRequestError (/var/task/node_modules/@prisma/client/runtime/index.js:28658:13)    
at RequestHandler.request (/var/task/node_modules/@prisma/client/runtime/index.js:28640:12)    
at async consumer (/var/task/node_modules/@prisma/client/runtime/index.js:29618:18)    
at async PrismaClient._request (/var/task/node_modules/@prisma/client/runtime/index.js:29639:16)    
at async __WEBPACK_DEFAULT_EXPORT__ (/var/task/.next/server/pages/api/collect.js:251:9)    
at async Object.apiResolver (/var/task/node_modules/next/dist/server/api-utils/node.js:184:9)    
at async NextNodeServer.runApi (/var/task/node_modules/next/dist/server/next-server.js:381:9)    
at async Object.fn (/var/task/node_modules/next/dist/server/base-server.js:491:37)    
at async Router.execute (/var/task/node_modules/next/dist/server/router.js:213:36)    
at async NextNodeServer.run (/var/task/node_modules/next/dist/server/base-server.js:610:29) {  code: 'P2022',  clientVersion: '4.1.1',  meta: { column: 'event_name' }}
```

**Comment by rohandebsarkar** [comment]
I think this related to my previous issue #1389.

**Comment by rohandebsarkar** [comment]
Manually solved as described in the comment https://github.com/umami-software/umami/issues/1389#issuecomment-1214859357.
