### ISSUE TITLE
Error occurred prerendering page

### ISSUE THREAD

**Issue by robertrud** [umami-software/umami#1420]
Hi, I've tried to upgrade to 1.37.0 but `npm run build` failed with a bunch of errors while generating static pages. I don't know what to do:
......
`> umami@1.37.0 build-app
> next build

info  - Loaded env from /home/robert/umami/.env
info  - Skipping linting
info  - Checking validity of types  
info  - Creating an optimized production build  
info  - Compiled successfully
info  - Collecting page data  
[    ] info  - Generating static pages (0/11)
Error occurred prerendering page "/404". Read more: https://nextjs.org/docs/messages/prerender-error
Invariant Violation: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at ca (/home/robert/umami/node_modules/react-spring/node_modules/react/cjs/react.production.min.js:11:316)
    at B (/home/robert/umami/node_modules/react-spring/node_modules/react/cjs/react.production.min.js:12:166)
    at W (/home/robert/umami/node_modules/react-spring/node_modules/react/cjs/react.production.min.js:20:375)
    at Object.useMemo (/home/robert/umami/node_modules/react-spring/node_modules/react/cjs/react.production.min.js:23:164)
    at useTransition (/home/robert/umami/node_modules/react-spring/node_modules/@react-spring/core/dist/react-spring-core.cjs.prod.js:2156:21)
    at ThemeButton (/home/robert/umami/.next/server/chunks/838.js:1378:84)
    at d (/home/robert/umami/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:498)
    at bb (/home/robert/umami/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
    at a.b.render (/home/robert/umami/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
    at a.b.read (/home/robert/umami/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)

Error occurred prerendering page "/dashboard/[[...id]]". Read more: https://nextjs.org/docs/messages/prerender-error
Invariant Violation: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at ca (/home/robert/umami/node_modules/react-spring/node_modules/react/cjs/react.production.min.js:11:316)
    at B (/home/robert/umami/node_modules/react-spring/node_modules/react/cjs/react.production.min.js:12:166)
    at W (/home/robert/umami/node_modules/react-spring/node_modules/react/cjs/react.production.min.js:20:375)
    at Object.useMemo (/home/robert/umami/node_modules/react-spring/node_modules/react/cjs/react.production.min.js:23:164)
    at useTransition (/home/robert/umami/node_modules/react-spring/node_modules/@react-spring/core/dist/react-spring-core.cjs.prod.js:2156:21)
    at ThemeButton (/home/robert/umami/.next/server/chunks/838.js:1378:84)
    at d (/home/robert/umami/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:498)
    at bb (/home/robert/umami/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
    at a.b.render (/home/robert/umami/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
    at a.b.read (/home/robert/umami/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)

Error occurred prerendering page "/realtime". Read more: https://nextjs.org/docs/messages/prerender-error
Invariant Violation: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at ca (/home/robert/umami/node_modules/react-spring/node_modules/react/cjs/react.production.min.js:11:316)
    at B (/home/robert/umami/node_modules/react-spring/node_modules/react/cjs/react.production.min.js:12:166)
    at W (/home/robert/umami/node_modules/react-spring/node_modules/react/cjs/react.production.min.js:20:375)
    at Object.useMemo (/home/robert/umami/node_modules/react-spring/node_modules/react/cjs/react.production.min.js:23:164)
    at useTransition (/home/robert/umami/node_modules/react-spring/node_modules/@react-spring/core/dist/react-spring-core.cjs.prod.js:2156:21)
    at ThemeButton (/home/robert/umami/.next/server/chunks/838.js:1378:84)
    at d (/home/robert/umami/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:498)
    at bb (/home/robert/umami/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
    at a.b.render (/home/robert/umami/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
    at a.b.read (/home/robert/umami/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)

Error occurred prerendering page "/settings/accounts". Read more: https://nextjs.org/docs/messages/prerender-error
Invariant Violation: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at ca (/home/robert/umami/node_modules/react-spring/node_modules/react/cjs/react.production.min.js:11:316)
    at B (/home/robert/umami/node_modules/react-spring/node_modules/react/cjs/react.production.min.js:12:166)
    at W (/home/robert/umami/node_modules/react-spring/node_modules/react/cjs/react.production.min.js:20:375)
    at Object.useMemo (/home/robert/umami/node_modules/react-spring/node_modules/react/cjs/react.production.min.js:23:164)
    at useTransition (/home/robert/umami/node_modules/react-spring/node_modules/@react-spring/core/dist/react-spring-core.cjs.prod.js:2156:21)
    at ThemeButton (/home/robert/umami/.next/server/chunks/838.js:1378:84)
    at d (/home/robert/umami/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:498)
    at bb (/home/robert/umami/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
    at a.b.render (/home/robert/umami/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
    at a.b.read (/home/robert/umami/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)

Error occurred prerendering page "/settings". Read more: https://nextjs.org/docs/messages/prerender-error
Invariant Violation: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at ca (/home/robert/umami/node_modules/react-spring/node_modules/react/cjs/react.production.min.js:11:316)
    at B (/home/robert/umami/node_modules/react-spring/node_modules/react/cjs/react.production.min.js:12:166)
    at W (/home/robert/umami/node_modules/react-spring/node_modules/react/cjs/react.production.min.js:20:375)
    at Object.useMemo (/home/robert/umami/node_modules/react-spring/node_modules/react/cjs/react.production.min.js:23:164)
    at useTransition (/home/robert/umami/node_modules/react-spring/node_modules/@react-spring/core/dist/react-spring-core.cjs.prod.js:2156:21)
    at ThemeButton (/home/robert/umami/.next/server/chunks/838.js:1378:84)
    at d (/home/robert/umami/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:498)
    at bb (/home/robert/umami/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
    at a.b.render (/home/robert/umami/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
    at a.b.read (/home/robert/umami/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)

Error occurred prerendering page "/settings/profile". Read more: https://nextjs.org/docs/messages/prerender-error
Invariant Violation: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at ca (/home/robert/umami/node_modules/react-spring/node_modules/react/cjs/react.production.min.js:11:316)
    at B (/home/robert/umami/node_modules/react-spring/node_modules/react/cjs/react.production.min.js:12:166)
    at W (/home/robert/umami/node_modules/react-spring/node_modules/react/cjs/react.production.min.js:20:375)
    at Object.useMemo (/home/robert/umami/node_modules/react-spring/node_modules/react/cjs/react.production.min.js:23:164)
    at useTransition (/home/robert/umami/node_modules/react-spring/node_modules/@react-spring/core/dist/react-spring-core.cjs.prod.js:2156:21)
    at ThemeButton (/home/robert/umami/.next/server/chunks/838.js:1378:84)
    at d (/home/robert/umami/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:498)
    at bb (/home/robert/umami/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
    at a.b.render (/home/robert/umami/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
    at a.b.read (/home/robert/umami/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
info  - Generating static pages (11/11)

> Build error occurred
Error: Export encountered errors on following paths:
	/404
	/dashboard/[[...id]]
	/realtime
	/settings
	/settings/accounts
	/settings/profile
    at /home/robert/umami/node_modules/next/dist/export/index.js:395:19
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Span.traceAsyncFn (/home/robert/umami/node_modules/next/dist/trace/trace.js:79:20)
    at async /home/robert/umami/node_modules/next/dist/build/index.js:1118:21
    at async Span.traceAsyncFn (/home/robert/umami/node_modules/next/dist/trace/trace.js:79:20)
    at async /home/robert/umami/node_modules/next/dist/build/index.js:995:17
    at async Span.traceAsyncFn (/home/robert/umami/node_modules/next/dist/trace/trace.js:79:20)
    at async Object.build [as default] (/home/robert/umami/node_modules/next/dist/build/index.js:65:29)
ERROR: "build-app" exited with 1.`

**Comment by aidanm1999** [comment]
Did you follow the [update guide](https://umami.is/docs/updates)? Double check you have installed all packages and updated the database

**Comment by mikecao** [comment]
When it errors out during the build it's usually a memory issue or OS issue. Were you able to build previous versions?
