### ISSUE TITLE
PrismaClientValidationError: Argument event_name for data.event_name is missing.

### ISSUE THREAD

**Issue by barissayil** [umami-software/umami#1423]
Hi,

I started using umami a few days ago and during development I updated to `1.37.0` however I can no longer track events due to this:
```
2022-08-12 09:49:03.968 UTC [58] LOG:  stats_timestamp 2022-08-12 09:49:03.977536+00 is later than collector's time 2022-08-12 09:49:03.96528+00 for database 13470
umami_1  | PrismaClientValidationError: Argument event_name for data.event_name is missing.
umami_1  | 
umami_1  |     at Document.validate (/app/node_modules/@prisma/client/runtime/index.js:27181:20)
umami_1  |     at PrismaClient._executeRequest (/app/node_modules/@prisma/client/runtime/index.js:29694:17)
umami_1  |     at middleware (/app/node_modules/@prisma/client/runtime/index.js:29603:60)
umami_1  |     at consumer (/app/node_modules/@prisma/client/runtime/index.js:29618:24)
umami_1  |     at /app/node_modules/@prisma/client/runtime/index.js:29622:135
umami_1  |     at AsyncResource.runInAsyncScope (node:async_hooks:202:9)
umami_1  |     at callback (/app/node_modules/@prisma/client/runtime/index.js:29622:113)
umami_1  |     at PrismaClient._request (/app/node_modules/@prisma/client/runtime/index.js:29639:22)
umami_1  |     at requestFn (/app/node_modules/@prisma/client/runtime/index.js:28302:65)
umami_1  |     at /app/node_modules/@prisma/client/runtime/index.js:28318:18 {
umami_1  |   clientVersion: '4.1.1'
umami_1  | }
```

I also deleted everything in docker (images, volumes) and retried but I still have this.

It seems that the umami script that I add to `<head>` sends an `umami` that still has the old model. What should I do?

**Comment by barissayil** [comment]
Need to clear cache

**Comment by ahoiroman** [comment]
Got the same problem and I'm wondering, what kind of cache you deleted. The browser's cache?

**Comment by anbraten** [comment]
The browser cache. You have to go to your umami page and there you can simply clear the cache via the browsers dev tools.
