### ISSUE TITLE
POST /api/website fails with error 500

### ISSUE THREAD

**Issue by nicgutierrez** [umami-software/umami#1505]
Trying to create a new website using the API. I'm passing the authorization header and the required payload for this to work, however, the server responds with error 500. Here's the error:

```
2022-09-08T16:40:38.720Z	72873d20-b3a0-4f85-9cba-b74b8b21d27c	ERROR	PrismaClientValidationError: Argument user_id: Got invalid value NaN on prisma.createOnewebsite. Provided Float, expected Int.
    at Document.validate (/var/task/node_modules/@prisma/client/runtime/index.js:28329:20)
    at serializationFn (/var/task/node_modules/@prisma/client/runtime/index.js:30929:19)
    at runInChildSpan (/var/task/node_modules/@prisma/client/runtime/index.js:24157:12)
    at PrismaClient._executeRequest (/var/task/node_modules/@prisma/client/runtime/index.js:30936:31)
    at consumer (/var/task/node_modules/@prisma/client/runtime/index.js:30862:23)
    at /var/task/node_modules/@prisma/client/runtime/index.js:30867:51
    at AsyncResource.runInAsyncScope (node:async_hooks:202:9)
    at /var/task/node_modules/@prisma/client/runtime/index.js:30867:29
    at runInChildSpan (/var/task/node_modules/@prisma/client/runtime/index.js:24157:12)
    at PrismaClient._request (/var/task/node_modules/@prisma/client/runtime/index.js:30864:22) {
  clientVersion: '4.3.1'
}
```

**Comment by briancao** [comment]
Not sure what you're using to call the API manually, but you might have to cast your user_id as an Int instead of a Float.

**Comment by nicgutierrez** [comment]
Hi @briancao 

I'm following the documentation [here](https://umami.is/docs/api). Using axios, I first retrieve the token via user/pass and that's working correctly. I then pass the authorization header to store a website and that's failing. 

I'm not setting the user_id at all.. I'm assuming that somehow is being taken care via the token I'm providing via authorization header.

Here's the request:

```js
    const response = await client.post(`${process.env.UMAMI_URL}/api/website`, {
        domain: `${slug}.${process.env.APP_HOST}`,
        name,
        enable_share_url: false,
      }, {
        headers: { Authorization: `Bearer ${authResponse.data.token}` },
      })
```

**Comment by nicgutierrez** [comment]
I figured it out while looking at the API request going out from the admin panel. I think the documentation might be outdated?

I've updated the request to include an "owner" field and it's now working as expected:

```js
    const response = await client.post(`${process.env.UMAMI_URL}/api/website`, {
      owner: authResponse.data.user.user_id.toString(),
      domain: `${slug}.${process.env.APP_HOST}`,
      name,
      enable_share_url: false,
      public: false,
    }, {
      headers: { Authorization: `Bearer ${authResponse.data.token}` },
    })
```

**Comment by briancao** [comment]
Looks like we had an api update 2 weeks ago that may have affected our documentation.  I'll create an internal ticket to get it updated.
