### ISSUE TITLE
"Connection reset by peer" from Postgres

### ISSUE THREAD

**Issue by khromov** [umami-software/umami#1546]
👋 I'm running a small installation of Umami with a dedicated Postgres database attached.

I noticed that I have a lot of these errors in the Postgres logs, and I wonder if there is anything I can enable on the Umami side to debug this, as I don't want to miss any visits.

```
2022-10-01T05:51:20.826789109Z 2022-10-01 05:51:20.824 UTC [15590] LOG:  could not receive data from client: Connection reset by peer
2022-10-01T06:56:52.985238877Z 2022-10-01 06:56:52.984 UTC [15724] LOG:  could not receive data from client: Connection reset by peer
2022-10-01T07:51:29.787649145Z 2022-10-01 07:51:29.785 UTC [15833] LOG:  could not receive data from client: Connection reset by peer
2022-10-01T08:57:01.945505561Z 2022-10-01 08:57:01.945 UTC [15969] LOG:  could not receive data from client: Connection reset by peer
2022-10-01T09:27:36.955106822Z 2022-10-01 09:27:36.952 UTC [16031] LOG:  could not receive data from client: Connection reset by peer
2022-10-01T10:03:06.873118738Z 2022-10-01 10:03:06.872 UTC [16099] LOG:  could not receive data from client: Connection reset by peer
2022-10-01T11:29:56.985045630Z 2022-10-01 11:29:56.984 UTC [16288] LOG:  could not receive data from client: Connection reset by peer
2022-10-01T11:53:58.781552325Z 2022-10-01 11:53:58.776 UTC [16336] LOG:  could not receive data from client: Connection reset by peer
2022-10-01T12:28:55.929100531Z 2022-10-01 12:28:55.928 UTC [16407] LOG:  could not receive data from client: Connection reset by peer
2022-10-01T13:25:43.801342142Z 2022-10-01 13:25:43.801 UTC [16526] LOG:  could not receive data from client: Connection reset by peer
2022-10-01T13:48:40.057077099Z 2022-10-01 13:48:40.056 UTC [16568] LOG:  could not receive data from client: Connection reset by peer
2022-10-01T14:18:09.529258522Z 2022-10-01 14:18:09.528 UTC [16632] LOG:  could not receive data from client: Connection reset by peer
2022-10-01T14:40:00.249083705Z 2022-10-01 14:40:00.248 UTC [16680] LOG:  could not receive data from client: Connection reset by peer
2022-10-01T15:08:24.187347196Z 2022-10-01 15:08:24.184 UTC [16739] LOG:  could not receive data from client: Connection reset by peer
2022-10-01T15:25:52.761402407Z 2022-10-01 15:25:52.760 UTC [16772] LOG:  could not receive data from client: Connection reset by peer
2022-10-01T16:35:30.683342348Z 2022-10-01 16:35:30.680 UTC [16906] LOG:  could not receive data from client: Connection reset by peer
2022-10-01T18:16:16.379207447Z 2022-10-01 18:16:16.377 UTC [17126] LOG:  could not receive data from client: Connection reset by peer
2022-10-01T18:33:44.955055016Z 2022-10-01 18:33:44.952 UTC [17162] LOG:  could not receive data from client: Connection reset by peer
2022-10-01T18:53:24.601217667Z 2022-10-01 18:53:24.600 UTC [17200] LOG:  could not receive data from client: Connection reset by peer
2022-10-01T19:42:33.724644163Z 2022-10-01 19:42:33.723 UTC [17291] LOG:  could not receive data from client: Connection reset by peer
2022-10-01T20:09:52.121195420Z 2022-10-01 20:09:52.120 UTC [17358] LOG:  could not receive data from client: Connection reset by peer
```

On the Umami side I do occasionally get the error below, but the timing and amount does not match the Postgres errors, which happen once per hour or so.

Example from Umami logs:

```
2022-09-28T18:36:16.976553626Z Error: Invalid request
2022-09-28T18:36:16.976908460Z     at getSession (/app/.next/server/chunks/1649.js:184:15)
2022-09-28T18:36:16.976920345Z     at /app/.next/server/chunks/1649.js:31:86
2022-09-28T18:36:16.976924831Z     at /app/node_modules/next-basics/dist/cjs/index.js:1:65610
2022-09-28T18:36:16.976929509Z     at new Promise (<anonymous>)
2022-09-28T18:36:16.976934858Z     at /app/node_modules/next-basics/dist/cjs/index.js:1:65583
2022-09-28T18:36:16.976939260Z     at __WEBPACK_DEFAULT_EXPORT__ (/app/.next/server/pages/api/collect.js:209:79)
2022-09-28T18:36:16.976943953Z     at runMicrotasks (<anonymous>)
2022-09-28T18:36:16.976948128Z     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-09-28T18:36:16.976952144Z     at async Object.apiResolver (/app/node_modules/next/dist/server/api-utils/node.js:184:9)
2022-09-28T18:36:16.976956212Z     at async NextNodeServer.runApi (/app/node_modules/next/dist/server/next-server.js:403:9)
```

**Comment by mikecao** [comment]
Not sure about the `Connection reset by peer` errors, possibly connections being dropped by the database server.

`Invalid request` you prob don't need to worry about. You can get that when a bot tries to hit an endpoint without passing the correct parameters.

**Comment by flyingjoe** [comment]
We are now at the point where Umami crashes, even when only the last 7 days are selected. We'll look into other solutions as this doesn't work for us.

**Comment by briancao** [comment]
@flyingjoe We have some performance enhancements planned after we release reports.  Unfortunately it sounds like it doesn't fit your timeline.

If you could provide some details on your Umami instance, maybe its something we solve and hotfix.

- What database are you using and what are your database server specs?
- How many total pageviews in the website_event table are there?  And how many are you querying when selecting 7/30/90 days?
- Is there a particular query/api-endpoint that's giving you timeouts?

**Comment by flyingjoe** [comment]
Hi @briancao, 

Tested Server Specs:
-  2 Cores, 4GB (ARM) 
-  4 Cores 16GB (ARM)
- 2 Cores, 2GB (x86)

We saw the same behaviour across all three of these systems. The only difference was that Umami had to be restarted via PM2 on ARM, which is not needed on x86

Our page views:
7 days: 700k
30 days: 3.7 mio
90 days: 7.9 mio 

I tried blocking all api endpoints via nginx and only enabling one at a time. My observations: 
`/pageviews` fine, just slow (30 days: 33s)
`/stats` fine, just slow (30 days: 52s)
`/metrics` (+pageviews, as it won't request it without): umami immediately crashes with nginx reporting 502

So I suspected `/metrics` to be the culprit and tested each query (os, device etc.) individually.
They all run fine individually, though some of them also take more than 20s(!) to complete.

From the attached umami error logs it looks like the connection pool is full the therefore aborting?
Maybe the PrismaClient is not reused correctly? I found this in their documentation: https://www.prisma.io/docs/guides/performance-and-optimization/connection-management#prismaclient-in-long-running-applications

**Comment by briancao** [comment]
Your pageview numbers appear to match if/when most users using our rDBS solution appear to run into performance issues.  Have you tried to increase your connection pool or increase the pool timeout as a interim fix?

I've put in a ticket to add more specific indexing for `/metrics` columns which should help speed up those queries, and hopefully free up connection resources.

We're still working on features for reports at this time, so I can't provide an ETA on that work at this time.

**Comment by flyingjoe** [comment]
Increasing the connection_limit and timeout helped 👍 
Loading the 90 day view now takes around 5 minutes, but at least it loads :)

Looking forward to those performance improvements and thanks for all of your work!

**Comment by flyingjoe** [comment]
Not stale. 90 days is not loading anymore on newest version.

**Comment by screendriver** [comment]
I also have this issue since `2.6.0` (also with 2.6.2):

```sh
umami_db  | 2023-09-01 09:51:11.628 UTC [30] ERROR:  relation "account" does not exist at character 15
umami_db  | 2023-09-01 09:51:11.628 UTC [30] STATEMENT:  select * from account limit 1
umami_db  | 2023-09-01 09:51:12.662 UTC [32] LOG:  could not receive data from client: Connection reset by peer
```

With `2.5.0` everything is working as expected.
