### ISSUE TITLE
1.39.1 realtime logs every visitor show unknown data and no page views 

### ISSUE THREAD

**Issue by lyragosa** [umami-software/umami#1585]
![image](https://user-images.githubusercontent.com/2680509/197694770-736b9349-ed88-42e3-8da6-97fdef6ccbd9.png)

and dont show visit page infomation 

error infomation:

yarn start
yarn run v1.22.19
$ next start
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from /my/install/path/umami/.env
PrismaClientValidationError: Unknown arg `websiteUuid` in where.website.websiteUuid for type WebsiteRelationFilter.

    at Document.validate (/my/install/path/umami/node_modules/@prisma/client/runtime/index.js:28989:20)
    at serializationFn (/my/install/path/umami/node_modules/@prisma/client/runtime/index.js:31900:19)
    at runInChildSpan (/my/install/path/umami/node_modules/@prisma/client/runtime/index.js:25102:12)
    at PrismaClient._executeRequest (/my/install/path/umami/node_modules/@prisma/client/runtime/index.js:31907:31)
    at consumer (/my/install/path/umami/node_modules/@prisma/client/runtime/index.js:31834:23)
    at /my/install/path/umami/node_modules/@prisma/client/runtime/index.js:31839:51
    at AsyncResource.runInAsyncScope (node:async_hooks:202:9)
    at /my/install/path/umami/node_modules/@prisma/client/runtime/index.js:31839:29
    at runInChildSpan (/my/install/path/umami/node_modules/@prisma/client/runtime/index.js:25102:12)
    at PrismaClient._request (/my/install/path/umami/node_modules/@prisma/client/runtime/index.js:31836:22) {
  clientVersion: '4.5.0'
}

**Comment by mskian** [comment]
same here - https://github.com/umami-software/umami/issues/1583#issuecomment-1290037343

**Comment by mikecao** [comment]
Fixed in v1.39.2.
