### ISSUE TITLE
 Cannot read properties of undefined (reading 'id')

### ISSUE THREAD

**Issue by bboysoulcn** [umami-software/umami#1602]
```bash
umami  | TypeError: Cannot read properties of undefined (reading 'id')
umami  |     at __WEBPACK_DEFAULT_EXPORT__ (/app/.next/server/pages/api/websites.js:163:29)
umami  |     at runMicrotasks (<anonymous>)
umami  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
umami  |     at async Object.apiResolver (/app/node_modules/next/dist/server/api-utils/node.js:366:9)
umami  |     at async NextNodeServer.runApi (/app/node_modules/next/dist/server/next-server.js:481:9)
umami  |     at async Object.fn (/app/node_modules/next/dist/server/next-server.js:735:37)
umami  |     at async Router.execute (/app/node_modules/next/dist/server/router.js:247:36)
umami  |     at async NextNodeServer.run (/app/node_modules/next/dist/server/base-server.js:347:29)
umami  |     at async NextNodeServer.handleRequest (/app/node_modules/next/dist/server/base-server.js:285:20)
umami  |     at async Server.<anonymous> (/app/server.js:19:5)
```

**Comment by briancao** [comment]
What version of umami are you on?  And did your migrations run ok?

**Comment by FunctionalHacker** [comment]
I fixed the same error by logging out and logging back in.

**Comment by LoaderB0T** [comment]
Hi, I had the same issue.
I updated from [v1.38.0](https://github.com/umami-software/umami/releases/tag/v1.38.0) to [v1.39.2](https://github.com/umami-software/umami/releases/tag/v1.39.2) and got the error in the logs.
Logging out and back in fixed it for me too. Migrations (`04_add_uuid`) ran successfully.
I guess the local state saved in the browser is invalid after the update?

**Comment by davquar** [comment]
Hi, same problem and same fix by logging out

**Comment by briancao** [comment]
@LoaderB0T Correct.  We're thinking of changing the process to auto-log users out on version updates.
