### ISSUE TITLE
Error creating UUID, invalid length: expected length 32 for simple format, found 1

### ISSUE THREAD

**Issue by dipakparmar** [umami-software/umami#1603]
When updating the previously created Website for the share URL, it errors the following:

```
{
    message: 'Error creating UUID, invalid length: expected length 32 for simple format, found 1'
  }
}
PrismaClientKnownRequestError: 
Invalid `prisma.website.findUnique()` invocation:
Inconsistent column data: Error creating UUID, invalid length: expected length 32 for simple format, found 1
    at RequestHandler.handleRequestError (/app/node_modules/@prisma/client/runtime/index.js:30873:13)
    at RequestHandler.request (/app/node_modules/@prisma/client/runtime/index.js:30856:12)
    at async PrismaClient._request (/app/node_modules/@prisma/client/runtime/index.js:31836:16)
    at async __WEBPACK_DEFAULT_EXPORT__ (/app/.next/server/pages/api/websites/[id].js:173:26)
    at async Object.apiResolver (/app/node_modules/next/dist/server/api-utils/node.js:366:9)
    at async NextNodeServer.runApi (/app/node_modules/next/dist/server/next-server.js:481:9)
    at async Object.fn (/app/node_modules/next/dist/server/next-server.js:735:37)
    at async Router.execute (/app/node_modules/next/dist/server/router.js:247:36)
    at async NextNodeServer.run (/app/node_modules/next/dist/server/base-server.js:347:29)
    at async NextNodeServer.handleRequest (/app/node_modules/next/dist/server/base-server.js:285:20) {
  code: 'P2023',
  clientVersion: '4.5.0',
```

Umami Version/Image: ghcr.io/umami-software/umami:postgresql-v1.39.2

**Comment by briancao** [comment]
Confirming bug.  I'll have a fix tomorrow.

**Comment by titou26140** [comment]
Same here. Thank you for your work !

**Comment by mikecao** [comment]
Fixed in v1.39.3
