### ISSUE TITLE
The column `account.account_uuid` does not exist in the current database after upgrading to 1.39.2

### ISSUE THREAD

**Issue by ahoiroman** [umami-software/umami#1604]
Getting

```
✓ Database is up to date.
$ node scripts/update-tracker.js
$ node server.js
Listening on port 3000
TypeError: Cannot read properties of undefined (reading 'id')
    at __WEBPACK_DEFAULT_EXPORT__ (/app/.next/server/pages/api/websites.js:163:29)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.apiResolver (/app/node_modules/next/dist/server/api-utils/node.js:366:9)
    at async NextNodeServer.runApi (/app/node_modules/next/dist/server/next-server.js:481:9)
    at async Object.fn (/app/node_modules/next/dist/server/next-server.js:735:37)
    at async Router.execute (/app/node_modules/next/dist/server/router.js:247:36)
    at async NextNodeServer.run (/app/node_modules/next/dist/server/base-server.js:347:29)
    at async NextNodeServer.handleRequest (/app/node_modules/next/dist/server/base-server.js:285:20)
    at async Server.<anonymous> (/app/server.js:19:5)
TypeError: Cannot read properties of undefined (reading 'id')
    at __WEBPACK_DEFAULT_EXPORT__ (/app/.next/server/pages/api/websites.js:163:29)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.apiResolver (/app/node_modules/next/dist/server/api-utils/node.js:366:9)
    at async NextNodeServer.runApi (/app/node_modules/next/dist/server/next-server.js:481:9)
    at async Object.fn (/app/node_modules/next/dist/server/next-server.js:735:37)
    at async Router.execute (/app/node_modules/next/dist/server/router.js:247:36)
    at async NextNodeServer.run (/app/node_modules/next/dist/server/base-server.js:347:29)
    at async NextNodeServer.handleRequest (/app/node_modules/next/dist/server/base-server.js:285:20)
    at async Server.<anonymous> (/app/server.js:19:5)
TypeError: Cannot read properties of undefined (reading 'id')
    at __WEBPACK_DEFAULT_EXPORT__ (/app/.next/server/pages/api/websites.js:163:29)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.apiResolver (/app/node_modules/next/dist/server/api-utils/node.js:366:9)
    at async NextNodeServer.runApi (/app/node_modules/next/dist/server/next-server.js:481:9)
    at async Object.fn (/app/node_modules/next/dist/server/next-server.js:735:37)
    at async Router.execute (/app/node_modules/next/dist/server/router.js:247:36)
    at async NextNodeServer.run (/app/node_modules/next/dist/server/base-server.js:347:29)
    at async NextNodeServer.handleRequest (/app/node_modules/next/dist/server/base-server.js:285:20)
    at async Server.<anonymous> (/app/server.js:19:5)
PrismaClientKnownRequestError:
Invalid `prisma.account.findUnique()` invocation:


The column `account.account_uuid` does not exist in the current database.
    at RequestHandler.handleRequestError (/app/node_modules/@prisma/client/runtime/index.js:30873:13)
    at RequestHandler.request (/app/node_modules/@prisma/client/runtime/index.js:30856:12)
    at async PrismaClient._request (/app/node_modules/@prisma/client/runtime/index.js:31836:16)
    at async __WEBPACK_DEFAULT_EXPORT__ (/app/.next/server/pages/api/auth/login.js:107:21)
    at async Object.apiResolver (/app/node_modules/next/dist/server/api-utils/node.js:366:9)
    at async NextNodeServer.runApi (/app/node_modules/next/dist/server/next-server.js:481:9)
    at async Object.fn (/app/node_modules/next/dist/server/next-server.js:735:37)
    at async Router.execute (/app/node_modules/next/dist/server/router.js:247:36)
    at async NextNodeServer.run (/app/node_modules/next/dist/server/base-server.js:347:29)
    at async NextNodeServer.handleRequest (/app/node_modules/next/dist/server/base-server.js:285:20) {
  code: 'P2022',
  clientVersion: '4.5.0',
  meta: { column: 'account.account_uuid' }
}
```

after upgrading to 1.39.2 .

Logging out and logging back in does NOT solve the problem here.

**Comment by seriousm4x** [comment]
same here

**Comment by briancao** [comment]
If account_uuid column does not exists, then the latest migration did not run.  If you tried to install 1.39.0 or 1.39.1, there was a known issue with migrations not running on older versions of postgres (v12 and under had issues).

You'll have to delete the migration from prisma migration..

`delete from _prisma_migrations where migration_name = '04_add_uuid';`

Then rebuild umami, to apply the latest fix.

**Comment by MoltenCoffee** [comment]
In my case, both migration 03 and 04 hadn't run. Running `yarn update-db` myself (which runs prisma in turn) applied the patches and got me running again

**Comment by ahoiroman** [comment]
Hey there,

thanks for your replies. Is there any documentation on how to perform those steps in a docker-based installation?

Thanks in advance :-)

**Comment by ngmathiou** [comment]
I'm also getting the same error, trying to run
`yarn update-db`

I get the bellow error:

yarn run v1.22.19
$ prisma migrate deploy
Prisma schema loaded from prisma/schema.prisma
Datasource "db": MySQL database "umami" at "10.0.0.1:3306"

4 migrations found in prisma/migrations

Error: **Table 'umami._prisma_migrations' doesn't exist in engine**
   0: migration_core::state::ApplyMigrations
             at migration-engine/core/src/state.rs:186

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.


My MySQL version is:
`10.9.3-MariaDB`

**Comment by jeroenpelgrims** [comment]
> Hey there,
> 
> thanks for your replies. Is there any documentation on how to perform those steps in a docker-based installation?
> 
> Thanks in advance :-)

The delete query mentioned above can be run by `exec`'ing into the db container.
For Postgres: Run the following in the folder with your docker-compose file in it:
```docker-compose exec <postgres_service_name> /bin/bash```
A terminal will open inside your container. There you run:
```PGPASSWORD=<database-password> psql -h localhost -U <database-user> -p 5432 -d <database-name> -c "delete from _prisma_migrations where migration_name = '04_add_uuid';"```
This should also work and be copy-pastable:
```PGPASSWORD=$POSTGRES_PASSWORD psql -h localhost -U $POSTGRES_USER -p 5432 -d $POSTGRES_DB -c "delete from _prisma_migrations where migration_name = '04_add_uuid';"```

Now, I assume the next step would be to update the postgres container to >v12 and then try to update umami. (so the migration can run again)
I'll update this post if i find a solution.

**Comment by imok7** [comment]
If you guy use docker-compose，you can fix this problem by using lower version  of docker image.  It works.

exg:
image: docker.umami.dev/umami-software/umami:postgresql-v1.33.3

 #postgresql-latest

**Comment by calvinbui** [comment]
I had the same issue but `02_add_event_data` had failed.

I exec'd into the umami container and ran:

```
/app $ yarn prisma migrate resolve --applied 01_init
yarn run v1.22.19
$ /app/node_modules/.bin/prisma migrate resolve --applied 01_init
...
Migration 01_init marked as applied.
Done in 1.67s.
```

Then performed the upgrade again with `yarn update-db`
