### ISSUE TITLE
Unknown column 'event_name' in 'field list'

### ISSUE THREAD

**Issue by mauricerenck** [umami-software/umami#1619]
I run umami on a koyeb instance using the docker image. As a database I use MySQL on a remote host.

It runs normally but in the logs I see the following error quite often:

```
PrismaClientKnownRequestError:
Invalid `prisma.event.findMany()` invocation:
The column `XXXXXXX.event.event_name` does not exist in the current database.
at RequestHandler.handleRequestError (/app/node_modules/@prisma/client/runtime/index.js:30873:13)
at RequestHandler.request (/app/node_modules/@prisma/client/runtime/index.js:30856:12)
at async PrismaClient._request (/app/node_modules/@prisma/client/runtime/index.js:31836:16)
at async Promise.all (index 2)
at async getRealtimeData (/app/.next/server/chunks/9447.js:2036:43)
at async __WEBPACK_DEFAULT_EXPORT__ (/app/.next/server/pages/api/realtime/init.js:160:22)
at async Object.apiResolver (/app/node_modules/next/dist/server/api-utils/node.js:366:9)
at async NextNodeServer.runApi (/app/node_modules/next/dist/server/next-server.js:481:9)
at async Object.fn (/app/node_modules/next/dist/server/next-server.js:735:37)
at async Router.execute (/app/node_modules/next/dist/server/router.js:247:36) {
code: 'P2022',
clientVersion: '4.5.0',
meta: { column: 'XXXXXX.event.event_name' }
}
```

Migrations are all done:

```
Running update...
Prisma schema loaded from prisma/schema.prisma
Datasource "db": MySQL database "XXXXXXX" at "XXXXXXXXX"
4 migrations found in prisma/migrations
Applying migration `04_add_uuid`
The following migration have been applied:
migrations/
└─ 04_add_uuid/
└─ migration.sql
All migrations have been successfully applied.
✓ Database is up to date.
```

Running it locally (with the same db) gives me the same error in the console.
In the UI no events are shown.

**Comment by mauricerenck** [comment]
I do have the `event_data` table, but no `event_name` field in the `event` table.
