### ISSUE TITLE
node server.js error on 1.39.4

### ISSUE THREAD

**Issue by Ti-Tom** [umami-software/umami#1646]
image: ghcr.io/umami-software/umami:mysql-latest (1.39.4)

Logs from docker compose:
```
umami-umami-1  | yarn run v1.22.19
umami-umami-1  | $ npm-run-all check-db update-tracker start-server
umami-umami-1  | $ node scripts/check-db.js
umami-umami-1  | ✓ DATABASE_URL is defined.
umami-umami-1  | ✓ Database connection successful.
umami-umami-1  | ✓ Database tables found.
umami-umami-1  | Prisma schema loaded from prisma/schema.prisma
umami-umami-1  | Datasource "db": MySQL database "umami" at "IP:PORT"
umami-umami-1  | 
umami-umami-1  | 4 migrations found in prisma/migrations
umami-umami-1  | 
umami-umami-1  | 
umami-umami-1  | Database schema is up to date!
umami-umami-1  | 
umami-umami-1  | ✓ Database is up to date.
umami-umami-1  | $ node scripts/update-tracker.js
umami-umami-1  | $ node server.js
umami-umami-1  | error Command failed with signal "SIGILL".
umami-umami-1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
umami-umami-1  | ERROR: "start-server" exited with 1.
umami-umami-1  | error Command failed with exit code 1.
umami-umami-1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

And when i execute `docker exec -it umami-umami-1 yarn run --verbose start-server`
```
yarn run v1.22.19
verbose 2.313491253 Checking for configuration file "/app/.npmrc".
verbose 2.320557567 Checking for configuration file "/home/nextjs/.npmrc".
verbose 2.326562077 Checking for configuration file "/usr/local/etc/npmrc".
verbose 2.332092301 Checking for configuration file "/app/.npmrc".
verbose 2.341789315 Checking for configuration file "/app/.yarnrc".
verbose 2.349882253 Checking for configuration file "/home/nextjs/.yarnrc".
verbose 2.355206499 Checking for configuration file "/usr/local/etc/yarnrc".
verbose 2.361066927 Checking for configuration file "/app/.yarnrc".
verbose 2.400271389 current time: 2022-11-09T08:54:05.555Z
$ node server.js
verbose 13.331250456 Error: Command failed with signal "SIGILL".
    at ProcessTermError.ExtendableBuiltin (/opt/yarn-v1.22.19/lib/cli.js:721:66)
    at ProcessTermError.MessageError (/opt/yarn-v1.22.19/lib/cli.js:750:123)
    at new ProcessTermError (/opt/yarn-v1.22.19/lib/cli.js:790:113)
    at /opt/yarn-v1.22.19/lib/cli.js:34406:30
    at Generator.throw (<anonymous>)
    at step (/opt/yarn-v1.22.19/lib/cli.js:310:30)
    at /opt/yarn-v1.22.19/lib/cli.js:323:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error Command failed with signal "SIGILL".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

EDIT: work with previous release 1.39.3

**Comment by Teufeuleu** [comment]
Got the exact same issue while updating from v1.33.5 to v1.39.5 (using docker-compose).
Couldn't trace the problem further, but the update worked with 1.39.3.
