### ISSUE TITLE
Error on /api/collect endpoint after update

### ISSUE THREAD

**Issue by ocha** [umami-software/umami#1660]
I am seeing following error on every `/api/collect` post since updating to latest version:
```
umami_1         | TypeError: Cannot read properties of null (reading 'id')
umami_1         |     at relationalQuery (/app/.next/server/chunks/9447.js:1676:65)
umami_1         |     at Object.prisma (/app/.next/server/chunks/9447.js:1672:69)
umami_1         |     at runQuery (/app/.next/server/chunks/9447.js:296:31)
umami_1         |     at savePageView (/app/.next/server/chunks/9447.js:1671:70)
umami_1         |     at __WEBPACK_DEFAULT_EXPORT__ (/app/.next/server/pages/api/collect.js:218:78)
umami_1         |     at runMicrotasks (<anonymous>)
umami_1         |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
umami_1         |     at async Object.apiResolver (/app/node_modules/next/dist/server/api-utils/node.js:366:9)
umami_1         |     at async NextNodeServer.runApi (/app/node_modules/next/dist/server/next-server.js:481:9)
umami_1         |     at async Object.fn (/app/node_modules/next/dist/server/next-server.js:735:37)
```

I have uuid columns in DB so I don't think it is related to the UUID issue described in https://github.com/umami-software/umami/issues/1598

Is there a way to get the mapping to the source file where the error occurs or more verbose logs?

**Comment by ocha** [comment]
I nuked the DB and had umami recreate it - still the same problem. Is there a way to log SQL queries?

**Comment by ocha** [comment]
I figured it out. Issue is present if redis is enabled using REDIS_URL. once I removed redis, it started working again.
