### ISSUE TITLE
Server side throwing `TypeError: Cannot read properties of null (reading 'id')` error when updating the page view

### ISSUE THREAD

**Issue by boris1993** [umami-software/umami#1763]
Using master branch in [my fork](https://github.com/boris1993/umami).
Deploying in Railway.

Full error log: 

```
TypeError: Cannot read properties of null (reading 'id')
at relationalQuery (/app/.next/server/chunks/9447.js:1676:65)
at Object.prisma (/app/.next/server/chunks/9447.js:1672:69)
at runQuery (/app/.next/server/chunks/9447.js:296:31)
at savePageView (/app/.next/server/chunks/9447.js:1671:70)
at __WEBPACK_DEFAULT_EXPORT__ (/app/.next/server/pages/api/collect.js:218:78)
at async Object.apiResolver (/app/node_modules/next/dist/server/api-utils/node.js:366:9)
at async NextNodeServer.runApi (/app/node_modules/next/dist/server/next-server.js:481:9)
at async Object.fn (/app/node_modules/next/dist/server/next-server.js:735:37)
at async Router.execute (/app/node_modules/next/dist/server/router.js:247:36)
at async NextNodeServer.run (/app/node_modules/next/dist/server/base-server.js:347:29)
```

**Comment by boris1993** [comment]
Seems like caused by bad sequence. Because I was migrating the database from Supabase to Railway.
