### ISSUE TITLE
ERR! ERESOLVE unable to resolve dependency tree

### ISSUE THREAD

**Issue by bernd-wechner** [umami-software/umami#1786]
I just tried to update, so pulled the latest codebase, and ran:

```
$ sudo -u umami npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: umami@1.40.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.0" from the root project
npm ERR!   peer react@"^17.0.2 || ^18.0.0-0" from next@12.3.4
npm ERR!   node_modules/next
npm ERR!     next@"^12.3.1" from the root project
npm ERR!     peer next@"^12.2.5" from next-basics@0.18.0
npm ERR!     node_modules/next-basics
npm ERR!       next-basics@"^0.18.0" from the root project
npm ERR!   1 more (react-dom)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^18.2.0" from next-basics@0.18.0
npm ERR! node_modules/next-basics
npm ERR!   next-basics@"^0.18.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/umami/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/umami/.npm/_logs/2023-02-15T05_28_58_684Z-debug-0.log
```

If only npm could manage to write lucid error reports in moderately natural language. I cannot decipher this without some upskilling, but clearly something to do with react and next-basics.

Any tips for someone keen to understand/learn and or how a dependency tree can be broken?

**Comment by mikecao** [comment]
Have you tried using yarn instead?

**Comment by bernd-wechner** [comment]
No. No experience with that. How do I do that?

**Comment by bernd-wechner** [comment]
Worked it out. That updated fine, built fin and starts fine. Alas Now when I try to log in:

```
Feb 16 12:13:30 shelob yarn[259269]: The column `account.account_uuid` does not exist in the current database.
Feb 16 12:13:30 shelob yarn[259269]:     at RequestHandler.handleRequestError (/home/umami/umami/node_modules/@prisma/client/runtime/index.js:3194>
Feb 16 12:13:30 shelob yarn[259269]:     at RequestHandler.handleAndLogRequestError (/home/umami/umami/node_modules/@prisma/client/runtime/index.j>
Feb 16 12:13:30 shelob yarn[259269]:     at RequestHandler.request (/home/umami/umami/node_modules/@prisma/client/runtime/index.js:31908:12)
Feb 16 12:13:30 shelob yarn[259269]:     at async PrismaClient._request (/home/umami/umami/node_modules/@prisma/client/runtime/index.js:32994:16)
Feb 16 12:13:30 shelob yarn[259269]:     at async __WEBPACK_DEFAULT_EXPORT__ (/home/umami/umami/.next/server/pages/api/auth/login.js:107:21)
Feb 16 12:13:30 shelob yarn[259269]:     at async Object.apiResolver (/home/umami/umami/node_modules/next/dist/server/api-utils/node.js:366:9)
Feb 16 12:13:30 shelob yarn[259269]:     at async NextNodeServer.runApi (/home/umami/umami/node_modules/next/dist/server/next-server.js:481:9)
Feb 16 12:13:30 shelob yarn[259269]:     at async Object.fn (/home/umami/umami/node_modules/next/dist/server/next-server.js:735:37)
Feb 16 12:13:30 shelob yarn[259269]:     at async Router.execute (/home/umami/umami/node_modules/next/dist/server/router.js:247:36)
Feb 16 12:13:30 shelob yarn[259269]:     at async NextNodeServer.run (/home/umami/umami/node_modules/next/dist/server/base-server.js:347:29) {
Feb 16 12:13:30 shelob yarn[259269]:   code: 'P2022',
Feb 16 12:13:30 shelob yarn[259269]:   clientVersion: '4.9.0',
Feb 16 12:13:30 shelob yarn[259269]:   meta: { column: 'account.account_uuid' },
Feb 16 12:13:30 shelob yarn[259269]:   batchRequestIdx: undefined
Feb 16 12:13:30 shelob yarn[259269]: }
```

Oh the joys. I shall drill down I guess.  Silly me should have backed that database up ;-)

**Comment by bernd-wechner** [comment]
Looking into the database with psql, I see everything looks good. All my data seems intact ;-) but:

```
umami=# \d account
                                         Table "public.account"
   Column   |           Type           | Collation | Nullable |                 Default
------------+--------------------------+-----------+----------+------------------------------------------
 user_id    | integer                  |           | not null | nextval('account_user_id_seq'::regclass)
 username   | character varying(255)   |           | not null |
 password   | character varying(60)    |           | not null |
 is_admin   | boolean                  |           | not null | false
 created_at | timestamp with time zone |           |          | CURRENT_TIMESTAMP
 updated_at | timestamp with time zone |           |          | CURRENT_TIMESTAMP
Indexes:
    "account_pkey" PRIMARY KEY, btree (user_id)
    "account_username_key" UNIQUE CONSTRAINT, btree (username)
Referenced by:
    TABLE "website" CONSTRAINT "website_user_id_fkey" FOREIGN KEY (user_id) REFERENCES account(user_id) ON UPDATE CASCADE ON DELETE RESTRICT
```

reveals account_uuid is missing. Indeed. It seems in the yard build a migration was missed. Is this indicative of a deeper problem? I could create a single column, and even populate it (only have two accounts on the system). But it is worrying that I saw yarn apply migrations but it seems to have missed one?

**Comment by bernd-wechner** [comment]
And before I fiddles with schema by hand I'd want to know what else may have changed on it.

**Comment by bernd-wechner** [comment]
But guess what:

https://github.com/umami-software/umami/blob/master/sql/schema.postgresql.sql

It's not even in the schema! Dear me.

**Comment by bernd-wechner** [comment]
It looks like this migration:

https://github.com/umami-software/umami/blob/aceb904398b527658676879b11ff22135b7cbaf8/db/postgresql/migrations/04_add_uuid/migration.sql

was not applied!

**Comment by bernd-wechner** [comment]
So now, I need to work out which migrations have been applied and how to check and apply migrations.

**Comment by bernd-wechner** [comment]
Done. Inspected migrations 1 to 3 and confirmed they are all in my schema already, then ran migration 4 with psql and now I can log in again and it looks like I'm updated.
