### ISSUE TITLE
Migration error

### ISSUE THREAD

**Issue by edcous** [umami-software/umami#1888]
When running `npx @umami/migrate-v1-v2` I receive the following error:

```Database type detected: postgresql
✓ Copied /root/.npm/_npx/1eeacd173acbda61/node_modules/@umami/migrate-v1-v2/db/postgresql to /root/.npm/_npx/1eeacd173acbda61/node_modules/@umami/migrate-v1-v2/prisma
prisma:warn The postinstall script automatically ran `prisma generate` and did not find your `prisma/schema.prisma`.
If you have a Prisma schema file in a custom path, you will need to run
`prisma generate --schema=./path/to/your/schema.prisma` to generate Prisma Client.
If you do not have a Prisma schema file yet, you can ignore this message.
Environment variables loaded from .env


/root/.npm/_npx/1eeacd173acbda61/node_modules/.prisma/client/index.js:3
    throw new Error(
    ^

Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
In case this error is unexpected for you, please report it in https://github.com/prisma/prisma/issues
    at new PrismaClient (/root/.npm/_npx/1eeacd173acbda61/node_modules/.prisma/client/index.js:3:11)
    at Object.<anonymous> (/root/.npm/_npx/1eeacd173acbda61/node_modules/@umami/migrate-v1-v2/migrate-db.js:327:16)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47

Node.js v19.9.0
```

**Comment by franciscao633** [comment]
Can you try rerunning the npx command? There's a bug in the script with timing the prisma generate that we need to resolve.

**Comment by edcous** [comment]
Same error.

**Comment by bluelinden** [comment]
similar (possibly related?) error here:

```
╭─ /var/www/analytics/umami on master !2 ?155 ········································································································ took 32s at 00:16:15
╰─❯ npx @umami/migrate-v1-v2        
Database type detected: mysql
✓ Copied /home/blue/.npm/_npx/1eeacd173acbda61/node_modules/@umami/migrate-v1-v2/db/mysql to /home/blue/.npm/_npx/1eeacd173acbda61/node_modules/@umami/migrate-v1-v2/prisma
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma

✔ Generated Prisma Client (4.11.0 | library) to ./node_modules/@prisma/client in 963ms
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
\`\`\`
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
\`\`\`

/home/blue/.npm/_npx/1eeacd173acbda61/node_modules/.prisma/client/index.js:3
    throw new Error(
    ^

Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
In case this error is unexpected for you, please report it in https://github.com/prisma/prisma/issues
    at new PrismaClient (/home/blue/.npm/_npx/1eeacd173acbda61/node_modules/.prisma/client/index.js:3:11)
    at Object.<anonymous> (/home/blue/.npm/_npx/1eeacd173acbda61/node_modules/@umami/migrate-v1-v2/migrate-db.js:327:16)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47
```

**Comment by franciscao633** [comment]
yes same error. I'm trying to get in a fix now.

**Comment by dhwaj1902** [comment]
Same error.

**Comment by bboysoulcn** [comment]
the same issue

**Comment by mskian** [comment]
try this work for me

```sh
git clone https://github.com/umami-software/migrate-v1-v2.git
cd migrate-v1-v2

# create env file add your umami database connection URL
touch .env

## env content
```
DB_USER=
DB_PASSWORD=
DB_HOST=localhost
DB_PORT=3306
DB_NAME=myumami
DATABASE_URL=mysql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAM
```

## build and migrate it done
yarn install
yarn build
```

**Comment by franciscao633** [comment]
We're doing away with the npx command. Had a bunch of issues getting it to work with prisma. Please see the new docs on how to run the migration. https://umami.is/docs/migrate-v1-v2

**Comment by timoschwarzer** [comment]
I still get the same error, even with the updated docs.

I ran these commands inside the umami directory (where its node_modules sit):

```sh
yarn add @umami/migrate-v1-v2
npx @umami/migrate-v1-v2
```

**Comment by franciscao633** [comment]
Had a day to smooth things out with the npx command and updated the docs. There will now be 2 options to migrate. Please continue to report any bugs you see, thanks again for helping us out!
