### ISSUE TITLE
Migration error v1 to v2

### ISSUE THREAD

**Issue by thomasbnt** [umami-software/umami#1890]
Hello, when I type `npx @umami/migrate-v1-v2` after pull the latest version for migrating to v1 -> v2, I've got this error :
```bash
# npx @umami/migrate-v1-v2
Database type detected: mysql
/.npm/_npx/1eeacd173acbda61/node_modules/@umami/migrate-v1-v2/index.js:52
      throw new Error('Unable to copy db files.');
            ^

Error: Unable to copy db files.
    at copyDbFiles (/.npm/_npx/1eeacd173acbda61/node_modules/@umami/migrate-v1-v2/index.js:52:13)
    at /.npm/_npx/1eeacd173acbda61/node_modules/@umami/migrate-v1-v2/index.js:326:9
    at Object.<anonymous> (/.npm/_npx/1eeacd173acbda61/node_modules/@umami/migrate-v1-v2/index.js:354:3)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1147:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47

Node.js v17.0.1
```

Maybe linked to this issue https://github.com/umami-software/umami/issues/1888

**Comment by franciscao633** [comment]
We're doing away with the npx command. Had a bunch of issues getting it to work with prisma. Please see the new docs on how to run the migration. https://umami.is/docs/migrate-v1-v2

**Comment by thomasbnt** [comment]
> We're doing away with the npx command. Had a bunch of issues getting it to work with prisma. Please see the new docs on how to run the migration. [umami.is/docs/migrate-v1-v2](https://umami.is/docs/migrate-v1-v2)

Okay this is **better** @franciscao633 ! Thanks!
