### ISSUE TITLE
Unknown field 'teamUser'

### ISSUE THREAD

**Issue by thomasbnt** [umami-software/umami#1893]
Hello ! 
I upgraded to the v2, good work thanks!

When I go to `/settings/teams`, I've got an internal error (500), in the terminal I've got that : 

```bash
5|umami  | PrismaClientValidationError:
5|umami  | Unknown field `teamUser` for include statement on model Team. Did you mean `teamUsers`?
5|umami  |     at mi.validate (/node_modules/@prisma/client/runtime/library.js:149:91)
5|umami  |     at rn.createMessage (/node_modules/@prisma/client/runtime/library.js:164:13651)
5|umami  |     at /node_modules/@prisma/client/runtime/library.js:177:10955
5|umami  |     at runInChildSpan (/node_modules/@prisma/client/runtime/library.js:70:25817)
5|umami  |     at t._executeRequest (/node_modules/@prisma/client/runtime/library.js:177:10944) {
5|umami  |   clientVersion: '4.12.0'
5|umami  | }
```

**Comment by franciscao633** [comment]
Hello, I'm trying to track down the error. Is your instance using MySQL or postgres?

**Comment by thomasbnt** [comment]
> Hello, I'm trying to track down the error. Is your instance using MySQL or postgres?

Hello! I've got MariaDB!

**Comment by franciscao633** [comment]
This is fixed in dev. Will release a hotfix with as many bugs included as we can.

**Comment by thomasbnt** [comment]
Thanks!
