### ISSUE TITLE
V2 delete user: Invalid prisma.team.findMany()

### ISSUE THREAD

**Issue by atmonshi** [umami-software/umami#1894]
Hello, thank you, and congrats on the new V2 :)

After upgrading, I created a user, and then try to delete it:

```
yarn run v1.22.19
$ next dev -p 3000
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from /Users/atmonshi/Sites/umami/.env
event - compiled client and server successfully in 628 ms (1211 modules)
wait  - compiling /settings/users (client and server)...
event - compiled client and server successfully in 264 ms (1419 modules)
wait  - compiling /api/config (client and server)...
wait  - compiling /api/auth/verify (client and server)...
wait  - compiling /api/scripts/telemetry (client and server)...
event - compiled successfully in 40 ms (146 modules)
wait  - compiling...
event - compiled successfully in 0 ms (197 modules)
wait  - compiling...
event - compiled successfully in 0 ms (197 modules)
wait  - compiling /api/users (client and server)...
event - compiled successfully in 17 ms (198 modules)
wait  - compiling /api/users/[id] (client and server)...
event - compiled successfully in 53 ms (199 modules)
error - PrismaClientValidationError:
Invalid `prisma.team.findMany()` invocation:

{
  where: {
    teamUser: {
    ~~~~~~~~
      some: {
        userId: 'b2a7f0cf-b5e6-436a-bd2f-32f270bedacc',
        role: 'team-owner'
      }
    }
  }
}

Unknown arg `teamUser` in where.teamUser for type TeamWhereInput. Did you mean `teamUsers`? Available args:
type TeamWhereInput {
  AND?: TeamWhereInput | List<TeamWhereInput>
  OR?: List<TeamWhereInput>
  NOT?: TeamWhereInput | List<TeamWhereInput>
  id?: StringFilter | String
  name?: StringFilter | String
  accessCode?: StringNullableFilter | String | Null
  createdAt?: DateTimeNullableFilter | DateTime | Null
  updatedAt?: DateTimeNullableFilter | DateTime | Null
  teamUsers?: TeamUserListRelationFilter
  teamWebsite?: TeamWebsiteListRelationFilter
}


    at ti.validate (/Users/atmonshi/Sites/umami/node_modules/@prisma/client/runtime/library.js:149:91)
    at Wr.createMessage (/Users/atmonshi/Sites/umami/node_modules/@prisma/client/runtime/library.js:164:13655)
    at /Users/atmonshi/Sites/umami/node_modules/@prisma/client/runtime/library.js:174:10933
    at runInChildSpan (/Users/atmonshi/Sites/umami/node_modules/@prisma/client/runtime/library.js:70:25817)
    at t._executeRequest (/Users/atmonshi/Sites/umami/node_modules/@prisma/client/runtime/library.js:174:10922) {
  clientVersion: '4.11.0',
  page: '/api/users/[id]'
}
wait  - compiling /_error (client and server)...
event - compiled client and server successfully in 111 ms (1482 modules)
```

**Comment by franciscao633** [comment]
Looks like the same issue as below #1893. I'm going to close this and combine the issues into one. If you can tell me what db your using also It will help us. Thank you.
