### ISSUE TITLE
[BUG][2.0.0] Cannot npm install 

### ISSUE THREAD

**Issue by gander** [umami-software/umami#1902]
# v2.0.0

```shell
npm install 
```
Result:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: umami@2.0.0
npm ERR! Found: next@13.2.4
npm ERR! node_modules/next
npm ERR!   next@"^13.2.3" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer next@"^12.3.2" from next-basics@0.27.0
npm ERR! node_modules/next-basics
npm ERR!   next-basics@"^0.27.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```
```
Running node v16.20.0 (npm v8.19.4)
Running node v14.21.2 (npm v9.3.1)
Running node v12.22.12 (npm v8.19.3)
```

**Comment by franciscao633** [comment]
Hello, is this a clean install and not a v1 upgrade? Just need a little more info to help target the issue. Thanks!

**Comment by rohandebsarkar** [comment]
I also faced a similar issue while using `npm install`, but instead using `yarn install` works.

**Comment by gander** [comment]
It was freshly downloaded repository and checkout on tag v2.0.0

**Comment by franciscao633** [comment]
The dependency issues might be coming from the node version. The docs state you need a node version of 14.3 or newer to run Umami. Alternatively you can try to install with legacy `npm install --legacy-peer-deps` and see if that works

https://umami.is/docs/install

**Comment by ammar-madni** [comment]
> I also faced a similar issue while using `npm install`, but instead using `yarn install` works.

`yarn install` worked for me too.

**Comment by bernd-wechner** [comment]
I tried `yarn install`:

```
$ sudo -u umami yarn install
yarn install v1.22.19
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
[2/4] Fetching packages...
warning chart.js@4.3.0: The engine "pnpm" appears to be invalid.
[3/4] Linking dependencies...
warning " > next-basics@0.27.0" has incorrect peer dependency "next@^12.3.2".
warning "react-basics > react-spring > @react-spring/konva@9.7.2" has unmet peer dependency "konva@>=2.6".
warning "react-basics > react-spring > @react-spring/konva@9.7.2" has unmet peer dependency "react-konva@^16.8.0 || ^16.8.7-0 || ^16.9.0-0 || ^16.10.1-0 || ^16.12.0-0 || ^16.13.0-0 || ^17.0.0-0 || ^17.0.1-0 || ^17.0.2-0 || ^18.0.0-0".
warning "react-basics > react-spring > @react-spring/native@9.7.2" has unmet peer dependency "react-native@>=0.58".
warning "react-basics > react-spring > @react-spring/three@9.7.2" has unmet peer dependency "@react-three/fiber@>=6.0".
warning "react-basics > react-spring > @react-spring/three@9.7.2" has unmet peer dependency "three@>=0.126".
warning "react-basics > react-spring > @react-spring/zdog@9.7.2" has unmet peer dependency "react-zdog@>=1.0".
warning "react-basics > react-spring > @react-spring/zdog@9.7.2" has unmet peer dependency "zdog@>=1.0".
warning " > react-intl@5.24.7" has incorrect peer dependency "react@^16.3.0 || 17".
warning " > react-simple-maps@2.3.0" has incorrect peer dependency "react@^16.8.0 || 17.x".
warning " > react-simple-maps@2.3.0" has incorrect peer dependency "react-dom@^16.8.0 || 17.x".
warning " > react-simple-maps@2.3.0" has unmet peer dependency "prop-types@^15.7.2".
warning " > rollup-plugin-dts@5.3.0" has incorrect peer dependency "rollup@^3.0.0".
warning " > ts-node@10.9.1" has unmet peer dependency "@types/node@*".
warning Workspaces can only be enabled in private projects.
[4/4] Building fresh packages...
success Saved lockfile.
$ node -e "if (process.env.NODE_ENV !== 'production'){process.exit(1)} " || husky install
husky - Git hooks installed
Done in 148.21s.
$ sudo service umami restart
$ sudo service umami status
● umami.service - A simple, easy to use, self-hosted web analytics solution.
     Loaded: loaded (/etc/systemd/system/umami.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Wed 2023-08-09 20:46:52 AEST; 6min ago
       Docs: https://umami.is/docs/about
    Process: 2825758 ExecStart=/usr/bin/yarn start (code=exited, status=1/FAILURE)
   Main PID: 2825758 (code=exited, status=1/FAILURE)

Aug 09 20:46:52 server systemd[1]: umami.service: Scheduled restart job, restart counter is at 5.
Aug 09 20:46:52 server systemd[1]: Stopped A simple, easy to use, self-hosted web analytics solution..
Aug 09 20:46:52 server systemd[1]: umami.service: Start request repeated too quickly.
Aug 09 20:46:52 server systemd[1]: umami.service: Failed with result 'exit-code'.
Aug 09 20:46:52 server systemd[1]: Failed to start A simple, easy to use, self-hosted web analytics solution..
$ journalctl -u umami
Aug 09 20:41:53 server systemd[1]: Started A simple, easy to use, self-hosted web analytics solution..
Aug 09 20:41:53 server yarn[2824770]: yarn run v1.22.19
Aug 09 20:41:53 server yarn[2824770]: $ next start
Aug 09 20:41:53 server yarn[2824792]: ready - started server on 0.0.0.0:3000, url: http://localhost:3000
Aug 09 20:41:53 server yarn[2824792]: info  - Loaded env from /home/umami/umami/.env
Aug 09 20:41:54 server yarn[2824792]: Error: Cannot find module '/home/umami/umami/.next/server/next-font-manifest.json'
Aug 09 20:41:54 server yarn[2824792]: Require stack:
Aug 09 20:41:54 server yarn[2824792]: - /home/umami/umami/node_modules/next/dist/server/next-server.js
Aug 09 20:41:54 server yarn[2824792]: - /home/umami/umami/node_modules/next/dist/server/next.js
Aug 09 20:41:54 server yarn[2824792]: - /home/umami/umami/node_modules/next/dist/server/lib/start-server.js
Aug 09 20:41:54 server yarn[2824792]: - /home/umami/umami/node_modules/next/dist/cli/next-start.js
Aug 09 20:41:54 server yarn[2824792]: - /home/umami/umami/node_modules/next/dist/lib/commands.js
Aug 09 20:41:54 server yarn[2824792]: - /home/umami/umami/node_modules/next/dist/bin/next
Aug 09 20:41:54 server yarn[2824792]:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1026:15)
Aug 09 20:41:54 server yarn[2824792]:     at Function.mod._resolveFilename (/home/umami/umami/node_modules/next/dist/build/webpack/require-hook.js:23:32)
Aug 09 20:41:54 server yarn[2824792]:     at Function.Module._load (node:internal/modules/cjs/loader:871:27)
Aug 09 20:41:54 server yarn[2824792]:     at Module.require (node:internal/modules/cjs/loader:1098:19)
Aug 09 20:41:54 server yarn[2824792]:     at require (node:internal/modules/cjs/helpers:108:18)
Aug 09 20:41:54 server yarn[2824792]:     at NextNodeServer.getNextFontManifest (/home/umami/umami/node_modules/next/dist/server/next-server.js:644:16)
Aug 09 20:41:54 server yarn[2824792]:     at new Server (/home/umami/umami/node_modules/next/dist/server/base-server.js:74:38)
Aug 09 20:41:54 server yarn[2824792]:     at new NextNodeServer (/home/umami/umami/node_modules/next/dist/server/next-server.js:70:9)
Aug 09 20:41:54 server yarn[2824792]:     at NextServer.createServer (/home/umami/umami/node_modules/next/dist/server/next.js:147:16)
Aug 09 20:41:54 server yarn[2824792]:     at async /home/umami/umami/node_modules/next/dist/server/next.js:159:31 {
Aug 09 20:41:54 server yarn[2824792]:   code: 'MODULE_NOT_FOUND',
Aug 09 20:41:54 server yarn[2824792]:   requireStack: [
Aug 09 20:41:54 server yarn[2824792]:     '/home/umami/umami/node_modules/next/dist/server/next-server.js',
Aug 09 20:41:54 server yarn[2824792]:     '/home/umami/umami/node_modules/next/dist/server/next.js',
Aug 09 20:41:54 server yarn[2824792]:     '/home/umami/umami/node_modules/next/dist/server/lib/start-server.js',
Aug 09 20:41:54 server yarn[2824792]:     '/home/umami/umami/node_modules/next/dist/cli/next-start.js',
Aug 09 20:41:54 server yarn[2824792]:     '/home/umami/umami/node_modules/next/dist/lib/commands.js',
Aug 09 20:41:54 server yarn[2824792]:     '/home/umami/umami/node_modules/next/dist/bin/next'
Aug 09 20:41:54 server yarn[2824792]:   ]
Aug 09 20:41:54 server yarn[2824792]: }
Aug 09 20:41:54 server yarn[2824770]: error Command failed with exit code 1.
Aug 09 20:41:54 server yarn[2824770]: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Aug 09 20:41:54 server systemd[1]: umami.service: Main process exited, code=exited, status=1/FAILURE
Aug 09 20:41:54 server systemd[1]: umami.service: Failed with result 'exit-code'.
Aug 09 20:41:54 server systemd[1]: umami.service: Scheduled restart job, restart counter is at 1.
Aug 09 20:41:54 server systemd[1]: Stopped A simple, easy to use, self-hosted web analytics solution..
```

Alas some issue has arisen.

**Comment by bernd-wechner** [comment]
And I can now confirm that yarn install and yarn build worked after finally a successful migration. Details are all in https://github.com/umami-software/umami/issues/2194

But I suspect this issue can close now too. As the shift to using yard was clean and simple once the migration issue was resolved. In a nutshell it is because the migration attempts to install a postgres extension and this fails if you are running umami under specific umami user accounts that are not postgres admins (as in fact you should be!)
