### ISSUE TITLE
Application error: a client-side exception has occurred (see the browser console for more information).

### ISSUE THREAD

**Issue by Jonnyan404** [umami-software/umami#1971]
```html
content.js:34 updateSettings ObjectCT_AREA: "Ctrl+2"CT_BATCH: "Ctrl+1"CT_DIRECT: "Opt"CT_SCROLL: "Ctrl+4"CT_VISIBLE: "Ctrl+3"dropType: 0format: "png"[[Prototype]]: Object
framework-2c79e2a64abdb08b.js:9 Error: [@formatjs/intl] An `id` must be provided to format a message. You can either:
1. Configure your build toolchain with [babel-plugin-formatjs](https://formatjs.io/docs/tooling/babel-plugin)
or [@formatjs/ts-transformer](https://formatjs.io/docs/tooling/ts-transformer) OR
2. Configure your `eslint` config to include [eslint-plugin-formatjs](https://formatjs.io/docs/tooling/linter#enforce-id)
to autofix this issue
    at r (_app-d6ee3011e5e51a59.js:1:150)
    at m (_app-d6ee3011e5e51a59.js:6:526273)
    at V (_app-d6ee3011e5e51a59.js:6:535294)
    at K ([id]-32069d218b3806e2.js:1:7230)
    at ab (framework-2c79e2a64abdb08b.js:9:60915)
    at ud (framework-2c79e2a64abdb08b.js:9:72801)
    at i (framework-2c79e2a64abdb08b.js:9:120370)
    at oO (framework-2c79e2a64abdb08b.js:9:99112)
    at framework-2c79e2a64abdb08b.js:9:98979
    at oF (framework-2c79e2a64abdb08b.js:9:98986)
a6 @ framework-2c79e2a64abdb08b.js:9
main-312c3af8736f482a.js:1 Error: [@formatjs/intl] An `id` must be provided to format a message. You can either:
1. Configure your build toolchain with [babel-plugin-formatjs](https://formatjs.io/docs/tooling/babel-plugin)
or [@formatjs/ts-transformer](https://formatjs.io/docs/tooling/ts-transformer) OR
2. Configure your `eslint` config to include [eslint-plugin-formatjs](https://formatjs.io/docs/tooling/linter#enforce-id)
to autofix this issue
    at r (_app-d6ee3011e5e51a59.js:1:150)
    at m (_app-d6ee3011e5e51a59.js:6:526273)
    at V (_app-d6ee3011e5e51a59.js:6:535294)
    at K ([id]-32069d218b3806e2.js:1:7230)
    at ab (framework-2c79e2a64abdb08b.js:9:60915)
    at ud (framework-2c79e2a64abdb08b.js:9:72801)
    at i (framework-2c79e2a64abdb08b.js:9:120370)
    at oO (framework-2c79e2a64abdb08b.js:9:99112)
    at framework-2c79e2a64abdb08b.js:9:98979
    at oF (framework-2c79e2a64abdb08b.js:9:98986)
K @ main-312c3af8736f482a.js:1
main-312c3af8736f482a.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
K @ main-312c3af8736f482a.js:1

```

The main interface can't be opened now.

**Comment by Jonnyan404** [comment]
After the upgrade, it can be accessed now.
