### ISSUE TITLE
various failures when upgrading to v2 with docker-compose setup

### ISSUE THREAD

**Issue by kiprasmel** [umami-software/umami#1999]
started @ v1.40.0, tried simply `npx @umami/migrate-v1-v2` in exec'ed docker container.
got error similar to [1], where the 2nd migration wasn't detected as applied, even tho in my db backup i see that i had all 4 of them done.

[1] https://github.com/umami-software/umami/issues/1887#issuecomment-1521286749

so this didn't work. i couldn't figure out a fix, so nuked the whole db - by removing local docker volume for it (`docker-compose down -v`), & starting over at v1.40.0.

had db backup (via `pg_dumpall`), but didn't know how to apply.
eventually figured out that migrations run on app start, so i intentionally provided a wrong db connection url to app so that migrations won't run.
also, instead of pointing the default schema to db (`./sql/schema.postgresql.sql`), pointed to my db backup file (which is sql statements as well), so that db will restore from it in first launch, instead of creating an empty db.

almost worked, had to remove 2 lines from the db backup file:
- CREATE ROLE umami;
- CREATE DATABASE umami WITH TEMPLATE = template0 ENCODING = 'UTF8' LC_COLLATE = 'en_US.utf8' LC_CTYPE = 'en_US.utf8'

...because would error out that already exist.

then finally worked, db got restored. after changing to correct password for the umami role, i was back successfully at v1.40.0,
everything worked, was able to both view UI & umami was able to store new data.

---

so then, the 2nd attempt to upgrade to v2:

looked thru the `migrate-v1-v2 script`, noticed ppl are doing some manual `cp`-ying,
noticed that since v0.9.0 [2], the script no longer calls `copyDbFiles` and `prismaGenerate` functions
if called thru `npx` (because no `yarn install` and `yarn build` gets run if running script thru npx).

[2] https://github.com/umami-software/migrate-v1-v2/commit/f242512ff290c6a48a48aedb1b25acae5afc8b6d

i didn't know if this is causing any problems or is irrelevant.
nonetheless, i wanted to try - maybe migration would work if i'd run locally so that the 2 function would get called.
so tried following example:
https://github.com/umami-software/umami/issues/1887#issuecomment-1512915162

but didn't exactly work since `apt` wasn't even available inside the docker container,
so instead i cloned the script locally & mounted w/ volume, similar to:
https://github.com/umami-software/umami/issues/1887#issuecomment-1514127361

and performed the needed steps:
```
docker exec -it umami_umami_1
cd /app/migrate-v1-v2/
yarn install
chmod 777 -R . # was needed! exactly after install/before build, wouldn't work otherwise
yarn build
yarn start
```

and just like previous time, migration printed as successful.

logs:

1. in umami_umami_1, the latest run of the migration-v1-v2 script:

```
/app/migrate-v1-v2
# yarn start
yarn run v1.22.19
$ node index.js
Running v0.15.0
✓ DATABASE_URL is defined.
✓ Database connection successful.
Preparing v1 tables for migration
✓ Dropped v1 database keys.
✓ Dropped v1 database indexes.
✓ Renamed v1 database tables.
✓ Database v1 tables ready for migration.
Database v2 tables not found.
Adding v2 tables...
✓ Ran sql file /db/postgresql/migrations/01_init/migration.sql.
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "umami", schema "public" at "db:5432"
Migration 01_init marked as applied.

✓ Database is ready for migration.
✓ Starting v2 data migration. Please do no cancel this process, it may take a while.
✓ Ran sql file /db/postgresql/data-migration-v2.sql.
✓ Data migration from v1 to v2 tables completed.
✔ Do you want to delete v1 database tables? (Y/N) … n
✓ Migration successfully completed.
Done in 13.80s.
```

2. `docker logs umami_db_1`:

```
2023-04-26 01:24:01.744 UTC [1] LOG:  starting PostgreSQL 12.14 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r4) 12.2.1 20220924, 64-bit
2023-04-26 01:24:01.745 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2023-04-26 01:24:01.745 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2023-04-26 01:24:01.749 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2023-04-26 01:24:01.805 UTC [21] LOG:  database system was shut down at 2023-04-26 01:23:59 UTC
2023-04-26 01:24:01.814 UTC [1] LOG:  database system is ready to accept connections
2023-04-26 01:24:06.936 UTC [30] LOG:  could not receive data from client: Connection reset by peer
2023-04-26 01:28:01.833 UTC [47] ERROR:  relation "website_event" does not exist at character 15
2023-04-26 01:28:01.833 UTC [47] STATEMENT:  select * from website_event limit 1
2023-04-26 01:28:05.944 UTC [49] LOG:  could not receive data from client: Connection reset by peer
2023-04-26 01:28:06.319 UTC [50] ERROR:  relation "_prisma_migrations" does not exist at character 126
2023-04-26 01:28:06.319 UTC [50] STATEMENT:  SELECT "id", "checksum", "finished_at", "migration_name", "logs", "rolled_back_at", "started_at", "applied_steps_count" FROM "_prisma_migrations" ORDER BY "started_at" ASC
2023-04-26 01:28:30.226 UTC [33] ERROR:  relation "pageview" does not exist at character 46
2023-04-26 01:28:30.226 UTC [33] STATEMENT:  select count(distinct session_id) x
	    from pageview
	      join website
	        on pageview.website_id = website.website_id
	    where website.website_uuid = $1::uuid
	    and pageview.created_at >= $2
```

3. `docker logs umami_umami_1`:

```
Raw query failed. Code: `42P01`. Message: `relation "pageview" does not exist`
    at RequestHandler.handleRequestError (/app/node_modules/@prisma/client/runtime/index.js:31941:13)
    at RequestHandler.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/index.js:31913:12)
    at RequestHandler.request (/app/node_modules/@prisma/client/runtime/index.js:31908:12)
    at async Proxy._request (/app/node_modules/@prisma/client/runtime/index.js:32994:16)
    at async __WEBPACK_DEFAULT_EXPORT__ (/app/.next/server/pages/api/websites/[id]/active.js:156:24)
    at async Object.apiResolver (/app/node_modules/next/dist/server/api-utils/node.js:366:9)
    at async NextNodeServer.runApi (/app/node_modules/next/dist/server/next-server.js:481:9)
    at async Object.fn (/app/node_modules/next/dist/server/next-server.js:735:37)
    at async Router.execute (/app/node_modules/next/dist/server/router.js:247:36)
    at async NextNodeServer.run (/app/node_modules/next/dist/server/base-server.js:347:29) {
  code: 'P2010',
  clientVersion: '4.9.0',
  meta: { code: '42P01', message: 'relation "pageview" does not exist' },
  batchRequestIdx: undefined
}
PrismaClientKnownRequestError:
Invalid `prisma.$queryRaw()` invocation:
```

end logs

---

but as you see, db now had different errors.
so performed a switch in umami's git repo from v1.40.0 to master:

```
docker-compose down

git checkout master

# switch to proper sql schema instead of db backup.
# fix db connection url for the application.

# switch to *latest* image of umami instead of v1.40.0
docker-compose pull
docker-compose up -d
```

app started fine, though db had 1 new error:

4. `docker logs umami_db_1`:

```
PostgreSQL Database directory appears to contain a database; Skipping initialization

2023-04-26 01:38:41.660 UTC [1] LOG:  starting PostgreSQL 12.14 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r4) 12.2.1 20220924, 64-bit
2023-04-26 01:38:41.660 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2023-04-26 01:38:41.660 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2023-04-26 01:38:41.662 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2023-04-26 01:38:41.687 UTC [21] LOG:  database system was shut down at 2023-04-26 01:34:56 UTC
2023-04-26 01:38:41.692 UTC [1] LOG:  database system is ready to accept connections
2023-04-26 01:38:44.778 UTC [30] ERROR:  relation "account" does not exist at character 15
2023-04-26 01:38:44.778 UTC [30] STATEMENT:  select * from account limit 1
2023-04-26 01:38:46.308 UTC [31] LOG:  could not receive data from client: Connection reset by peer
```

nonetheless, opened app, finally the UI worked!

sadly, when visiting any site i have which uses umami,
db now prints a completely new error, and umami is unable to record any new data into db.

5. `docker logs umami_umami_1`

```
Inconsistent column data: Error creating UUID, invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-zA-Z], found `u` at 1
    at pn.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:176:6477)
    at pn.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:176:5907)
    at pn.request (/app/node_modules/@prisma/client/runtime/library.js:176:5786)
    at async t._request (/app/node_modules/@prisma/client/runtime/library.js:179:10484)
    at async __WEBPACK_DEFAULT_EXPORT__ (/app/.next/server/pages/api/websites/[id].js:154:25)
    at async Object.apiResolver (/app/node_modules/next/dist/server/api-utils/node.js:372:9)
    at async NextNodeServer.runApi (/app/node_modules/next/dist/server/next-server.js:514:9)
    at async Object.fn (/app/node_modules/next/dist/server/next-server.js:828:35)
    at async Router.execute (/app/node_modules/next/dist/server/router.js:243:32)
    at async NextNodeServer.runImpl (/app/node_modules/next/dist/server/base-server.js:432:29) {
  code: 'P2023',
  clientVersion: '4.13.0',
  meta: {
    message: 'Error creating UUID, invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-zA-Z], found `u` at 1'
  }
}
PrismaClientKnownRequestError:
Invalid `prisma.website.findUnique()` invocation:
```

so up to this point, i was able to brute-force thru problems,
but now am stuck & would appreciate your help..

**Comment by kiprasmel** [comment]
update:
~12hours have passed, and now the umami application is broken as well:

```
Application error: a client-side exception has occurred (see the browser console for more information).
```

---

fwiw, there isn't that much data, i only had 2 websites w/ only pageviews, no events,
data is not sensitive either so could give some access if helps to debug..

thanks.

**Comment by franciscao633** [comment]
Looks like you successfully migrated, but that urn error is completely unrelated since its happening on a fresh install too #1964. Will troubleshoot today. We had a bunch of failed iterations where users had to do workarounds, but the docs should be best going forward.

**Comment by kiprasmel** [comment]
hey @franciscao633 , any updates on this? 🙏

**Comment by franciscao633** [comment]
Sorry, I've been looking into this when I can. It looks like the app is passing undefined in the website ID somewhere in the app. Will try to get this resolved as soon as I can.

**Comment by ammar-madni** [comment]
> Sorry, I've been looking into this when I can. It looks like the app is passing undefined in the website ID somewhere in the app. Will try to get this resolved as soon as I can.

Correct, I believe the `websiteId` is `undefined` initially when the component renders. I fixed this by using a ternary operator in the [`pages/realtime/[id]/index.js`](https://github.com/umami-software/umami/blob/master/pages/realtime/%5Bid%5D/index.js#LL13C56-L13C56) page before querying with the webstieId to make sure we only query if `websiteId` is truthy. So now my `pages/realtime/[id]/index.js` file looks like this:

```
import { useRouter } from 'next/router';
import AppLayout from 'components/layout/AppLayout';
import RealtimeDashboard from 'components/pages/realtime/RealtimeDashboard';
import useMessages from 'hooks/useMessages';
import useApi from 'hooks/useApi';

export default function RealtimeDetailsPage() {
  const router = useRouter();
  const { id: websiteId } = router.query;
  const { formatMessage, labels } = useMessages();
  const { get, useQuery } = useApi();
  const { data: website } = useQuery(['websites', websiteId], () =>
    websiteId ? get(`/websites/${websiteId}`, { enabled: !!websiteId }) : null,
  );
  const title = `${formatMessage(labels.realtime)}${website?.name ? ` - ${website.name}` : ''}`;

  if (!websiteId) {
    return null;
  }

  return (
    <AppLayout title={title}>
      <RealtimeDashboard key={websiteId} websiteId={websiteId} />
    </AppLayout>
  );
}
```

If like me you still have no data for all your sites, it is possibly because you have not updated the analytics script. It is mentioned in the upgrade guide but not very clearly imo (would be nice if this was updated to make it something actionable i.e all sites need their analytics script updated). Once I updated the scripts on all my sites and cleared my caches (cloudflare, nginx) everything started working again.

Little sad I lost 4 days worth of data. Hope that helps someone else

**Comment by kiprasmel** [comment]
wait, you need to update the umami script in websites that use it? 🤦 
yeah that's not clear at all.

cc @mikecao you guys really need to make this obvious in the migration docs.. https://umami.is/docs/migrate-v1-v2
.. or keep both `script.js` and `umami.js` for backwards compat..

---

i can't really do that anyway since the app is broken.. let's see if your patch helps..

i changed the file, did docker-compose down & docker-compose up -d, then cleared cache & re-logged in.
dashboard now seems to work! 🚀

---

then, i updated umami script in my website, and now data is collecting successfully as well! 🚀

tysm @ammar-madni 🤝

**Comment by kiprasmel** [comment]
though, the dashboard error has come back after refreshing the page, there's something more to fix..

**Comment by kiprasmel** [comment]
@franciscao633 correct, i implemented the fix.

then, after clearing cache & re-logging in, the application works fine.
it breaks & the error comes back if i refresh the page.

**Comment by ammar-madni** [comment]
@franciscao633 Not sure if that question was directed at me but I've only noticed it on the realtime page.

**Comment by kiprasmel** [comment]
@franciscao633 the error occurs anywhere on the page, mostly the default /dashboard. I don't really use realtime since i don't have many active users 😅
