### ISSUE TITLE
Version 2, script.js error when clicking on document

### ISSUE THREAD

**Issue by skipperbent** [umami-software/umami#2000]
Great work with the project. I found this bug when clicking somewhere on the document/page with no parent element. I couldn't see it on the issues list, but sorry for double posting if you're already aware.

**Console output:**
```js
caught TypeError: Cannot read properties of null (reading 'tagName')
    at script.js:1:2071
    at HTMLDocument.<anonymous> (script.js:1:2118)
(anonymous) @ script.js:1
(anonymous) @ script.js:1
```

**script.js**

```js
if ("A" === n.tagName)
```

**Comment by miroslavpejic85** [comment]
I had the same issue, but it was fixed in the latest release `v2.2.0`

**Comment by skipperbent** [comment]
> I had the same issue, but it was fixed in the latest release `v2.2.0`

Thanks for the heads up. I wasn't aware that a 2.2.0 was already released. I think i'm on 2.1.0 - but im not entirely sure. Will reopen if the problem is still there. Thanks again
