### ISSUE TITLE
Upgrade (to latest Master - 2.2.0) failed to install (ERESOLVE unable to resolve dependency tree)

### ISSUE THREAD

**Issue by bernd-wechner** [umami-software/umami#2012]
### Describe the Bug

Probably simple to fix, but beyond my immediate skill set so I'll need to drill down and research a little. Before I start, filing the issue just in case expertise out there can point me right quickly.  I'm guessing up front a node or npm upgrade is needed.

### Database

PostgreSQL

### Relevant log output

```shell
$ cat /home/umami/.npm/_logs/2023-04-29T08_43_36_404Z-debug-0.log
0 verbose cli /usr/bin/node /usr/bin/npm
1 info using npm@8.19.3
2 info using node@v16.19.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 4ms
5 timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 3ms
7 timing config:load:cli Completed in 4ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:/home/umami/umami/.npmrc Completed in 0ms
10 timing config:load:project Completed in 5ms
11 timing config:load:file:/home/umami/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/usr/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 1ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 21ms
19 timing npm:load:configload Completed in 22ms
20 timing npm:load:mkdirpcache Completed in 1ms
21 timing npm:load:mkdirplogs Completed in 1ms
22 verbose title npm install
23 verbose argv "install"
24 timing npm:load:setTitle Completed in 1ms
25 timing config:load:flatten Completed in 5ms
26 timing npm:load:display Completed in 7ms
27 verbose logfile logs-max:10 dir:/home/umami/.npm/_logs
28 verbose logfile /home/umami/.npm/_logs/2023-04-29T08_43_36_404Z-debug-0.log
29 timing npm:load:logFile Completed in 8ms
30 timing npm:load:timers Completed in 0ms
31 timing npm:load:configScope Completed in 0ms
32 timing npm:load Completed in 41ms
33 timing arborist:ctor Completed in 1ms
34 silly logfile start cleaning logs, removing 1 files
35 silly logfile done cleaning log files
36 timing idealTree:init Completed in 1543ms
37 timing idealTree:userRequests Completed in 0ms
38 silly idealTree buildDeps
39 silly fetch manifest @fontsource/inter@^4.5.15
40 http fetch GET 200 https://registry.npmjs.org/npm 4159ms (cache updated)
41 http fetch GET 200 https://registry.npmjs.org/@fontsource%2finter 3860ms (cache updated)
42 silly fetch manifest @prisma/client@4.13.0
43 http fetch GET 200 https://registry.npmjs.org/@prisma%2fclient 4017ms (cache updated)
44 silly fetch manifest prisma@4.13.0
45 http fetch GET 200 https://registry.npmjs.org/prisma 1998ms (cache updated)
46 silly fetch manifest @tanstack/react-query@^4.16.1
47 http fetch GET 200 https://registry.npmjs.org/@tanstack%2freact-query 500ms (cache miss)
48 silly fetch manifest react@^18.2.0
49 http fetch GET 200 https://registry.npmjs.org/react 351ms (cache updated)
50 silly fetch manifest react-dom@^18.2.0
51 http fetch GET 200 https://registry.npmjs.org/react-dom 335ms (cache updated)
52 silly fetch manifest react-native@*
53 http fetch GET 200 https://registry.npmjs.org/react-native 694ms (cache updated)
54 silly fetch manifest @umami/prisma-client@^0.2.0
55 http fetch GET 200 https://registry.npmjs.org/@umami%2fprisma-client 2086ms (cache miss)
56 silly fetch manifest @umami/redis-client@^0.2.0
57 http fetch GET 200 https://registry.npmjs.org/@umami%2fredis-client 2094ms (cache miss)
58 silly fetch manifest chart.js@^4.2.1
59 http fetch GET 200 https://registry.npmjs.org/chart.js 887ms (cache updated)
60 silly fetch manifest chartjs-adapter-date-fns@^3.0.0
61 http fetch GET 200 https://registry.npmjs.org/chartjs-adapter-date-fns 814ms (cache miss)
62 silly fetch manifest date-fns@^2.23.0
63 http fetch GET 200 https://registry.npmjs.org/date-fns 298ms (cache updated)
64 silly fetch manifest clickhouse@^2.5.0
65 http fetch GET 200 https://registry.npmjs.org/clickhouse 905ms (cache revalidated)
66 silly fetch manifest cross-spawn@^7.0.3
67 http fetch GET 200 https://registry.npmjs.org/cross-spawn 48ms (cache revalidated)
68 silly fetch manifest dateformat@^5.0.3
69 http fetch GET 200 https://registry.npmjs.org/dateformat 70ms (cache revalidated)
70 silly fetch manifest kafkajs@^2.1.0
71 http fetch GET 200 https://registry.npmjs.org/kafkajs 946ms (cache updated)
72 silly fetch manifest moment-timezone@^0.5.35
73 http fetch GET 200 https://registry.npmjs.org/moment-timezone 69ms (cache updated)
74 silly fetch manifest next@13.2.4
75 http fetch GET 200 https://registry.npmjs.org/next 1653ms (cache updated)
76 silly fetch manifest @opentelemetry/api@^1.4.0
77 http fetch GET 200 https://registry.npmjs.org/@opentelemetry%2fapi 315ms (cache miss)
78 silly fetch manifest fibers@>= 3.1.0
79 http fetch GET 200 https://registry.npmjs.org/fibers 57ms (cache revalidated)
80 silly fetch manifest node-sass@^6.0.0 || ^7.0.0
81 http fetch GET 200 https://registry.npmjs.org/node-sass 59ms (cache updated)
82 silly fetch manifest sass@^1.3.0
83 http fetch GET 200 https://registry.npmjs.org/sass 102ms (cache updated)
84 silly fetch manifest next-basics@^0.27.0
85 http fetch GET 200 https://registry.npmjs.org/next-basics 1243ms (cache updated)
86 silly fetch manifest next@^12.3.2
87 timing idealTree Completed in 25673ms
88 timing command:install Completed in 25704ms
89 notice
89 notice New major version of npm available! 8.19.3 -> 9.6.5
89 notice Changelog: https://github.com/npm/cli/releases/tag/v9.6.5
89 notice Run npm install -g npm@9.6.5 to update!
89 notice
90 verbose stack Error: unable to resolve dependency tree
90 verbose stack     at Arborist.[failPeerConflict] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1381:25)
90 verbose stack     at Arborist.[loadPeerSet] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1347:34)
90 verbose stack     at async Arborist.[buildDepStep] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:930:11)
90 verbose stack     at async Arborist.buildIdealTree (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:211:7)
90 verbose stack     at async Promise.all (index 1)
90 verbose stack     at async Arborist.reify (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:154:5)
90 verbose stack     at async Install.exec (/usr/lib/node_modules/npm/lib/commands/install.js:145:5)
90 verbose stack     at async module.exports (/usr/lib/node_modules/npm/lib/cli.js:78:5)
91 verbose cwd /home/umami/umami
92 verbose Linux 5.4.0-139-generic
93 verbose node v16.19.0
94 verbose npm  v8.19.3
95 error code ERESOLVE
96 error ERESOLVE unable to resolve dependency tree
97 error
98 error While resolving: umami@2.2.0
98 error Found: next@13.2.4
98 error node_modules/next
98 error   next@"13.2.4" from the root project
98 error
98 error Could not resolve dependency:
98 error peer next@"^12.3.2" from next-basics@0.27.0
98 error node_modules/next-basics
98 error   next-basics@"^0.27.0" from the root project
98 error
98 error Fix the upstream dependency conflict, or retry
98 error this command with --force, or --legacy-peer-deps
98 error to accept an incorrect (and potentially broken) dependency resolution.
98 error
98 error See /home/umami/.npm/eresolve-report.txt for a full report.
99 verbose exit 1
100 timing npm Completed in 25942ms
101 verbose unfinished npm timer reify 1682757816635
102 verbose unfinished npm timer reify:loadTrees 1682757816660
103 verbose unfinished npm timer idealTree:buildDeps 1682757818206
104 verbose unfinished npm timer idealTree:#root 1682757818207
105 verbose code 1
106 error A complete log of this run can be found in:
106 error     /home/umami/.npm/_logs/2023-04-29T08_43_36_404Z-debug-0.l
```

### Which browser are you using? (if relevant)

Matters not

### How are you deploying your application? (if relevant)

git pull, npm install

**Comment by bernd-wechner** [comment]
Of possible interest:

```
$ sudo -u umami npm audit
# npm audit report

d3-color  <3.1.0
Severity: high
d3-color vulnerable to ReDoS - https://github.com/advisories/GHSA-36jr-mh4h-2g58
fix available via `npm audit fix --force`
Will install react-simple-maps@1.0.0, which is a breaking change
node_modules/d3-color
  d3-interpolate  0.1.3 - 2.0.1
  Depends on vulnerable versions of d3-color
  node_modules/d3-interpolate
    d3-transition  0.0.7 - 2.0.0
    Depends on vulnerable versions of d3-color
    Depends on vulnerable versions of d3-interpolate
    node_modules/d3-transition
    d3-zoom  0.0.2 - 2.0.0
    Depends on vulnerable versions of d3-interpolate
    Depends on vulnerable versions of d3-transition
    node_modules/d3-zoom
      react-simple-maps  >=2.0.0
      Depends on vulnerable versions of d3-zoom
      node_modules/react-simple-maps

request  *
Severity: moderate
Server-Side Request Forgery in Request - https://github.com/advisories/GHSA-p8p7-x288-28g6
No fix available
node_modules/request
  clickhouse  *
  Depends on vulnerable versions of request
  node_modules/clickhouse

7 vulnerabilities (2 moderate, 5 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
```

**Comment by bernd-wechner** [comment]
Which I ran because I tried a force:

```
$ sudo -u umami npm install --force
npm WARN using --force Recommended protections disabled.
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: umami@2.2.0
npm WARN Found: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@"^18.2.0" from next@13.2.4
npm WARN   node_modules/next
npm WARN     next@"13.2.4" from the root project
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"17.0.2" from react-dom@17.0.2
npm WARN node_modules/react-dom
npm WARN   peer react-dom@"^18.2.0" from next@13.2.4
npm WARN   node_modules/next
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: umami@2.2.0
npm WARN Found: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@"^18.2.0" from next@13.2.4
npm WARN   node_modules/next
npm WARN     next@"13.2.4" from the root project
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"17.0.2" from react-dom@17.0.2
npm WARN node_modules/react-dom
npm WARN   peer react-dom@"^18.2.0" from next@13.2.4
npm WARN   node_modules/next
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: umami@2.2.0
npm WARN Found: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@"^18.2.0" from next@13.2.4
npm WARN   node_modules/next
npm WARN     next@"13.2.4" from the root project
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"17.0.2" from react-dom@17.0.2
npm WARN node_modules/react-dom
npm WARN   peer react-dom@"^18.2.0" from next@13.2.4
npm WARN   node_modules/next
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: umami@2.2.0
npm WARN Found: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@"^18.2.0" from next@13.2.4
npm WARN   node_modules/next
npm WARN     next@"13.2.4" from the root project
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"17.0.2" from react-dom@17.0.2
npm WARN node_modules/react-dom
npm WARN   peer react-dom@"^18.2.0" from next@13.2.4
npm WARN   node_modules/next
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: umami@2.2.0
npm WARN Found: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@"^18.2.0" from next@13.2.4
npm WARN   node_modules/next
npm WARN     next@"13.2.4" from the root project
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.3.0 || 17" from react-intl@5.24.7
npm WARN node_modules/react-intl
npm WARN   react-intl@"^5.24.7" from the root project
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: umami@2.2.0
npm WARN Found: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@"^18.2.0" from next@13.2.4
npm WARN   node_modules/next
npm WARN     next@"13.2.4" from the root project
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.8.0 || 17.x" from react-simple-maps@2.3.0
npm WARN node_modules/react-simple-maps
npm WARN   react-simple-maps@"^2.3.0" from the root project
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: umami@2.2.0
npm WARN Found: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@"^18.2.0" from next@13.2.4
npm WARN   node_modules/next
npm WARN     next@"13.2.4" from the root project
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^15.0.0 || ^16.0.0 || ^17.0.0" from react-window@1.8.6
npm WARN node_modules/react-window
npm WARN   react-window@"^1.8.6" from the root project
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: umami@2.2.0
npm WARN Found: react-dom@17.0.2
npm WARN node_modules/react-dom
npm WARN   peer react-dom@"^18.2.0" from next@13.2.4
npm WARN   node_modules/next
npm WARN     next@"13.2.4" from the root project
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react-dom@"^16.8.0 || 17.x" from react-simple-maps@2.3.0
npm WARN node_modules/react-simple-maps
npm WARN   react-simple-maps@"^2.3.0" from the root project
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: umami@2.2.0
npm WARN Found: react-dom@17.0.2
npm WARN node_modules/react-dom
npm WARN   peer react-dom@"^18.2.0" from next@13.2.4
npm WARN   node_modules/next
npm WARN     next@"13.2.4" from the root project
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react-dom@"^15.0.0 || ^16.0.0 || ^17.0.0" from react-window@1.8.6
npm WARN node_modules/react-window
npm WARN   react-window@"^1.8.6" from the root project
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: next-basics@0.27.0
npm WARN Found: next@13.2.4
npm WARN node_modules/next
npm WARN   next@"13.2.4" from the root project
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer next@"^12.3.2" from next-basics@0.27.0
npm WARN node_modules/next-basics
npm WARN   next-basics@"^0.27.0" from the root project
npm WARN 
npm WARN Conflicting peer dependency: next@12.3.4
npm WARN node_modules/next
npm WARN   peer next@"^12.3.2" from next-basics@0.27.0
npm WARN   node_modules/next-basics
npm WARN     next-basics@"^0.27.0" from the root project
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: rollup-plugin-dts@5.3.0
npm WARN Found: rollup@2.79.1
npm WARN node_modules/rollup
npm WARN   dev rollup@"^2.70.1" from the root project
npm WARN   14 more (@rollup/plugin-buble, @rollup/pluginutils, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer rollup@"^3.0.0" from rollup-plugin-dts@5.3.0
npm WARN node_modules/rollup-plugin-dts
npm WARN   dev rollup-plugin-dts@"^5.3.0" from the root project
npm WARN 
npm WARN Conflicting peer dependency: rollup@3.21.1
npm WARN node_modules/rollup
npm WARN   peer rollup@"^3.0.0" from rollup-plugin-dts@5.3.0
npm WARN   node_modules/rollup-plugin-dts
npm WARN     dev rollup-plugin-dts@"^5.3.0" from the root project
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated uglify-es@3.3.9: support for ECMAScript is superseded by `uglify-js` as of v3.13.0
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated

> umami@2.2.0 prepare
> node -e "if (process.env.NODE_ENV !== 'production'){process.exit(1)} " || husky install

husky - Git hooks installed

added 818 packages, removed 169 packages, changed 327 packages, and audited 1780 packages in 4m

264 packages are looking for funding
  run `npm fund` for details

7 vulnerabilities (2 moderate, 5 high)

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
```

**Comment by bernd-wechner** [comment]
I notice the latest installation docs use `yarn`. Not sure if that's the root of the issue, I am running off my own notes on how I've done upgrades in past ;-)

**Comment by franciscao633** [comment]
Might be same issue as #1902. Someone states `yarn install` worked, so worth a try.

**Comment by bernd-wechner** [comment]
A quick note that I moved to yarn and all this went away. Just for the record!
