### ISSUE TITLE
Critical fail deploy

### ISSUE THREAD

**Issue by miguelgargallo** [umami-software/umami#2017]
### Describe the Bug

I tried over 3 OS, and over 2 docker, docker-compose, private docker
On server fails, at home localhost ip works
Tried on both Databases

even the coolify fails

*I removed all data involved the log, so this is just for demonstration

### Database

PostgreSQL

### Relevant log output

```shell
2023-05-01T23:04:59.117934093Z Error: Could not find a production build in the '/app/.next' directory. Try building your app with 'next build' before starting the production server. https://nextjs.org/docs/messages/production-start-no-build-id

2023-05-01T23:04:59.118014405Z at NextNodeServer.getBuildId (/app/node_modules/next/dist/server/next-server.js:198:23)

2023-05-01T23:04:59.118019446Z at new Server (/app/node_modules/next/dist/server/base-server.js:68:29)

2023-05-01T23:04:59.118023236Z at new NextNodeServer (/app/node_modules/next/dist/server/next-server.js:70:9)

2023-05-01T23:04:59.118026836Z at NextServer.createServer (/app/node_modules/next/dist/server/next.js:147:16)

2023-05-01T23:04:59.118030586Z at async /app/node_modules/next/dist/server/next.js:159:31

2023-05-01T23:04:59.118033816Z at async NextServer.prepare (/app/node_modules/next/dist/server/next.js:134:24)

2023-05-01T23:04:59.118037516Z at async /app/node_modules/next/dist/cli/next-start.js:118:9

2023-05-01T23:04:59.141558075Z error Command failed with exit code 1.

2023-05-01T23:05:00.810090330Z Error: Could not find a production build in the '/app/.next' directory. Try building your app with 'next build' before starting the production server. https://nextjs.org/docs/messages/production-start-no-build-id

2023-05-01T23:05:00.810231175Z at NextNodeServer.getBuildId (/app/node_modules/next/dist/server/next-server.js:198:23)

2023-05-01T23:05:00.810235335Z at new Server (/app/node_modules/next/dist/server/base-server.js:68:29)

2023-05-01T23:05:00.810238695Z at new NextNodeServer (/app/node_modules/next/dist/server/next-server.js:70:9)

2023-05-01T23:05:00.810242645Z at NextServer.createServer (/app/node_modules/next/dist/server/next.js:147:16)

2023-05-01T23:05:00.810246445Z at async /app/node_modules/next/dist/server/next.js:159:31

2023-05-01T23:05:00.810250265Z at async NextServer.prepare (/app/node_modules/next/dist/server/next.js:134:24)

2023-05-01T23:05:00.810254135Z at async /app/node_modules/next/dist/cli/next-start.js:118:9

2023-05-01T23:05:00.831880536Z error Command failed with exit code 1.

2023-05-01T23:05:02.542155900Z Error: Could not find a production build in the '/app/.next' directory. Try building your app with 'next build' before starting the production server. https://nextjs.org/docs/messages/production-start-no-build-id

2023-05-01T23:05:02.542233922Z at NextNodeServer.getBuildId (/app/node_modules/next/dist/server/next-server.js:198:23)

2023-05-01T23:05:02.542240372Z at new Server (/app/node_modules/next/dist/server/base-server.js:68:29)

2023-05-01T23:05:02.542245162Z at new NextNodeServer (/app/node_modules/next/dist/server/next-server.js:70:9)

2023-05-01T23:05:02.542259803Z at NextServer.createServer (/app/node_modules/next/dist/server/next.js:147:16)

2023-05-01T23:05:02.542263413Z at async /app/node_modules/next/dist/server/next.js:159:31

2023-05-01T23:05:02.542267033Z at async NextServer.prepare (/app/node_modules/next/dist/server/next.js:134:24)

2023-05-01T23:05:02.542270723Z at async /app/node_modules/next/dist/cli/next-start.js:118:9

2023-05-01T23:05:02.576526039Z error Command failed with exit code 1.

2023-05-01T23:05:04.497251611Z Error: Could not find a production build in the '/app/.next' directory. Try building your app with 'next build' before starting the production server. https://nextjs.org/docs/messages/production-start-no-build-id

2023-05-01T23:05:04.497335123Z at NextNodeServer.getBuildId (/app/node_modules/next/dist/server/next-server.js:198:23)

2023-05-01T23:05:04.497341303Z at new Server (/app/node_modules/next/dist/server/base-server.js:68:29)

2023-05-01T23:05:04.497345214Z at new NextNodeServer (/app/node_modules/next/dist/server/next-server.js:70:9)

2023-05-01T23:05:04.497348844Z at NextServer.createServer (/app/node_modules/next/dist/server/next.js:147:16)

2023-05-01T23:05:04.497352724Z at async /app/node_modules/next/dist/server/next.js:159:31

2023-05-01T23:05:04.497356284Z at async NextServer.prepare (/app/node_modules/next/dist/server/next.js:134:24)

2023-05-01T23:05:04.497360044Z at async /app/node_modules/next/dist/cli/next-start.js:118:9

2023-05-01T23:05:04.520652576Z error Command failed with exit code 1.

2023-05-01T23:05:06.772427112Z Error: Could not find a production build in the '/app/.next' directory. Try building your app with 'next build' before starting the production server. https://nextjs.org/docs/messages/production-start-no-build-id

2023-05-01T23:05:06.772482994Z at NextNodeServer.getBuildId (/app/node_modules/next/dist/server/next-server.js:198:23)

2023-05-01T23:05:06.772503484Z at new Server (/app/node_modules/next/dist/server/base-server.js:68:29)

2023-05-01T23:05:06.772507364Z at new NextNodeServer (/app/node_modules/next/dist/server/next-server.js:70:9)

2023-05-01T23:05:06.772511064Z at NextServer.createServer (/app/node_modules/next/dist/server/next.js:147:16)

2023-05-01T23:05:06.772514615Z at async /app/node_modules/next/dist/server/next.js:159:31

2023-05-01T23:05:06.772518245Z at async NextServer.prepare (/app/node_modules/next/dist/server/next.js:134:24)

2023-05-01T23:05:06.772521815Z at async /app/node_modules/next/dist/cli/next-start.js:118:9

2023-05-01T23:05:06.788211234Z error Command failed with exit code 1.

2023-05-01T23:04:58.424737727Z yarn run v1.22.19

2023-05-01T23:04:58.484072901Z $ next start

2023-05-01T23:04:58.649394107Z ready - started server on 0.0.0.0:3000, url: http://localhost:3000

2023-05-01T23:04:59.144576337Z info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

2023-05-01T23:05:00.224232058Z yarn run v1.22.19

2023-05-01T23:05:00.292512776Z $ next start

2023-05-01T23:05:00.424615444Z ready - started server on 0.0.0.0:3000, url: http://localhost:3000

2023-05-01T23:05:00.832365872Z info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

2023-05-01T23:05:01.808654159Z yarn run v1.22.19

2023-05-01T23:05:01.946848973Z $ next start

2023-05-01T23:05:02.120551893Z ready - started server on 0.0.0.0:3000, url: http://localhost:3000

2023-05-01T23:05:02.576619502Z info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

2023-05-01T23:05:03.853646449Z yarn run v1.22.19

2023-05-01T23:05:03.934486701Z $ next start

2023-05-01T23:05:04.092317864Z ready - started server on 0.0.0.0:3000, url: http://localhost:3000

2023-05-01T23:05:04.520559064Z info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

2023-05-01T23:05:06.160526193Z yarn run v1.22.19

2023-05-01T23:05:06.227034346Z $ next start

2023-05-01T23:05:06.373994567Z ready - started server on 0.0.0.0:3000, url: http://localhost:3000

2023-05-01T23:05:06.788146642Z info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

2023-05-01T23:05:06.772427112Z Error: Could not find a production build in the '/app/.next' directory. Try building your app with 'next build' before starting the production server. https://nextjs.org/docs/messages/production-start-no-build-id

2023-05-01T23:05:06.772482994Z at NextNodeServer.getBuildId (/app/node_modules/next/dist/server/next-server.js:198:23)

2023-05-01T23:05:06.772503484Z at new Server (/app/node_modules/next/dist/server/base-server.js:68:29)

2023-05-01T23:05:06.772507364Z at new NextNodeServer (/app/node_modules/next/dist/server/next-server.js:70:9)

2023-05-01T23:05:06.772511064Z at NextServer.createServer (/app/node_modules/next/dist/server/next.js:147:16)

2023-05-01T23:05:06.772514615Z at async /app/node_modules/next/dist/server/next.js:159:31

2023-05-01T23:05:06.772518245Z at async NextServer.prepare (/app/node_modules/next/dist/server/next.js:134:24)

2023-05-01T23:05:06.772521815Z at async /app/node_modules/next/dist/cli/next-start.js:118:9

2023-05-01T23:05:06.788211234Z error Command failed with exit code 1.

2023-05-01T23:05:06.160526193Z yarn run v1.22.19

2023-05-01T23:05:06.227034346Z $ next start

2023-05-01T23:05:06.373994567Z ready - started server on 0.0.0.0:3000, url: http://localhost:3000

2023-05-01T23:05:09.609516349Z yarn run v1.22.19

2023-05-01T23:05:10.257940340Z Error: Could not find a production build in the '/app/.next' directory. Try building your app with 'next build' before starting the production server. https://nextjs.org/docs/messages/production-start-no-build-id

2023-05-01T23:05:10.257982441Z at NextNodeServer.getBuildId (/app/node_modules/next/dist/server/next-server.js:198:23)

2023-05-01T23:05:10.257987292Z at new Server (/app/node_modules/next/dist/server/base-server.js:68:29)

2023-05-01T23:05:10.257991112Z at new NextNodeServer (/app/node_modules/next/dist/server/next-server.js:70:9)

2023-05-01T23:05:10.257994982Z at NextServer.createServer (/app/node_modules/next/dist/server/next.js:147:16)

2023-05-01T23:05:10.257999072Z at async /app/node_modules/next/dist/server/next.js:159:31

2023-05-01T23:05:10.258005082Z at async NextServer.prepare (/app/node_modules/next/dist/server/next.js:134:24)

2023-05-01T23:05:10.258008942Z at async /app/node_modules/next/dist/cli/next-start.js:118:9

2023-05-01T23:05:10.285803120Z error Command failed with exit code 1.

2023-05-01T23:05:09.724382799Z $ next start

2023-05-01T23:05:09.881243271Z ready - started server on 0.0.0.0:3000, url: http://localhost:3000

2023-05-01T23:05:10.285747939Z info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Which browser are you using? (if relevant)

Coolify

### How are you deploying your application? (if relevant)

Coolify, Docker, NPM, private docker

**Comment by mikecao** [comment]
This error `Error: Could not find a production build in the '/app/.next' directory.` means that the application was not built. I'm not sure how that can happen in a docker image. Are you building your own image or pulling from Github?

**Comment by miguelgargallo** [comment]
I only assign a domain and port, on coolify and fails

**Comment by leo-unglaub** [comment]
@miguelgargallo i had the same problem with the git version. I have to do a `yarn build` every time i want to start umami, because the build, for some unknown reason, gets removed as soon as yarn stops. Thats propobly the same thing issue that happens in the docker container.

Running `yarn build && yarn start` before every start fixed it for me. Hope that helps you.

**Comment by miguelgargallo** [comment]
On Coolify, where i can find that?

![imagen](https://user-images.githubusercontent.com/5947268/236147580-346f5ddc-ab15-4b80-a903-3008b23bf581.png)

**Comment by miguelgargallo** [comment]
```
[10:24:06.400] #9 0.726 yarn run v1.22.19
[10:24:06.413] #9 0.847 $ npm-run-all build-db check-db build-tracker build-geo build-app
[10:24:06.420] #9 1.385 $ npm-run-all copy-db-files build-db-client
[10:24:06.424] #9 1.878 $ node scripts/copy-db-files.js
[10:24:06.427] #9 2.049 /app/scripts/copy-db-files.js:20
[10:24:06.430] #9 2.049   throw new Error('Missing or invalid database');
[10:24:06.434] #9 2.049   ^
[10:24:06.439] #9 2.049
[10:24:06.444] #9 2.049 Error: Missing or invalid database
[10:24:06.448] #9 2.049     at Object.<anonymous> (/app/scripts/copy-db-files.js:20:9)
[10:24:06.454] #9 2.049     at Module._compile (node:internal/modules/cjs/loader:1254:14)
[10:24:06.458] #9 2.049     at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
[10:24:06.461] #9 2.049     at Module.load (node:internal/modules/cjs/loader:1117:32)
[10:24:06.468] #9 2.049     at Module._load (node:internal/modules/cjs/loader:958:12)
[10:24:06.472] #9 2.049     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
[10:24:06.478] #9 2.049     at node:internal/main/run_main_module:23:47
[10:24:06.481] #9 2.051
[10:24:06.485] #9 2.051 Node.js v18.16.0
[10:24:06.495] #9 2.076 error Command failed with exit code 1.
[10:24:06.505] #9 2.076 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[10:24:06.509] #9 2.092 ERROR: "copy-db-files" exited with 1.
[10:24:06.514] #9 2.122 error Command failed with exit code 1.
[10:24:06.523] #9 2.122 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[10:24:06.551] #9 2.136 ERROR: "build-db" exited with 1.
[10:24:06.555] #9 2.156 error Command failed with exit code 1.
[10:24:06.558] #9 2.157 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[10:24:06.565] #9 ERROR: process "/bin/sh -c yarn build" did not complete successfully: exit code: 1
[10:24:06.568] ------
[10:24:06.571] > [5/6] RUN yarn build:
[10:24:06.574] ------
[10:24:06.579] process "/bin/sh -c yarn build" did not complete successfully: exit code: 1
```

But a db is being added on .env as secret
