### ISSUE TITLE
Thousands of "The column `website_event` does not exist in the current database." errors daily.

### ISSUE THREAD

**Issue by juanPolaco** [umami-software/umami#2048]
### Describe the Bug

Hey!

I have been getting a lot of logs saying that website_event doesn't exist but it does exist. This is impacting around 10% of our sessions. Looks like it might be more of a Prisma issue but I am not an expert on Prisma so not sure. 

Anyone else seeing this issue? 

We are running the latest version of Umami on GCP through Cloud Run with Cloud SQL for the database (PostgresSQL 14). The only change we have made is to add some triggers on the database which we did a long time ago and re did it after migrating to v2.

### Database

PostgreSQL

### Relevant log output

```shell
PrismaClientKnownRequestError:
Invalid `prisma.websiteEvent.create()` invocation:
The column `website_event` does not exist in the current database.
at pn.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:176:6477)
at pn.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:176:5907)
at pn.request (/app/node_modules/@prisma/client/runtime/library.js:176:5786)
at async t._request (/app/node_modules/@prisma/client/runtime/library.js:179:10484)
at async __WEBPACK_DEFAULT_EXPORT__ (/app/.next/server/pages/api/send.js:238:5)
at async Object.apiResolver (/app/node_modules/next/dist/server/api-utils/node.js:372:9)
at async NextNodeServer.runApi (/app/node_modules/next/dist/server/next-server.js:514:9)
at async Object.fn (/app/node_modules/next/dist/server/next-server.js:828:35)
at async Router.execute (/app/node_modules/next/dist/server/router.js:243:32)
at async NextNodeServer.runImpl (/app/node_modules/next/dist/server/base-server.js:432:29) {
code: 'P2022',
clientVersion: '4.13.0',
meta: { column: 'website_event' }
}
```

### How are you deploying your application? (if relevant)

Docker

**Comment by briancao** [comment]
I don't see `website_event` referenced anywhere like this in the application.  So this is either from an application query being altered, or the trigger is written incorrectly.  Feel free to post your trigger code and I can help you troubleshoot.

I assume the column name is missing, like `website_event.{column_name}` from the query.

**Comment by juanPolaco** [comment]
Thank you @briancao ! You were right! It was indeed on one of the triggers!
