### ISSUE TITLE
server node sometimes  failed  to connect mysql db (mysql is working ), then node processor will exit 

### ISSUE THREAD

**Issue by runtop** [umami-software/umami#2060]
### Describe the Bug

and the server is faild down. must be restart manually.

### Database

MySQL

### Relevant log output

```shell
PrismaClientKnownRequestError:
Invalid `prisma.user.findFirst()` invocation:


Timed out fetching a new connection from the connection pool. More info: http://pris.ly/d/connection-pool (Current connection pool timeout: 10, connection limit: 3)
    at pn.handleRequestError (/home/ubuntu/umami/node_modules/@prisma/client/runtime/library.js:176:6477)
    at pn.handleAndLogRequestError (/home/ubuntu/umami/node_modules/@prisma/client/runtime/library.js:176:5907)
    at pn.request (/home/ubuntu/umami/node_modules/@prisma/client/runtime/library.js:176:5786)
    at async t._request (/home/ubuntu/umami/node_modules/@prisma/client/runtime/library.js:179:10484)
    at async /home/ubuntu/umami/.next/server/chunks/3972.js:189:16 {
  code: 'P2024',
  clientVersion: '4.13.0',
  meta: { connection_limit: 3, timeout: 10 }
}

Node.js v18.16.0
error Command failed with exit code 1.
```

### How are you deploying your application? (if relevant)

by pull source code

**Comment by franciscao633** [comment]
Can you try increasing your connection limit from 3? I see a lot of results for that error coming from prisma, but it looked like it has been resolved since. Hopefully increasing the limit works.

**Comment by runtop** [comment]
thank your reply, i know it  maybe work by increasing mysql connections limit , but i am not a nodejs developer ,and do not know how to increase connection count  by modify prisma's config ?

**Comment by franciscao633** [comment]
You can just alter your MySQL connection string by adding parameters. For example `mysql://username:mypassword@localhost:3306/mydb?connection_limit=40&pool_timeout=20`

**Comment by runtop** [comment]
thanks a lot!
