### ISSUE TITLE
[@formatjs/intl] An `id` must be provided to format a message.

### ISSUE THREAD

**Issue by LWJerri** [umami-software/umami#2155]
### Describe the Bug

When I try to open the dashboard I see the error.

![image](https://github.com/umami-software/umami/assets/50290430/eecd7f13-a8e1-4152-8ce5-3f911566e023)

Repro repo: https://github.com/LWJerri/umami (v2.3.0 release).

### Database

PostgreSQL

### Relevant log output

```shell
Something went wrong.
[@formatjs/intl] An `id` must be provided to format a message. You can either: 1. Configure your build toolchain with [babel-plugin-formatjs](https://formatjs.io/docs/tooling/babel-plugin) or [@formatjs/ts-transformer](https://formatjs.io/docs/tooling/ts-transformer) OR 2. Configure your `eslint` config to include [eslint-plugin-formatjs](https://formatjs.io/docs/tooling/linter#enforce-id) to autofix this issue
Error: [@formatjs/intl] An `id` must be provided to format a message. You can either:
1. Configure your build toolchain with [babel-plugin-formatjs](https://formatjs.io/docs/tooling/babel-plugin)
or [@formatjs/ts-transformer](https://formatjs.io/docs/tooling/ts-transformer) OR
2. Configure your `eslint` config to include [eslint-plugin-formatjs](https://formatjs.io/docs/tooling/linter#enforce-id)
to autofix this issue
    at ep (https://umami.lwjerri.dev/_next/static/chunks/pages/_app-01e3fb586e5843a0.js:1:160)
    at eE (https://umami.lwjerri.dev/_next/static/chunks/pages/_app-01e3fb586e5843a0.js:6:577936)
    at e4 (https://umami.lwjerri.dev/_next/static/chunks/pages/_app-01e3fb586e5843a0.js:6:587683)
    at F (https://umami.lwjerri.dev/_next/static/chunks/pages/dashboard-ef3c6f276df533cc.js:1:5257)
    at ab (https://umami.lwjerri.dev/_next/static/chunks/framework-2c79e2a64abdb08b.js:9:60915)
    at ud (https://umami.lwjerri.dev/_next/static/chunks/framework-2c79e2a64abdb08b.js:9:72801)
    at i (https://umami.lwjerri.dev/_next/static/chunks/framework-2c79e2a64abdb08b.js:9:120370)
    at oO (https://umami.lwjerri.dev/_next/static/chunks/framework-2c79e2a64abdb08b.js:9:99112)
    at https://umami.lwjerri.dev/_next/static/chunks/framework-2c79e2a64abdb08b.js:9:98979
    at oF (https://umami.lwjerri.dev/_next/static/chunks/framework-2c79e2a64abdb08b.js:9:98986)
```

### How are you deploying your application? (if relevant)

Vercel

**Comment by LWJerri** [comment]
Related to https://github.com/umami-software/umami/issues/2153
