### ISSUE TITLE
Fetch event data error

### ISSUE THREAD

**Issue by eteplus** [umami-software/umami#2163]
### Describe the Bug

<img width="902" alt="image" src="https://github.com/umami-software/umami/assets/9312677/ff395644-6bbd-4fd4-9007-fcb5aa2bc167">

### Database

MySQL

### Relevant log output

```shell
PrismaClientKnownRequestError: 
Invalid `prisma.$queryRawUnsafe()` invocation:


Raw query failed. Code: `1105`. Message: `syntax error at position 115`
    at zr.handleRequestError (/var/task/node_modules/@prisma/client/runtime/library.js:122:8308)
    at zr.handleAndLogRequestError (/var/task/node_modules/@prisma/client/runtime/library.js:122:7697)
    at zr.request (/var/task/node_modules/@prisma/client/runtime/library.js:122:7307)
    at async __WEBPACK_DEFAULT_EXPORT__ (/var/task/.next/server/pages/api/event-data/events.js:154:22) {
  code: 'P2010',
  clientVersion: '5.0.0',
  meta: { code: '1105', message: 'syntax error at position 115' }
}
PrismaClientKnownRequestError: 
Invalid `prisma.$queryRawUnsafe()` invocation:


Raw query failed. Code: `1105`. Message: `syntax error at position 115`
    at zr.handleRequestError (/var/task/node_modules/@prisma/client/runtime/library.js:122:8308)
    at zr.handleAndLogRequestError (/var/task/node_modules/@prisma/client/runtime/library.js:122:7697)
    at zr.request (/var/task/node_modules/@prisma/client/runtime/library.js:122:7307)
    at async __WEBPACK_DEFAULT_EXPORT__ (/var/task/.next/server/pages/api/event-data/events.js:154:22) {
  code: 'P2010',
  clientVersion: '5.0.0',
  meta: { code: '1105', message: 'syntax error at position 115' }
}
RequestId: 67a5fab0-b265-4410-8a43-8014b728f8be Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Vercel

**Comment by franciscao633** [comment]
Confirmed. Looking into this.

**Comment by franciscao633** [comment]
This should be fixed in the most recent versions. Feel free to re-open if not the case. Thanks for reporting.
