### ISSUE TITLE
Settings -> Users -> Admin -> Edit -> Websites -> Error

### ISSUE THREAD

**Issue by iYoungblood** [umami-software/umami#2210]
### Describe the Bug

I have my "admin" user set to read only and I created another "admin" user, not named admin (security best practice).

I just upgraded to 2.5.0 and was clicking around looking for where to find my current version (Still haven't found it) and stumbled across this error: (I am logged in as the other admin user)

Something went wrong.
j is not a function
TypeError: j is not a function
    at w (https://owa.cloudautomation.blog/_next/static/chunks/420-0f9d38acd2802d57.js:1:1480)
    at https://owa.cloudautomation.blog/_next/static/chunks/pages/_app-663bdfebd59d6c1b.js:49:320775
    at uI (https://owa.cloudautomation.blog/_next/static/chunks/framework-73b8966a3c579ab0.js:9:84130)
    at oU (https://owa.cloudautomation.blog/_next/static/chunks/framework-73b8966a3c579ab0.js:9:113201)
    at https://owa.cloudautomation.blog/_next/static/chunks/framework-73b8966a3c579ab0.js:9:111581
    at oI (https://owa.cloudautomation.blog/_next/static/chunks/framework-73b8966a3c579ab0.js:9:111647)
    at oC (https://owa.cloudautomation.blog/_next/static/chunks/framework-73b8966a3c579ab0.js:9:96276)
    at r4 (https://owa.cloudautomation.blog/_next/static/chunks/framework-73b8966a3c579ab0.js:9:44778)
    at https://owa.cloudautomation.blog/_next/static/chunks/framework-73b8966a3c579ab0.js:9:93632

### Database

MySQL

### Which browser are you using? (if relevant)

Chrome

**Comment by mikecao** [comment]
Fixed in v2.6.0.
