### ISSUE TITLE
Umami panel settings link throws internal server error when clicked directly

### ISSUE THREAD

**Issue by Evavic44** [umami-software/umami#2213]
### Describe the Bug

On the Umami admin panel, when you click on the `settings` link on the navigation bar, it navigates to `http://localhost:3000/settings/websites` and throws an `internal server error` but when you follow through the profile button, this `/settings/websites` route seems to be working.

### Database

MySQL

### Relevant log output

```shell
TypeError: Cannot read properties of null (reading 'useRef')
    at exports.useRef (C:\Users\USER\Desktop\Projects\personal-project\umami\node_modules\react\cjs\react.production.min.js:25:337)
    at exports.useSyncExternalStoreWithSelector (C:\Users\USER\Desktop\Projects\personal-project\umami\node_modules\use-sync-external-store\cjs\use-sync-external-store-shim\with-selector.production.min.js:11:68)
    at useStore (file:///C:/Users/USER/Desktop/Projects/personal-project/umami/node_modules/zustand/esm/index.mjs:8:17)
    at useBoundStore (file:///C:/Users/USER/Desktop/Projects/personal-project/umami/node_modules/zustand/esm/index.mjs:25:51)
    at useLocale (C:\Users\USER\Desktop\Projects\personal-project\umami\.next\server\chunks\1649.js:63:83)
    at App (C:\Users\USER\Desktop\Projects\personal-project\umami\.next\server\pages\_app.js:189:104)
    at Wc (C:\Users\USER\Desktop\projects\personal-project\umami\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:68:44)  
    at Zc (C:\Users\USER\Desktop\projects\personal-project\umami\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:70:253) 
    at Z (C:\Users\USER\Desktop\projects\personal-project\umami\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:76:89)   
    at Zc (C:\Users\USER\Desktop\projects\personal-project\umami\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:70:481)
```

### Which browser are you using? (if relevant)

Firefox, Chrome

**Comment by franciscao633** [comment]
I can't seem to reproduce the error. Are you on v2.5.0 with Websites / Reports in the nav bar? Can you do another install, build, start and see if it resolves?
