### ISSUE TITLE
All report querys error with 405

### ISSUE THREAD

**Issue by AndrisBorbas** [umami-software/umami#2273]
### Describe the Bug

Any query I make from the reports page just returns 405 error, and on vercel it produces the error I pasted below. 

This is the repo where I build from if relevant: https://github.com/AndrisBorbas/umami

### Database

MySQL

### Relevant log output

```shell
PrismaClientKnownRequestError: 
Invalid `prisma.$queryRawUnsafe()` invocation:


Raw query failed. Code: `1105`. Message: `unknown error: syntax error at position 10 near 'WITH'`
    at vn.handleRequestError (/var/task/node_modules/@prisma/client/runtime/library.js:123:6730)
    at vn.handleAndLogRequestError (/var/task/node_modules/@prisma/client/runtime/library.js:123:6119)
    at vn.request (/var/task/node_modules/@prisma/client/runtime/library.js:123:5839)
    at async l (/var/task/node_modules/@prisma/client/runtime/library.js:128:9763)
    at async __WEBPACK_DEFAULT_EXPORT__ (/var/task/.next/server/pages/api/reports/retention.js:461:22) {
  code: 'P2010',
  clientVersion: '5.2.0',
  meta: {
    code: '1105',
    message: "unknown error: syntax error at position 10 near 'WITH'"
  }
}
PrismaClientKnownRequestError: 
Invalid `prisma.$queryRawUnsafe()` invocation:


Raw query failed. Code: `1105`. Message: `unknown error: syntax error at position 10 near 'WITH'`
    at vn.handleRequestError (/var/task/node_modules/@prisma/client/runtime/library.js:123:6730)
    at vn.handleAndLogRequestError (/var/task/node_modules/@prisma/client/runtime/library.js:123:6119)
    at vn.request (/var/task/node_modules/@prisma/client/runtime/library.js:123:5839)
    at async l (/var/task/node_modules/@prisma/client/runtime/library.js:128:9763)
    at async __WEBPACK_DEFAULT_EXPORT__ (/var/task/.next/server/pages/api/reports/retention.js:461:22) {
  code: 'P2010',
  clientVersion: '5.2.0',
  meta: {
    code: '1105',
    message: "unknown error: syntax error at position 10 near 'WITH'"
  }
}
PrismaClientKnownRequestError: 
Invalid `prisma.$queryRawUnsafe()` invocation:


Raw query failed. Code: `1105`. Message: `unknown error: syntax error at position 10 near 'WITH'`
    at vn.handleRequestError (/var/task/node_modules/@prisma/client/runtime/library.js:123:6730)
    at vn.handleAndLogRequestError (/var/task/node_modules/@prisma/client/runtime/library.js:123:6119)
    at vn.request (/var/task/node_modules/@prisma/client/runtime/library.js:123:5839)
    at async l (/var/task/node_modules/@prisma/client/runtime/library.js:128:9763)
    at async __WEBPACK_DEFAULT_EXPORT__ (/var/task/.next/server/pages/api/reports/retention.js:461:22) {
  code: 'P2010',
  clientVersion: '5.2.0',
  meta: {
    code: '1105',
    message: "unknown error: syntax error at position 10 near 'WITH'"
  }
}
RequestId: db8e2243-e582-4834-9f25-88dfb9f3c58e Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

### Which browser are you using? (if relevant)

Chrome 116.0.5845.141

### How are you deploying your application? (if relevant)

Vercel, Planetscale

**Comment by franciscao633** [comment]
I cloned your repo and everything is working fine. I'm currently testing on MySQL 8.0. Do you know what version of MySQL your Planetscale is running? I'm wondering it its specific to Planetscale.

**Comment by AndrisBorbas** [comment]
It doesn't say anywhere, but i found this: https://planetscale.com/docs/reference/mysql-compatibility

**Comment by AndrisBorbas** [comment]
These might be related: https://github.com/planetscale/discussion/discussions/245
https://github.com/vitessio/vitess/issues/9459

**Comment by franciscao633** [comment]
That is definitely it, if Planetscale doesn't support CTEs. Would take some time and effort to convert the CTEs into subqueries and test. I'll mention it to the team, so we can review.
