### ISSUE TITLE
errno: -111 after running for brief period of time (Docker)

### ISSUE THREAD

**Issue by CactusChaos** [umami-software/umami#2275]
### Describe the Bug

When I launch umami it runs fine for a little bit (Sometimes it straight up doesn't run at all) but then the boxes become "Something went wrong" and on refresh I get internal server error. I initially thought this was a problem with the system running out of resources but I upgraded my vps, doubling the ram (8gb) and I am still having the same issue. The docker compose logs are:

### Database

PostgreSQL

### Relevant log output

```shell
umami-umami-1  | TypeError: fetch failed
umami-umami-1  |     at Object.fetch (node:internal/deps/undici/undici:11576:11)
umami-umami-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
umami-umami-1  |     at async invokeRequest (/app/node_modules/next/dist/server/lib/server-ipc/invoke-request.js:17:12)
umami-umami-1  |     at async invokeRender (/app/node_modules/next/dist/server/lib/router-server.js:254:29)
umami-umami-1  |     at async requestHandler (/app/node_modules/next/dist/server/lib/router-server.js:475:24)
umami-umami-1  |     at async Server.<anonymous> (/app/node_modules/next/dist/server/lib/start-server.js:117:13) {
umami-umami-1  |   cause: Error: connect ECONNREFUSED 172.26.2.3:36115
umami-umami-1  |       at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16) {
umami-umami-1  |     errno: -111,
umami-umami-1  |     code: 'ECONNREFUSED',
umami-umami-1  |     syscall: 'connect',
umami-umami-1  |     address: '172.26.2.3',
umami-umami-1  |     port: 36115
umami-umami-1  |   }
```
and for db
```
umami-db-1  | 2023-09-05 08:17:26.801 UTC [36] ERROR:  relation "account" does not exist at character 15
umami-db-1  | 2023-09-05 08:17:26.801 UTC [36] STATEMENT:  select * from account limit 1
umami-db-1  | 2023-09-05 08:17:27.824 UTC [37] LOG:  could not receive data from client: Connection reset by peer
```
```


### Which browser are you using? (if relevant)

Firefox

### How are you deploying your application? (if relevant)

Docker

**Comment by thueske** [comment]
Same problem here since v2.6.x but no helpful log output. I need to restart Umami every day :/

**Comment by franciscao633** [comment]
Do you know what version of node you are running? I wonder if its related to this #876. Besides that double-check the port and address are open to connections. Looks like a general connection error.

**Comment by CactusChaos** [comment]
Node version is v16.20.2. Regarding ports, it all appears fine, and it does work for a little bit so that makes me think it is not them? I am running on stock ports with port 9000 proxied through nginx.

**Comment by iYoungblood** [comment]
I also have a similar error. Unami seems to be running fine but it is not pulling data from WordPress as it used it, which is why I'm here.

```
unami-db-1  | 2023-09-08 19:52:23.646 UTC [1] LOG:  database system is ready to accept connections
unami-db-1  | 2023-09-08 19:52:30.846 UTC [38] ERROR:  relation "account" does not exist at character 15
unami-db-1     | 2023-09-08 19:52:30.846 UTC [38] STATEMENT:  select * from account limit 1
unami-db-1     | 2023-09-08 19:52:32.001 UTC [40] LOG:  could not receive data from client: Connection reset by peer
unami-db-1     | 2023-09-08 19:57:23.737 UTC [23] LOG:  checkpoint starting: time
unami-db-1     | 2023-09-08 19:57:23.741 UTC [23] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.002 s, sync=0.001 s, total=0.004 s; sync files=2, longest=0.001 s, average=0.001 s; distance=0 kB, estimate=0 kB
unami-db-1     | 2023-09-09 00:52:28.957 UTC [23] LOG:  checkpoint starting: time
unami-db-1     | 2023-09-09 00:52:32.070 UTC [23] LOG:  checkpoint complete: wrote 32 buffers (0.2%); 0 WAL file(s) added, 0 removed, 0 recycled; write=3.109 s, sync=0.001 s, total=3.113 s; sync files=28, longest=0.001 s, average=0.001 s; distance=139 kB, estimate=139 kB
```

**Comment by slig** [comment]
Experiencing the same issue on a brand new ARM64 server running Caprover.

```
2023-09-09T16:41:22.442567195Z TypeError: fetch failed
2023-09-09T16:41:22.442668476Z at Object.fetch (node:internal/deps/undici/undici:11576:11)
2023-09-09T16:41:22.442679396Z at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-09-09T16:41:22.442686916Z at async invokeRequest (/app/node_modules/next/dist/server/lib/server-ipc/invoke-request.js:17:12)
2023-09-09T16:41:22.442693196Z at async invokeRender (/app/node_modules/next/dist/server/lib/router-server.js:254:29)
2023-09-09T16:41:22.442699197Z at async requestHandler (/app/node_modules/next/dist/server/lib/router-server.js:475:24)
2023-09-09T16:41:22.442705197Z at async Server.<anonymous> (/app/node_modules/next/dist/server/lib/start-server.js:117:13) {
2023-09-09T16:41:22.442711477Z cause: Error: connect ECONNREFUSED 10.0.1.21:38921
2023-09-09T16:41:22.442717197Z at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16) {
2023-09-09T16:41:22.442723277Z errno: -111,
2023-09-09T16:41:22.442728717Z code: 'ECONNREFUSED',
2023-09-09T16:41:22.442734157Z syscall: 'connect',
2023-09-09T16:41:22.442739557Z address: '10.0.1.21',
2023-09-09T16:41:22.442744957Z port: 38921
2023-09-09T16:41:22.442750317Z }
2023-09-09T16:41:22.442755557Z }
```

**Comment by jc0b** [comment]
I also have the same, running Umami in Docker on arm64 behind an nginx reverse proxy using the included docker-compose.yml.

```
TypeError: fetch failed
umami-umami-1  |     at Object.fetch (node:internal/deps/undici/undici:11576:11)
umami-umami-1  |     at async invokeRequest (/app/node_modules/next/dist/server/lib/server-ipc/invoke-request.js:17:12)
umami-umami-1  |     at async invokeRender (/app/node_modules/next/dist/server/lib/router-server.js:254:29)
umami-umami-1  |     at async requestHandler (/app/node_modules/next/dist/server/lib/router-server.js:475:24)
umami-umami-1  |     at async Server.<anonymous> (/app/node_modules/next/dist/server/lib/start-server.js:117:13) {
umami-umami-1  |   cause: SocketError: other side closed
umami-umami-1  |       at Socket.onSocketEnd (/app/node_modules/next/dist/compiled/undici/index.js:1:63301)
umami-umami-1  |       at Socket.emit (node:events:526:35)
umami-umami-1  |       at endReadableNT (node:internal/streams/readable:1359:12)
umami-umami-1  |       at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
umami-umami-1  |     code: 'UND_ERR_SOCKET',
umami-umami-1  |     socket: {
umami-umami-1  |       localAddress: '192.168.224.3',
umami-umami-1  |       localPort: 59032,
umami-umami-1  |       remoteAddress: undefined,
umami-umami-1  |       remotePort: undefined,
umami-umami-1  |       remoteFamily: undefined,
umami-umami-1  |       timeout: undefined,
umami-umami-1  |       bytesWritten: 8036,
umami-umami-1  |       bytesRead: 1167
umami-umami-1  |     }
umami-umami-1  |   }
umami-umami-1  | }
```

**Comment by danielelic** [comment]
I have similar error. I'm using ghcr.io/umami-software/umami:postgresql-v2.6.2 on my OCI k3s cluster with Ampere Altra A1 compute platform.

```
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11576:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async invokeRequest (/app/node_modules/next/dist/server/lib/server-ipc/invoke-request.js:17:12)
    at async invokeRender (/app/node_modules/next/dist/server/lib/router-server.js:254:29)
    at async requestHandler (/app/node_modules/next/dist/server/lib/router-server.js:475:24)
    at async Server.<anonymous> (/app/node_modules/next/dist/server/lib/start-server.js:117:13) {
  cause: Error: connect ECONNREFUSED 10.42.0.188:34267
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '10.42.0.188',
    port: 34267
  }
}
```

**Comment by slig** [comment]
Anyone with this issue *NOT* on arm64?

**Comment by Antjrobles** [comment]
Same error here, running ubuntu and debian: 
```
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11576:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async invokeRequest (/app/node_modules/next/dist/server/lib/server-ipc/invoke-request.js:17:12)
    at async invokeRender (/app/node_modules/next/dist/server/lib/router-server.js:254:29)
    at async requestHandler (/app/node_modules/next/dist/server/lib/router-server.js:475:24)
    at async Server.<anonymous> (/app/node_modules/next/dist/server/lib/start-server.js:117:13) {
  cause: Error: connect ECONNREFUSED 172.16.128.3:36755
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '172.16.128.3',
    port: 36755
  }
}
````
Tried differents machines but same error. Im using the standar docker-compose, changed nothing:
```
version: '3'
services:
  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest
    container_name: umami
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://umami:umami@db:5432/umami
      DATABASE_TYPE: postgresql
      APP_SECRET: replace-me-with-a-random-string
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15-alpine
    container_name: umami-db
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: umami
    volumes:
      - umami-db-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  umami-db-data:
````
Thanks

**Comment by slig** [comment]
It's been fixed in the latest release.

**Comment by CactusChaos** [comment]
Just updated and no issues as far as I can tell, so will close! Thanks guys
