### ISSUE TITLE
Umami seems to hang for no reason

### ISSUE THREAD

**Issue by brunoamaral** [umami-software/umami#2290]
### Describe the Bug

I'm running docker in two different servers, and only one of them seems to hang. The only difference between them, is that the one that runs smoothly is only measuring one website.

The other ends the log with this message:
```
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11576:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async invokeRequest (/app/node_modules/next/dist/server/lib/server-ipc/invoke-request.js:17:12)
    at async invokeRender (/app/node_modules/next/dist/server/lib/router-server.js:254:29)
    at async requestHandler (/app/node_modules/next/dist/server/lib/router-server.js:475:24)
    at async Server.<anonymous> (/app/node_modules/next/dist/server/lib/start-server.js:117:13) {
  cause: Error: connect ECONNREFUSED 172.18.0.3:36977
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '172.18.0.3',
    port: 36977
  }
}
```
I'm not sure what this means but every time that I restart the container it keeps running ok for some time.

### Database

PostgreSQL

### Relevant log output

```shell
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11576:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async invokeRequest (/app/node_modules/next/dist/server/lib/server-ipc/invoke-request.js:17:12)
    at async invokeRender (/app/node_modules/next/dist/server/lib/router-server.js:254:29)
    at async requestHandler (/app/node_modules/next/dist/server/lib/router-server.js:475:24)
    at async Server.<anonymous> (/app/node_modules/next/dist/server/lib/start-server.js:117:13) {
  cause: Error: connect ECONNREFUSED 172.18.0.3:36977
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '172.18.0.3',
    port: 36977
  }
}
```

### How are you deploying your application? (if relevant)

Docker

**Comment by Excigma** [comment]
This issue also occurs with my Next.js application, and it seems pretty widespread across Next.js projects. If you search for "ECONNREFUSED" in their server, there has been a spike in reports of this since early August.

However, there seem to be no fixes other than downgrading Next.js to 13.4.12. Some people have suggested upgrading to the latest canary works as well.

**Comment by amanpatel** [comment]
Yup, for me, this occurs immediately if I click "Refresh" in the browser. This is very debilitating, how can a browser refresh break a backend application?  <rant> With all the javascript advancements we've made, sometimes I think back to `cgi-bin` days with perl scripts, they would never fail in this manner. </rant>

Anyway. I appreciate your response @Excigma  is there anyway someone would downgrade or upgrade to canary via the provided dockerhub images? When I browse the repo, I don't see these as avaialble. I guess we would have to build our own images to fix this problem. That would be very inconvinient.

**Comment by Excigma** [comment]
@amanpatel unfortunately I'm not too sure how to do that, is it possible to make your own dockerfile and specify umami as the base image (e.g. FROM)? Then adding yarn or npm commands to downgrade or upgrade... not very neat but should do the job

**Comment by amanpatel** [comment]
I think I have a FIX! 

When I swtiich to the image from `docker.umami.dev/umami-software/umami:postgresql-latest` (from the README instructions). I think it fixes this issue. Its been running stable for atleast a few hours (previously it would crash pretty much immediately).

If I have any issues, I'll update this ticket.

**Comment by brunoamaral** [comment]
isn't the correct image ` ghcr.io/umami-software/umami:postgresql-latest` ?

**Comment by slig** [comment]
It's been fixed in the latest release.
