### ISSUE TITLE
`yarn install` can't done

### ISSUE THREAD

**Issue by MagmaBlock** [umami-software/umami#2405]
### Describe the Bug

Follow the official docs, I clone git repo and run `yarn install`
Can't finish:

```bash
root@shanghai-tencentcloud-lighthouse1:/opt/umami# yarn install
yarn install v1.22.21
[1/4] Resolving packages...
[2/4] Fetching packages...
warning chart.js@4.4.0: The engine "pnpm" appears to be invalid.
[3/4] Linking dependencies...
warning " > @umami/prisma-client@0.3.0" has incorrect peer dependency "@prisma/client@^4.8.0".
warning " > react-simple-maps@2.3.0" has incorrect peer dependency "react@^16.8.0 || 17.x".
warning " > react-simple-maps@2.3.0" has incorrect peer dependency "react-dom@^16.8.0 || 17.x".
warning " > react-simple-maps@2.3.0" has unmet peer dependency "prop-types@^15.7.2".
warning " > rollup-plugin-terser@7.0.2" has incorrect peer dependency "rollup@^2.0.0".
warning " > stylelint-config-prettier@9.0.5" has incorrect peer dependency "stylelint@>= 11.x < 15".
warning " > stylelint-config-recommended@9.0.0" has incorrect peer dependency "stylelint@^14.10.0".
warning Workspaces can only be enabled in private projects.
[4/4] Building fresh packages...
[-/6] ⠠ waiting...
[-/6] ⠠ waiting...
[3/6] ⠠ sharp
[-/6] ⠠ waiting...
error /opt/umami/node_modules/sharp: Command failed.
Exit code: 1
Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
Arguments: 
Directory: /opt/umami/node_modules/sharp
Output:
sharp: Using cached /root/.npm/_libvips/libvips-8.14.5-linux-x64.tar.br
sharp: Integrity check passed for linux-x64
prebuild-install warn install connect ETIMEDOUT 20.205.243.166:443
gyp info it worked if it ends with ok
gyp info using node-gyp@10.0.1
gyp info using node@18.18.0 | linux | x64
gyp info find Python using Python version 3.11.2 found at "/usr/bin/python3"

gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args 'binding.gyp',
gyp info spawn args '-f',
gyp info spawn args 'make',
gyp info spawn args '-I',
gyp info spawn args '/opt/umami/node_modules/sharp/build/config.gypi',
gyp info spawn args '-I',
gyp info spawn args '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args '-I',
gyp info spawn args '/root/.cache/node-gyp/18.18.0/include/node/common.gypi',
gyp info spawn args '-Dlibrary=shared_library',
gyp info spawn args '-Dvisibility=default',
gyp info spawn args '-Dnode_root_dir=/root/.cache/node-gyp/18.18.0',
gyp info spawn args '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args '-Dnode_lib_file=/root/.cache/node-gyp/18.18.0/<(target_arch)/node.lib',
gyp info spawn args '-Dmodule_root_dir=/opt/umami/node_modules/sharp',
gyp info spawn args '-Dnode_engine=v8',
gyp info spawn args '--depth=.',
gyp info spawn args '--no-parallel',
gyp info spawn args '--generator-output',
gyp info spawn args 'build',
gyp info spawn args '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/opt/umami/node_modules/sharp/build'
  CC(target) Release/obj.target/nothing/../node-addon-api/nothing.o
rm -f Release/obj.target/../node-addon-api/nothing.a Release/obj.target/../node-addon-api/nothing.a.ar-file-list; mkdir -p `dirname Release/obj.target/../node-addon-api/nothing.a`
ar crs Release/obj.target/../node-addon-api/nothing.a @Release/obj.target/../node-addon-api/nothing.a.ar-file-list
  COPY Release/nothing.a
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp-linux-x64/src/common.o
make: g++: No such file or directory
make: *** [sharp-linux-x64.target.mk:143: Release/obj.target/sharp-linux-x64/src/common.o] Error 127
make: Leaving directory '/opt/umami/node_modules/sharp/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:209:23)
gyp ERR! System Linux 6.1.0-10-amd64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/umami/node_modules/sharp
```

After ask ChatGPT, I try to use apt-get to install `build-essential`, different error happened:

```
error /opt/umami/node_modules/sharp: Command failed.
Exit code: 1
Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
Arguments: 
Directory: /opt/umami/node_modules/sharp
Output:
sharp: Using cached /root/.npm/_libvips/libvips-8.14.5-linux-x64.tar.br
sharp: Integrity check passed for linux-x64
prebuild-install warn install connect ETIMEDOUT 20.205.243.166:443
gyp info it worked if it ends with ok
gyp info using node-gyp@10.0.1
gyp info using node@18.18.0 | linux | x64
gyp info find Python using Python version 3.11.2 found at "/usr/bin/python3"

gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args 'binding.gyp',
gyp info spawn args '-f',
gyp info spawn args 'make',
gyp info spawn args '-I',
gyp info spawn args '/opt/umami/node_modules/sharp/build/config.gypi',
gyp info spawn args '-I',
gyp info spawn args '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args '-I',
gyp info spawn args '/root/.cache/node-gyp/18.18.0/include/node/common.gypi',
gyp info spawn args '-Dlibrary=shared_library',
gyp info spawn args '-Dvisibility=default',
gyp info spawn args '-Dnode_root_dir=/root/.cache/node-gyp/18.18.0',
gyp info spawn args '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args '-Dnode_lib_file=/root/.cache/node-gyp/18.18.0/<(target_arch)/node.lib',
gyp info spawn args '-Dmodule_root_dir=/opt/umami/node_modules/sharp',
gyp info spawn args '-Dnode_engine=v8',
gyp info spawn args '--depth=.',
gyp info spawn args '--no-parallel',
gyp info spawn args '--generator-output',
gyp info spawn args 'build',
gyp info spawn args '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/opt/umami/node_modules/sharp/build'
  CC(target) Release/obj.target/nothing/../node-addon-api/nothing.o
rm -f Release/obj.target/../node-addon-api/nothing.a Release/obj.target/../node-addon-api/nothing.a.ar-file-list; mkdir -p `dirname Release/obj.target/../node-addon-api/nothing.a`
ar crs Release/obj.target/../node-addon-api/nothing.a @Release/obj.target/../node-addon-api/nothing.a.ar-file-list
  COPY Release/nothing.a
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp-linux-x64/src/common.o
../src/common.cc:13:10: fatal error: vips/vips8: No such file or directory
   13 | #include <vips/vips8>
      |          ^~~~~~~~~~~~
compilation terminated.
make: *** [sharp-linux-x64.target.mk:143: Release/obj.target/sharp-linux-x64/src/common.o] Error 1
make: Leaving directory '/opt/umami/node_modules/sharp/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:209:23)
gyp ERR! System Linux 6.1.0-10-amd64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/umami/node_modules/sharp
```

I tried many times in some days, but still can't success.
Is this a network issue? A few months ago I was use umami v1, but many problems also cause while I update the umami. The build process is always difficult to complete and requires dozens of attempts

### Database

MySQL

**Comment by MagmaBlock** [comment]
After I sent this issue, I tried again and it miraculously succeeded. This is highly likely a network problem

**Comment by MagmaBlock** [comment]
Hope more debug log in error
