### ISSUE TITLE
✗ Failed to run sql file /db/postgresql/data-migration-v2.sql

### ISSUE THREAD

**Issue by candidexmedia** [umami-software/umami#2475]
### Describe the Bug

Hi! I'm attempting to migrate my [v1 Supabase database to v2](https://github.com/umami-software/migrate-v1-v2/issues/7), via a Vercel deployment.

Unfortunately, I ran into the following error(s):

```Shell
yarn start
yarn run v1.22.10
$ node index.js
Running v0.15.0
✓ DATABASE_URL is defined.
✓ Database connection successful.
✓ Database v1 tables ready for migration.
✓ Database v2 tables found.
✓ Database is ready for migration.
✓ Starting v2 data migration. Please do no cancel this process, it may take a while.
PrismaClientKnownRequestError:
Invalid `prisma.$executeRawUnsafe()` invocation:


Raw query failed. Code: `42703`. Message: `column e.event_name does not exist`
    at Zr.handleRequestError (C:\.....\migrate-v1-v2\node_modules\@prisma\client\runtime\library.js:171:6414)
    at Zr.handleAndLogRequestError (C:\.....\migrate-v1-v2\node_modules\@prisma\client\runtime\library.js:171:5948)
    at Zr.request (C:\.....\migrate-v1-v2\node_modules\@prisma\client\runtime\library.js:171:5786)
    at async Proxy._request (C:\.....\migrate-v1-v2\node_modules\@prisma\client\runtime\library.js:174:10455)
    at async runSqlFile (C:\.....\migrate-v1-v2\index.js:277:9)
    at async migrateData (C:\.....\migrate-v1-v2\index.js:109:3)
    at async C:\.....\migrate-v1-v2\index.js:308:7 {
  code: 'P2010',
  clientVersion: '4.11.0',
  meta: { code: '42703', message: 'column e.event_name does not exist' }
}
✗ Failed to run sql file /db/postgresql/data-migration-v2.sql.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Database

PostgreSQL

### Relevant log output

```shell
yarn start
yarn run v1.22.10
$ node index.js
Running v0.15.0
✓ DATABASE_URL is defined.
✓ Database connection successful.
✓ Database v1 tables ready for migration.
✓ Database v2 tables found.
✓ Database is ready for migration.
✓ Starting v2 data migration. Please do no cancel this process, it may take a while.
PrismaClientKnownRequestError:
Invalid `prisma.$executeRawUnsafe()` invocation:


Raw query failed. Code: `42703`. Message: `column e.event_name does not exist`
    at Zr.handleRequestError (C:\.....\migrate-v1-v2\node_modules\@prisma\client\runtime\library.js:171:6414)
    at Zr.handleAndLogRequestError (C:\.....\migrate-v1-v2\node_modules\@prisma\client\runtime\library.js:171:5948)
    at Zr.request (C:\.....\migrate-v1-v2\node_modules\@prisma\client\runtime\library.js:171:5786)
    at async Proxy._request (C:\.....\migrate-v1-v2\node_modules\@prisma\client\runtime\library.js:174:10455)
    at async runSqlFile (C:\.....\migrate-v1-v2\index.js:277:9)
    at async migrateData (C:\.....\migrate-v1-v2\index.js:109:3)
    at async C:\.....\migrate-v1-v2\index.js:308:7 {
  code: 'P2010',
  clientVersion: '4.11.0',
  meta: { code: '42703', message: 'column e.event_name does not exist' }
}
✗ Failed to run sql file /db/postgresql/data-migration-v2.sql.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### How are you deploying your application? (if relevant)

Supabase + Vercel

**Comment by candidexmedia** [comment]
Turns out, I had to create a column in v1_event called "event_name", and run yarn start again
