### ISSUE TITLE
Error with Event Data Submission via /api/send

### ISSUE THREAD

**Issue by RainyCodeWizard** [umami-software/umami#2523]
### Describe the Bug

when sending event data via /api/send the following data: 
`"data":{"selectedFilter":"trending","selectedTrendingDays":"30"}}`

I face this error :
<details><summary>Error</summary>

```
 ⨯ PrismaClientValidationError: 
Invalid `prisma.eventData.createMany()` invocation:

{
  data: [
    {
      id: "6046182f-f665-423f-8bc8-28da84ff39ca",
      websiteEventId: "1adec6d0-7ed0-4de0-a4fe-827f9853b05d",
      websiteId: "535b38bb-32c6-4c16-af01-20892873c22c",
      eventKey: "selectedFilter",
      stringValue: "trending",
      numberValue: null,
      dateValue: null,
      dataType: 1
    },
    {
      id: "1e1c8f8c-f77f-4465-918f-934b6f7e0835",
      websiteEventId: "1adec6d0-7ed0-4de0-a4fe-827f9853b05d",
      websiteId: "535b38bb-32c6-4c16-af01-20892873c22c",
      eventKey: "selectedTrendingDays",
      stringValue: "30Z",
      numberValue: null,
      dateValue: new Date("Invalid Date"),
                 ~~~~~~~~~~~~~~~~~~~~~~~~
      dataType: 4
    }
  ]
}

Invalid value for argument `dateValue`: Provided Date object is invalid. Expected Date.
    at Zn (/Users/hussain/Git_Repos/navCentral/umami/node_modules/@prisma/client/runtime/library.js:117:5888)
    at e.throwValidationError (/Users/hussain/Git_Repos/navCentral/umami/node_modules/@prisma/client/runtime/library.js:117:9750)
    at Nl (/Users/hussain/Git_Repos/navCentral/umami/node_modules/@prisma/client/runtime/library.js:117:7819)
    at Ll (/Users/hussain/Git_Repos/navCentral/umami/node_modules/@prisma/client/runtime/library.js:117:8972)
    at Nl (/Users/hussain/Git_Repos/navCentral/umami/node_modules/@prisma/client/runtime/library.js:117:8512)
    at rf (/Users/hussain/Git_Repos/navCentral/umami/node_modules/@prisma/client/runtime/library.js:117:9406)
    at Nl (/Users/hussain/Git_Repos/navCentral/umami/node_modules/@prisma/client/runtime/library.js:117:8148)
    at Ll (/Users/hussain/Git_Repos/navCentral/umami/node_modules/@prisma/client/runtime/library.js:117:8972)
    at Ro (/Users/hussain/Git_Repos/navCentral/umami/node_modules/@prisma/client/runtime/library.js:117:6801)
    at Ol (/Users/hussain/Git_Repos/navCentral/umami/node_modules/@prisma/client/runtime/library.js:117:6731)
    at /Users/hussain/Git_Repos/navCentral/umami/node_modules/@prisma/client/runtime/library.js:129:10548
    at Object.runInChildSpan (/Users/hussain/Git_Repos/navCentral/umami/node_modules/@prisma/client/runtime/library.js:124:1481)
    at t._executeRequest (/Users/hussain/Git_Repos/navCentral/umami/node_modules/@prisma/client/runtime/library.js:129:10527)
    at Ba (/Users/hussain/Git_Repos/navCentral/umami/node_modules/@prisma/client/runtime/library.js:34:5144)
    at l (/Users/hussain/Git_Repos/navCentral/umami/node_modules/@prisma/client/runtime/library.js:129:10029) {
  clientVersion: '5.6.0',
  page: '/api/send'
}
```

</details>

I found a bug in the code that results in the above error. In `src/lib/data.ts` function `getDataType` uses `isValid(parseISO(value))` to check if a value is a valid date. And for the value of `'30'` for `'selectedTrendingDays'`,  it returns true. 

However, on `src/queries/analytics/eventData/saveEventData.ts`, it then uses `dateValue: a.dynamicDataType === DATA_TYPE.date ? new Date(a.value) : null` to get the date value. Which results as "Invalid Date" for the value of 30. 

I suggest replacing isValid(parseISO(value)) with isValid(new Date(value)) to address this issue. The updated getDataType() function would look like this:

```
// src/lib/data.ts

export function getDataType(value: any): string {
  let type: string = typeof value;

  if ((type === 'string' && isValid(value)) || isValid(new Date(value))) {
    type = 'date';
  }

  return type;
}
```

### Database

PostgreSQL

### Relevant log output

```shell
⨯ PrismaClientValidationError: 
Invalid `prisma.eventData.createMany()` invocation:

{
  data: [
    {
      id: "6046182f-f665-423f-8bc8-28da84ff39ca",
      websiteEventId: "1adec6d0-7ed0-4de0-a4fe-827f9853b05d",
      websiteId: "535b38bb-32c6-4c16-af01-20892873c22c",
      eventKey: "selectedFilter",
      stringValue: "trending",
      numberValue: null,
      dateValue: null,
      dataType: 1
    },
    {
      id: "1e1c8f8c-f77f-4465-918f-934b6f7e0835",
      websiteEventId: "1adec6d0-7ed0-4de0-a4fe-827f9853b05d",
      websiteId: "535b38bb-32c6-4c16-af01-20892873c22c",
      eventKey: "selectedTrendingDays",
      stringValue: "30Z",
      numberValue: null,
      dateValue: new Date("Invalid Date"),
                 ~~~~~~~~~~~~~~~~~~~~~~~~
      dataType: 4
    }
  ]
}

Invalid value for argument `dateValue`: Provided Date object is invalid. Expected Date.
    at Zn (/Users/hussain/Git_Repos/navCentral/umami/node_modules/@prisma/client/runtime/library.js:117:5888)
    at e.throwValidationError (/Users/hussain/Git_Repos/navCentral/umami/node_modules/@prisma/client/runtime/library.js:117:9750)
    at Nl (/Users/hussain/Git_Repos/navCentral/umami/node_modules/@prisma/client/runtime/library.js:117:7819)
    at Ll (/Users/hussain/Git_Repos/navCentral/umami/node_modules/@prisma/client/runtime/library.js:117:8972)
    at Nl (/Users/hussain/Git_Repos/navCentral/umami/node_modules/@prisma/client/runtime/library.js:117:8512)
    at rf (/Users/hussain/Git_Repos/navCentral/umami/node_modules/@prisma/client/runtime/library.js:117:9406)
    at Nl (/Users/hussain/Git_Repos/navCentral/umami/node_modules/@prisma/client/runtime/library.js:117:8148)
    at Ll (/Users/hussain/Git_Repos/navCentral/umami/node_modules/@prisma/client/runtime/library.js:117:8972)
    at Ro (/Users/hussain/Git_Repos/navCentral/umami/node_modules/@prisma/client/runtime/library.js:117:6801)
    at Ol (/Users/hussain/Git_Repos/navCentral/umami/node_modules/@prisma/client/runtime/library.js:117:6731)
    at /Users/hussain/Git_Repos/navCentral/umami/node_modules/@prisma/client/runtime/library.js:129:10548
    at Object.runInChildSpan (/Users/hussain/Git_Repos/navCentral/umami/node_modules/@prisma/client/runtime/library.js:124:1481)
    at t._executeRequest (/Users/hussain/Git_Repos/navCentral/umami/node_modules/@prisma/client/runtime/library.js:129:10527)
    at Ba (/Users/hussain/Git_Repos/navCentral/umami/node_modules/@prisma/client/runtime/library.js:34:5144)
    at l (/Users/hussain/Git_Repos/navCentral/umami/node_modules/@prisma/client/runtime/library.js:129:10029) {
  clientVersion: '5.6.0',
  page: '/api/send'
}
```

**Comment by MichaelBelgium** [comment]
Does it append a "Z" to the value automaticly somewhere?

I encountered this too, and while I just pass a number, there's a Z at the end somehow

> stringValue: "30Z",

Is it because it detects it as a date?

**Comment by PushHandle** [comment]
> Does it append a "Z" to the value automaticly somewhere?
> 
> I encountered this too, and while I just pass a number, there's a Z at the end somehow
> 
> > stringValue: "30Z",
> 
> Is it because it detects it as a date?

Experiencing the same here.

**Comment by RainyCodeWizard** [comment]
> Does it append a "Z" to the value automaticly somewhere?
> 
> I encountered this too, and while I just pass a number, there's a Z at the end somehow
> 
> > stringValue: "30Z",
> 
> Is it because it detects it as a date?



Yes, you're correct. The code utilizes parseISO() from date-fns to verify if a string can be converted into a date. This function considers strings that are solely integers, such as '30', as valid dates and subsequently appends a 'Z' to them to indicate UTC time. 

As a workaround, I've been appending a letter or word to the numeric string. For instance, changing '30' to '30d' prevents parseISO() from recognizing the string as a date, thereby avoiding the automatic addition of 'Z'.

Regarding the proposed solution, I cannot guarantee it will work flawlessly in every scenario. It's primarily aimed at addressing the discrepancy between the parseISO() and new Date() functions. By aligning the validation and parsing methods, we can eliminate the inconsistency issue.

Here is the code snippet for reference:

> ```
> // src/lib/data.ts
> 
> export function getDataType(value: any): string {
>   let type: string = typeof value;
> 
>   if ((type === 'string' && isValid(value)) || isValid(new Date(value))) {
>     type = 'date';
>   }
> 
>   return type;
> }
> ```

**Comment by mikecao** [comment]
Hey everyone, a fix has been pushed to cloud. It should handle numeric values correctly now. The fix will go out in the new release this week.
