### ISSUE TITLE
When upgrading from version 2.9.0 to 2.10.1 using Docker deployment, a strange error occurred. 

### ISSUE THREAD

**Issue by tippytea** [umami-software/umami#2561]
### Describe the Bug

Following the official instructions for the upgrade, I ran "docker compose pull" and "docker compose up --force-recreate". After the upgrade, when accessing the default /dashboard page in the background, it still showed version 2.9.1, but when navigating to other pages, it showed version 2.10.1.

After clicking on another page and then returning to the /dashboard page, it would show version 2.10.1 and the new features would appear. However, upon refreshing the page, it would revert back to version 2.9.0 and the new features would disappear.

This cycle continued, sometimes showing 2.9.0 and other times 2.10.1. What could be the issue?

### Database

PostgreSQL

### Relevant log output

```shell
The provided value for the column is too long for the column's type. Column: (not available)
    at ai.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:126:6775)
    at ai.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:126:6109)
    at ai.request (/app/node_modules/@prisma/client/runtime/library.js:126:5817)
    at async l (/app/node_modules/@prisma/client/runtime/library.js:131:9709)
    at async h (/app/.next/server/pages/api/send.js:1:2851)
    at async K (/app/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16545)
    at async U.render (/app/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16981)
    at async NextNodeServer.runApi (/app/node_modules/next/dist/server/next-server.js:556:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/next/dist/server/next-server.js:268:37)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/next/dist/server/base-server.js:807:17) {
  code: 'P2000',
  clientVersion: '5.9.1',
  meta: { modelName: 'WebsiteEvent', column_name: '(not available)' }
}
PrismaClientKnownRequestError: 
Invalid `prisma.websiteEvent.create()` invocation:
```

### Which Umami version are you using? (if relevant)

2.9.0

### Which browser are you using? (if relevant)

Edge

### How are you deploying your application? (if relevant)

Docker

**Comment by franciscao633** [comment]
Sorry for late response. Is this still an issue after restarting the container and/or logging out? Wondering if you had Umami open while upgrading the image, which caused some issues. I don't really have a technical answer.

**Comment by tippytea** [comment]
I had previously tried clearing browser cookies and cache, restarting the container, and even rebooting the server, but none of it worked. However, today, just when I logged in to check the statistics, I found that all its pages are on the latest version 2.10.1 and its functionality is also correct. But within 24 hours of my posting, I tried countless times to clear the cache and various reboots, but it consistently showed the error I described. I don't know why it's now back to normal without any errors and working properly.

**Comment by TeachMeHowToUse2FA** [comment]
I can confirm this error: completely clean version - v2.10.2, running via docker-compose - in the logs I see that requests from clients to POST /api/send give 500, and in the service logs:

```
PrismaClientKnownRequestError:
Invalid `prisma.websiteEvent.create()` invocation:

The provided value for the column is too long for the column's type. Column: (not available)
    at ai.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:126:6775)
    at ai.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:126:6109)
    at ai.request (/app/node_modules/@prisma/client/runtime/library.js:126:5817)
    at async l (/app/node_modules/@prisma/client/runtime/library.js:131:9709)
    at async h (/app/.next/server/pages/api/send.js:1:2849)
    at async K (/app/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16545)
    at async U.render (/app/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16981)
    at async NextNodeServer.runApi (/app/node_modules/next/dist/server/next-server.js:556:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/next/dist/server/next-server.js:268:37)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/next/dist/server/base-server.js:807:17) {
    code: 'P2000',
    clientVersion: '5.9.1',
    meta: { modelName: 'WebsiteEvent', column_name: '(not available)' }
}
```

I note that requests from some clients pass - statistics are updated.

**Comment by mikecao** [comment]
@TeachMeHowToUse2FA It would help if you can include the posted data so we can troubleshoot

**Comment by TeachMeHowToUse2FA** [comment]
> @TeachMeHowToUse2FA It would help if you can include the posted data so we can troubleshoot

Uh, sure. I think I found the reason: I can't be sure for sure, but cursory tests have shown that the request crashes when the page title is of long length. My site has cyrillic fonts and on short titles it does fine - all long titles crash with an error.

![Снимок экрана 2024-03-08 в 23 16 33](https://github.com/umami-software/umami/assets/15131106/85c0f43a-393f-407b-b9ab-f41384431c44)
