### ISSUE TITLE
Website endpoint returns 500 after upgrading to 2.10.2

### ISSUE THREAD

**Issue by Big-Cake-jpg** [umami-software/umami#2613]
### Describe the Bug

After upgrading from 2.9.0 to 2.10.2, the website endpoint starts returning 500 error and causes the dashboard to be empty.
![image](https://github.com/umami-software/umami/assets/76810494/3cff54d8-01d4-476c-8722-58d753d1ce9e)
After rolling back to 2.9.0, nothing will happen.
![image](https://github.com/umami-software/umami/assets/76810494/8a3abac6-e6c7-4dea-9bd8-c1c303b0969f)

### Database

MySQL

### Relevant log output

```shell
t database.
    at ai.handleRequestError (/var/task/node_modules/@prisma/client/runtime/library.js:126:6775)
    at ai.handleAndLogRequestError (/var/task/node_modules/@prisma/client/runtime/library.js:126:6109)
    at ai.request (/var/task/node_modules/@prisma/client/runtime/library.js:126:5817)
    at async l (/var/task/node_modules/@prisma/client/runtime/library.js:131:9709)
    at async Object._ [as pagedQuery] (/var/task/.next/server/chunks/6688.js:1:18567)
    at async m (/var/task/.next/server/pages/api/users/[userId]/teams.js:1:2083)
    at async K (/var/task/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16545)
    at async U.render (/var/task/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16981)
    at async r3.runApi (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:17:41752)
    at async r3.handleCatchallRenderRequest (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:17:36452) {
  code: 'P2022',
  clientVersion: '5.9.1',
  meta: { modelName: 'Team', column: 'umami.website.team_id' }
}
 ⨯ PrismaClientKnownRequestError: 
Invalid `prisma.team.findMany()` invocation:


The column `umami.website.team_id` does not exist in the current database.
    at ai.handleRequestError (/var/task/node_modules/@prisma/client/runtime/library.js:126:6775)
    at ai.handleAndLogRequestError (/var/task/node_modules/@prisma/client/runtime/library.js:126:6109)
    at ai.request (/var/task/node_modules/@prisma/client/runtime/library.js:126:5817)
    at async l (/var/task/node_modules/@prisma/client/runtime/library.js:131:9709)
    at async Object._ [as pagedQuery] (/var/task/.next/server/chunks/6688.js:1:18567)
    at async m (/var/task/.next/server/pages/api/users/[userId]/teams.js:1:2083)
    at async K (/var/task/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16545)
    at async U.render (/var/task/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16981)
    at async r3.runApi (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:17:41752)
    at async r3.handleCatchallRenderRequest (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:17:36452) {
  code: 'P2022',
  clientVersion: '5.9.1',
  meta: { modelName: 'Team', column: 'umami.website.team_id' }
}
PrismaClientKnownRequestError: 
Invalid `prisma.team.findMany()` invocation:


The column `umami.website.team_id` does not exist in the current database.
    at ai.handleRequestError (/var/task/node_modules/@prisma/client/runtime/library.js:126:6775)
    at ai.handleAndLogRequestError (/var/task/node_modules/@prisma/client/runtime/library.js:126:6109)
    at ai.request (/var/task/node_modules/@prisma/client/runtime/library.js:126:5817)
    at async l (/var/task/node_modules/@prisma/client/runtime/library.js:131:9709)
    at async Object._ [as pagedQuery] (/var/task/.next/server/chunks/6688.js:1:18567)
    at async m (/var/task/.next/server/pages/api/users/[userId]/teams.js:1:2083)
    at async K (/var/task/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16545)
    at async U.render (/var/task/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16981)
    at async r3.runApi (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:17:41752)
    at async r3.handleCatchallRenderRequest (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:17:36452) {
  code: 'P2022',
  clientVersion: '5.9.1',
  meta: { modelName: 'Team', column: 'umami.website.team_id' }
}
Error: Runtime exited with error: exit status 1
```

### Which Umami version are you using? (if relevant)

2.10.2

### Which browser are you using? (if relevant)

Chrome Canary

### How are you deploying your application? (if relevant)

Vercel & TiDB Serverless

**Comment by Big-Cake-jpg** [comment]
The problem was caused by several missing columns in the table `website` and `team`. After manually added these missing columns via Navicat, the problem disappeared.
Maybe we need a check or something that fixes the problem?

**Comment by franciscao633** [comment]
That's odd. Prisma should take care of all the migrations for you. Do you have a record named `04_team_redesign` in your `_prisma_migrations` table?

**Comment by Big-Cake-jpg** [comment]
> That's odd. Prisma should take care of all the migrations for you. Do you have a record named `04_team_redesign` in your `_prisma_migrations` table?

Seems not. I don't see that record mentioned by you in `_prisma_migrations`.
![image](https://github.com/umami-software/umami/assets/76810494/07135c06-31b6-4714-a59c-00b7d39f8196)
