### ISSUE TITLE
Inconsistent query result: Field user is required to return data, got `null` instead

### ISSUE THREAD

**Issue by manuel-rw** [umami-software/umami#2625]
### Describe the Bug

Users are unable to access the teams page. The following error message appears:
![image](https://github.com/umami-software/umami/assets/30572287/cdf2aca8-f4b0-4b42-a76a-07f946c9abcd)

It seems that database migrations may not have been applied.
We do see other errors as well hinting that some website events aren't being inserted.
This instance has been running for months and we have not tampered with the database or Umami itself.

### Database

PostgreSQL

### Relevant log output

```shell
PrismaClientUnknownRequestError: 
Invalid `prisma.team.findMany()` invocation:
Inconsistent query result: Field user is required to return data, got `null` instead.
    at ai.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:126:6965)
    at ai.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:126:6109)
    at ai.request (/app/node_modules/@prisma/client/runtime/library.js:126:5817)
    at async l (/app/node_modules/@prisma/client/runtime/library.js:131:9709)
    at async Object._ [as pagedQuery] (/app/.next/server/chunks/6688.js:1:18567)
    at async m (/app/.next/server/pages/api/users/[userId]/teams.js:1:2083)
    at async K (/app/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16545)
    at async U.render (/app/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16981)
    at async NextNodeServer.runApi (/app/node_modules/next/dist/server/next-server.js:556:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/next/dist/server/next-server.js:268:37) {
  clientVersion: '5.9.1'
}
```

### Which Umami version are you using? (if relevant)

v2.10.2

### Which browser are you using? (if relevant)

Firefox

### How are you deploying your application? (if relevant)

Docker

**Comment by franciscao633** [comment]
Are you able to query your _prisma_migrations table in your db and show me the results? I wonder if its similar to #2613, where the migrations are not being run. It should auto-run as part of the `yarn build` step.

**Comment by manuel-rw** [comment]
pgadmin dump of the ``_prisma_migrations`` table (I removed some confidential data with ``X``):

```sql
--
-- PostgreSQL database dump
--

-- Dumped from database version 12.18
-- Dumped by pg_dump version 12.18

-- Started on 2024-03-26 17:20:30 UTC

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 203 (class 1259 OID 16385)
-- Name: _prisma_migrations; Type: TABLE; Schema: public; Owner: XXXXXXXXXXXXXXXXXXXXXX
--

CREATE TABLE public._prisma_migrations (
    id character varying(36) NOT NULL,
    checksum character varying(64) NOT NULL,
    finished_at timestamp with time zone,
    migration_name character varying(255) NOT NULL,
    logs text,
    rolled_back_at timestamp with time zone,
    started_at timestamp with time zone DEFAULT now() NOT NULL,
    applied_steps_count integer DEFAULT 0 NOT NULL
);


ALTER TABLE public._prisma_migrations OWNER TO XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX;

--
-- TOC entry 3092 (class 0 OID 16385)
-- Dependencies: 203
-- Data for Name: _prisma_migrations; Type: TABLE DATA; Schema: public; Owner: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
--

COPY public._prisma_migrations (id, checksum, finished_at, migration_name, logs, rolled_back_at, started_at, applied_steps_count) FROM stdin;
361897ac-5d80-4978-9b8d-8a98a1e80637	65f0f9ee4a3b432e7fa917795033254887497a849d95acf7d9cb4ff24b45f98f	2024-02-10 12:15:36.749292+00	01_init	\N	\N	2024-02-10 12:15:36.31746+00	1
0154bb67-d3b3-4637-b280-d6b72160609d	4cc3c14482cb8700574cbdbdb478a93ccd1cabb0aeed37dfffb77a80278ce575	2024-02-10 12:15:36.890073+00	02_report_schema_session_data	\N	\N	2024-02-10 12:15:36.754538+00	1
0065eae6-ee17-437f-928b-e50f941b1329	baf86a7adc077bc46ea646d86aabc5f613aeb311e63894366979a18f6a9ca48c	2024-02-10 12:15:37.050036+00	03_metric_performance_index	\N	\N	2024-02-10 12:15:36.895167+00	1
d21e8469-938c-49b2-a530-b7ce393adf55	65f0f9ee4a3b432e7fa917795033254887497a849d95acf7d9cb4ff24b45f98f	2023-10-24 09:25:42.831224+00	01_init	\N	\N	2023-10-24 09:25:42.642762+00	1
874c6386-748f-41b0-b210-e7e2c37b6852	4cc3c14482cb8700574cbdbdb478a93ccd1cabb0aeed37dfffb77a80278ce575	2023-10-24 09:25:42.95518+00	02_report_schema_session_data	\N	\N	2023-10-24 09:25:42.835992+00	1
2128647f-03d1-4bbf-8c8b-be8fa7689699	baf86a7adc077bc46ea646d86aabc5f613aeb311e63894366979a18f6a9ca48c	2023-10-24 09:25:43.065813+00	03_metric_performance_index	\N	\N	2023-10-24 09:25:42.962151+00	1
70e98771-5143-4f1c-b4cd-daa6d8062f3c	eb0e4ae2ef5204bc67ddb248358a402cd3bd88567d710f808f16c5124e5fd9cb	2024-03-23 10:24:56.474876+00	04_team_redesign	\N	\N	2024-03-23 10:24:56.450391+00	1
\.


--
-- TOC entry 2965 (class 2606 OID 16394)
-- Name: _prisma_migrations _prisma_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: XXXXXXXXXXXXX
--

ALTER TABLE ONLY public._prisma_migrations
    ADD CONSTRAINT _prisma_migrations_pkey PRIMARY KEY (id);


-- Completed on 2024-03-26 17:20:30 UTC

--
-- PostgreSQL database dump complete
--


```

**Comment by franciscao633** [comment]
Not sure why you have duplicate records on 10/24/23 and 2/10/24, but it looks like the teams migration did run on 3/23. Something seems out of sync. Do you see the new teams dropdown in the top nav?

![image](https://github.com/umami-software/umami/assets/31608805/29d45f3e-fc9f-4320-a5d1-8981774e46ad)

**Comment by manuel-rw** [comment]
I do not see that drop-down. There is a new update but I haven't updated yet - I'm currently on holidays.

**Comment by manuel-rw** [comment]
Updated the image. I'm now getting
```
yarn run v1.22.19
$ npm-run-all check-db update-tracker start-server
$ node scripts/check-db.js
✓ DATABASE_URL is defined.
✓ Database connection successful.
✓ Database version check successful.

```

**Comment by manuel-rw** [comment]
@franciscao633 any update? Is there a possibility to start over but migrate at least the data so I don't loose all data?
