### ISSUE TITLE
Upgrade error: unhandledRejection Error: Cannot find module './blocks/images'

### ISSUE THREAD

**Issue by h0ek** [umami-software/umami#2639]
### Describe the Bug

I wanted to upgrade my self-hosted Umami instance as always, so I followed the steps from the instructions as always https://umami.is/docs/updates (in the past it was smooth and quick action on each update)
git pull
yarn install
yarn build -> and during build phase I got error

any ideas what the issue and how to solve it?

### Database

MySQL

### Relevant log output

```shell
...
$ next build
unhandledRejection Error: Cannot find module './blocks/images'
Require stack:
- /opt/umami/node_modules/next/dist/build/webpack/config/index.js
- /opt/umami/node_modules/next/dist/build/webpack-config.js
- /opt/umami/node_modules/next/dist/build/webpack/plugins/next-trace-entrypoints-plugin.js
- /opt/umami/node_modules/next/dist/build/collect-build-traces.js
- /opt/umami/node_modules/next/dist/build/index.js
- /opt/umami/node_modules/next/dist/cli/next-build.js
- /opt/umami/node_modules/next/dist/lib/commands.js
- /opt/umami/node_modules/next/dist/bin/next
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at /opt/umami/node_modules/next/dist/server/require-hook.js:55:36
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at mod.require (/opt/umami/node_modules/next/dist/server/require-hook.js:65:28)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/opt/umami/node_modules/next/dist/build/webpack/config/index.js:13:17)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/umami/node_modules/next/dist/build/webpack/config/index.js',
    '/opt/umami/node_modules/next/dist/build/webpack-config.js',
    '/opt/umami/node_modules/next/dist/build/webpack/plugins/next-trace-entrypoints-plugin.js',
    '/opt/umami/node_modules/next/dist/build/collect-build-traces.js',
    '/opt/umami/node_modules/next/dist/build/index.js',
    '/opt/umami/node_modules/next/dist/cli/next-build.js',
    '/opt/umami/node_modules/next/dist/lib/commands.js',
    '/opt/umami/node_modules/next/dist/bin/next'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "build-app" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Which Umami version are you using? (if relevant)

it was 2.10.0 or 2.10.1 and I was updating to the latest

### Which browser are you using? (if relevant)

Brave

### How are you deploying your application? (if relevant)

Selhosted, from the source, github.

**Comment by franciscao633** [comment]
Looks like a solution was posted [here](https://github.com/vercel/next.js/discussions/30519#discussioncomment-1556021). The post underneath it looks like the same error.
