### ISSUE TITLE
Loading of website details fails (on Edge Desktop)

### ISSUE THREAD

**Issue by bigbasti** [umami-software/umami#2832]
### Describe the Bug

I have installed umami using docker-compose on my server.
i have changed nothing in the configuration exept of the server port.

Server is up and running and counting visits. But today (after running for <24h) i can't open the website details on desktop Edge anymore (see below) - while opening the details on mobile or Desktop FireFox is no problem.

Steps: 
1. Open Dashboard
2. Click on "View Details" on the right

The UI shows the following error:

```
Something went wrong.
Cannot read properties of undefined (reading 'length')
TypeError: Cannot read properties of undefined (reading 'length')
    at L (https://stats.ultimate-holdem-timer.com/_next/static/chunks/1303-ec403c9dcaa0aa7f.js:1:10962)
    at https://stats.ultimate-holdem-timer.com/_next/static/chunks/1303-ec403c9dcaa0aa7f.js:1:11469
    at aW (https://stats.ultimate-holdem-timer.com/_next/static/chunks/fd9d1056-32e91c42f6a1484e.js:1:73244)
    ...
```

Clicking "OK" seems to reload the page and the error reappears.

The Browser console shows some errors:

```
Uncaught (in promise) TypeError: Failed to fetch
    at b (layout-9b3450ae0aaea4de.js:1:622)
    at layout-9b3450ae0aaea4de.js:1:1390
    at aW (fd9d1056-32e91c42f6a1484e.js:1:73244)
    ...
```

```
Failed to fetch RSC payload for https://stats.ultimate-holdem-timer.com/websites/cd56a5e1-a0ff-4b85-9caf-d5033e87cc10/event-data. Falling back to browser navigation. TypeError: Failed to fetch
    at s (7023-18fd8c89352dead8.js:1:45403)
    at 7023-18fd8c89352dead8.js:1:58952
    at Object.u [as task] (7023-18fd8c89352dead8.js:1:31790)
    at c.s (7023-18fd8c89352dead8.js:1:32495)
    at c.enqueue (7023-18fd8c89352dead8.js:1:31920)
    at s (7023-18fd8c89352dead8.js:1:58915)
    at i (7023-18fd8c89352dead8.js:1:58455)
    at a (7023-18fd8c89352dead8.js:1:65275)
    at f (7023-18fd8c89352dead8.js:1:75102)
    at Object.action (7023-18fd8c89352dead8.js:2:7102)
```

```
TypeError: Cannot read properties of undefined (reading 'length')
    at L (1303-ec403c9dcaa0aa7f.js:1:10962)
    at 1303-ec403c9dcaa0aa7f.js:1:11469
    at aW (fd9d1056-32e91c42f6a1484e.js:1:73244)
    at oe (fd9d1056-32e91c42f6a1484e.js:1:84685)
    at ol (fd9d1056-32e91c42f6a1484e.js:1:85323)
    at or (fd9d1056-32e91c42f6a1484e.js:1:85207)
    ...
```

If i select a different time frame before clicking "View details" the error does not show and everything works. Error only seems to occure when time frame is set to "Last 24 hours" Maybe a bug in the calculation since my instance has not been running for 24 yet?

### Database

PostgreSQL

### Relevant log output

```shell
TypeError: Cannot read properties of undefined (reading 'length')
    at L (1303-ec403c9dcaa0aa7f.js:1:10962)
    at 1303-ec403c9dcaa0aa7f.js:1:11469
    at aW (fd9d1056-32e91c42f6a1484e.js:1:73244)
    at oe (fd9d1056-32e91c42f6a1484e.js:1:84685)
    at ol (fd9d1056-32e91c42f6a1484e.js:1:85323)
    at or (fd9d1056-32e91c42f6a1484e.js:1:85207)
    at ol (fd9d1056-32e91c42f6a1484e.js:1:85303)
    at or (fd9d1056-32e91c42f6a1484e.js:1:85207)
    at ol (fd9d1056-32e91c42f6a1484e.js:1:85303)
    at or (fd9d1056-32e91c42f6a1484e.js:1:85207) '\n    at b (https://stats.ultimate-holdem-timer.com/_next/static/chunks/1303-ec403c9dcaa0aa7f.js:1:10399)\n    at p (https://stats.ultimate-holdem-timer.com/_next/static/chunks/1303-ec403c9dcaa0aa7f.js:1:9085)\n    at r.Z (https://stats.ultimate-holdem-timer.com/_next/static/chunks/app/(main)/websites/%5BwebsiteId%5D/page-54d87e4a03e08b05.js:1:3940)\n    at div\n    at div\n    at u (https://stats.ultimate-holdem-timer.com/_next/static/chunks/9583-ab9d50589ec3f414.js:1:2470)\n    at div\n    at o (https://stats.ultimate-holdem-timer.com/_next/static/chunks/9583-ab9d50589ec3f414.js:1:2350)\n    at M (https://stats.ultimate-holdem-timer.com/_next/static/chunks/app/(main)/websites/%5BwebsiteId%5D/page-54d87e4a03e08b05.js:1:2801)\n    at t.ZP (https://stats.ultimate-holdem-timer.com/_next/static/chunks/9583-ab9d50589ec3f414.js:1:629)\n    at R (https://stats.ultimate-holdem-timer.com/_next/static/chunks/app/(main)/websites/%5BwebsiteId%5D/page-54d87e4a03e08b05.js:1:3345)\n    at j (https://stats.ultimate-holdem-timer.com/_next/static/chunks/7023-18fd8c89352dead8.js:1:22780)\n    at c (https://stats.ultimate-holdem-timer.com/_next/static/chunks/7023-18fd8c89352dead8.js:1:33641)\n    at s (https://stats.ultimate-holdem-timer.com/_next/static/chunks/7023-18fd8c89352dead8.js:1:33723)\n    at s (https://stats.ultimate-holdem-timer.com/_next/static/chunks/7023-18fd8c89352dead8.js:1:30340)\n    at O (https://stats.ultimate-holdem-timer.com/_next/static/chunks/7023-18fd8c89352dead8.js:1:24122)\n    at h (https://stats.ultimate-holdem-timer.com/_next/static/chunks/7023-18fd8c89352dead8.js:1:19190)\n    at R (https://stats.ultimate-holdem-timer.com/_next/static/chunks/7023-18fd8c89352dead8.js:1:21511)\n    at P (https://stats.ultimate-holdem-timer.com/_next/static/chunks/7023-18fd8c89352dead8.js:1:22532)\n    at a (https://stats.ultimate-holdem-timer.com/_next/static/chunks/7023-18fd8c89352dead8.js:1:36677)\n    at S (https://stats.ultimate-holdem-timer.com/_next/static/chunks/7023-18fd8c89352dead8.js:1:24349)\n    at j (https://stats.ultimate-holdem-timer.com/_next/static/chunks/7023-18fd8c89352dead8.js:1:22780)\n    at c (https://stats.ultimate-holdem-timer.com/_next/static/chunks/7023-18fd8c89352dead8.js:1:33641)\n    at s (https://stats.ultimate-holdem-timer.com/_next/static/chunks/7023-18fd8c89352dead8.js:1:33723)\n    at s (https://stats.ultimate-holdem-timer.com/_next/static/chunks/7023-18fd8c89352dead8.js:1:30340)\n    at O (https://stats.ultimate-holdem-timer.com/_next/static/chunks/7023-18fd8c89352dead8.js:1:24122)\n    at h (https://stats.ultimate-holdem-timer.com/_next/static/chunks/7023-18fd8c89352dead8.js:1:19190)\n    at R (https://stats.ultimate-holdem-timer.com/_next/static/chunks/7023-18fd8c89352dead8.js:1:21511)\n    at P (https://stats.ultimate-holdem-timer.com/_next/static/chunks/7023-18fd8c89352dead8.js:1:22532)\n    at a (https://stats.ultimate-holdem-timer.com/_next/static/chunks/7023-18fd8c89352dead8.js:1:36677)\n    at S (https://stats.ultimate-holdem-timer.com/_next/static/chunks/7023-18fd8c89352dead8.js:1:24349)\n    at j (https://stats.ultimate-holdem-timer.com/_next/static/chunks/7023-18fd8c89352dead8.js:1:22780)\n    at c (https://stats.ultimate-holdem-timer.com/_next/static/chunks/7023-18fd8c89352dead8.js:1:33641)\n    at s (https://stats.ultimate-holdem-timer.com/_next/static/chunks/7023-18fd8c89352dead8.js:1:33723)\n    at s (https://stats.ultimate-holdem-timer.com/_next/static/chunks/7023-18fd8c89352dead8.js:1:30340)\n    at O (https://stats.ultimate-holdem-timer.com/_next/static/chunks/7023-18fd8c89352dead8.js:1:24122)\n    at h (https://stats.ultimate-holdem-timer.com/_next/static/chunks/7023-18fd8c89352dead8.js:1:19190)\n    at R (https://stats.ultimate-holdem-timer.com/_next/static/chunks/7023-18fd8c89352dead8.js:1:21511)\n    at P (https://stats.ultimate-holdem-timer.com/_next/static/chunks/7023-18fd8c89352dead8.js:1:22532)\n    at a (https://stats.ultimate-holdem-timer.com/_next/static/chunks/7023-18fd8c89352dead8.js:1:36677)\n    at S (https://stats.ultimate-holdem-timer.com/_next/static/chunks/7023-18fd8c89352dead8.js:1:24349)\n    at div\n    at n.default (https://stats.ultimate-holdem-timer.com/_next/static/chunks/app/(main)/layout-9b3450ae0aaea4de.js:1:8942)\n    at section\n    at main\n    at y (https://stats.ultimate-holdem-timer.com/_next/static/chunks/app/(main)/layout-9b3450ae0aaea4de.js:1:1873)\n    at j (https://stats.ultimate-holdem-timer.com/_next/static/chunks/7023-18fd8c89352dead8.js:1:22780)\n    at c (https://stats.ultimate-holdem-timer.com/_next/static/chunks/7023-18fd8c89352dead8.js:1:33641)\n    at s (https://stats.ultimate-holdem-timer.com/_next/static/chunks/7023-18fd8c89352dead8.js:1:33723)\n    at c (https://stats.ultimate-holdem-timer.com/_next/static/chunks/7023-18fd8c89352dead8.js:1:30229)\n    at s (https://stats.ultimate-holdem-timer.com/_next/static/chunks/7023-18fd8c89352dead8.js:1:30340)\n    at O (https://stats.ultimate-holdem-timer.com/_next/static/chunks/7023-18fd8c89352dead8.js:1:24122)\n    at h (https://stats.ultimate-holdem-timer.com/_next/static/chunks/7023-18fd8c89352dead8.js:1:19190)\n    at R (https://stats.ultimate-holdem-timer.com/_next/static/chunks/7023-18fd8c89352dead8.js:1:21511)\n    at P (https://stats.ultimate-holdem-timer.com/_next/static/chunks/7023-18fd8c89352dead8.js:1:22532)\n    at a (https://stats.ultimate-holdem-timer.com/_next/static/chunks/7023-18fd8c89352dead8.js:1:36677)\n    at S (https://stats.ultimate-holdem-timer.com/_next/static/chunks/7023-18fd8c89352dead8.js:1:24349)\n    at o (https://stats.ultimate-holdem-timer.com/_next/static/chunks/9273-c77789adbef73957.js:1:2729)\n    at f (https://stats.ultimate-holdem-timer.com/_next/static/chunks/app/layout-ee4a7966e09a28eb.js:1:696)\n    at ny (https://stats.ultimate-holdem-timer.com/_next/static/chunks/6dfc6103-c33563486ef16c0a.js:1:62597)\n    at u (https://stats.ultimate-holdem-timer.com/_next/static/chunks/8805-30d19cce27b0db41.js:24:36676)\n    at e (https://stats.ultimate-holdem-timer.com/_next/static/chunks/9273-c77789adbef73957.js:1:13108)\n    at v (https://stats.ultimate-holdem-timer.com/_next/static/chunks/app/layout-ee4a7966e09a28eb.js:1:1193)\n    at x (https://stats.ultimate-holdem-timer.com/_next/static/chunks/app/layout-ee4a7966e09a28eb.js:1:1466)\n    at body\n    at html\n    at c (https://stats.ultimate-holdem-timer.com/_next/static/chunks/7023-18fd8c89352dead8.js:1:33641)\n    at s (https://stats.ultimate-holdem-timer.com/_next/static/chunks/7023-18fd8c89352dead8.js:1:33723)\n    at D (https://stats.ultimate-holdem-timer.com/_next/static/chunks/7023-18fd8c89352dead8.js:1:10893)\n    at f (https://stats.ultimate-holdem-timer.com/_next/static/chunks/7023-18fd8c89352dead8.js:1:18523)\n    at h (https://stats.ultimate-holdem-timer.com/_next/static/chunks/7023-18fd8c89352dead8.js:1:19190)\n    at I (https://stats.ultimate-holdem-timer.com/_next/static/chunks/7023-18fd8c89352dead8.js:1:15645)\n    at w (https://stats.ultimate-holdem-timer.com/_next/static/chunks/7023-18fd8c89352dead8.js:1:4744)\n    at M (https://stats.ultimate-holdem-timer.com/_next/static/chunks/7023-18fd8c89352dead8.js:1:4800)'
```

### Which Umami version are you using? (if relevant)

2.12.1

### Which browser are you using? (if relevant)

Edge 126.0.2592.87

### How are you deploying your application? (if relevant)

Docker

**Comment by mikecao** [comment]
Try disabling your adblock.

**Comment by jaasonw** [comment]
Disabling adblock worked for me

It looks like ublock origin triggered on my umami instance because it had the word analytics and event in it
![image](https://github.com/umami-software/umami/assets/8981287/c547f120-7da4-4963-a567-42f710889f1c)

It also blocked the following endpoints from umami.is, although I'm not sure if these would have an effect on page load
![image](https://github.com/umami-software/umami/assets/8981287/151987db-577a-4ede-9c98-efe0bad65fda)

**Comment by bigbasti** [comment]
Disabling AdBlock solved the problem.

thanks for the help!

Maybe this information should be placed more prominently in the docs (at least i did not stumble over this information)?

**Comment by pReya** [comment]
Same here. I'm not sure which of the mentioned requests triggers the error in the UI. But it would be very nice, if the site would not crash, even if these requests are blocked. In my understanding, none of these requests are necessary for Umami to work properly, right?!

It would be wonderful, if we could keep using Umami WITHOUT disabling Adblockers.

**Comment by veitw** [comment]
Firefox with uBlock Origin enabled has the same problem, umami is not even visible after clicking the details link as the website completely fills with next errors. Disabling uBlock Origin makes it work again.
