### ISSUE TITLE
Websites details crash

### ISSUE THREAD

**Issue by sepiropht** [umami-software/umami#2849]
### Describe the Bug

When i go to  websites details after i clicked the button 'view details', the web app crash
The bug don't show on mobile.

I tried to debug myself but i don't have the  don't when i build and run on my local machine. 

### Database

PostgreSQL

### Relevant log output

```shell
Something went wrong.
Cannot read properties of undefined (reading 'length')
TypeError: Cannot read properties of undefined (reading 'length')
    at L (https://analytics.sepiropht.me/_next/static/chunks/1303-ec403c9dcaa0aa7f.js:1:10962)
    at https://analytics.sepiropht.me/_next/static/chunks/1303-ec403c9dcaa0aa7f.js:1:11469
    at aW (https://analytics.sepiropht.me/_next/static/chunks/fd9d1056-32e91c42f6a1484e.js:1:73244)
    at oe (https://analytics.sepiropht.me/_next/static/chunks/fd9d1056-32e91c42f6a1484e.js:1:84685)
    at ol (https://analytics.sepiropht.me/_next/static/chunks/fd9d1056-32e91c42f6a1484e.js:1:85323)
    at or (https://analytics.sepiropht.me/_next/static/chunks/fd9d1056-32e91c42f6a1484e.js:1:85207)
    at ol (https://analytics.sepiropht.me/_next/static/chunks/fd9d1056-32e91c42f6a1484e.js:1:85303)
    at or (https://analytics.sepiropht.me/_next/static/chunks/fd9d1056-32e91c42f6a1484e.js:1:85207)
    at ol (https://analytics.sepiropht.me/_next/static/chunks/fd9d1056-32e91c42f6a1484e.js:1:85303)
    at or (https://analytics.sepiropht.me/_next/static/chunks/fd9d1056-32e91c42f6a1484e.js:1:85207)
```

### Which Umami version are you using? (if relevant)

The last master update

### Which browser are you using? (if relevant)

chromium

### How are you deploying your application? (if relevant)

vercel

**Comment by sepiropht** [comment]
Disable u-block solve the issue
