### ISSUE TITLE
Unable to reset statistics and delete sites

### ISSUE THREAD

**Issue by God-2077** [umami-software/umami#2877]
### Describe the Bug

Unable to reset statistics and delete sites

Tip `Internal Server Error` Error

I changed the website icon api before this, but I don't think it has anything to do with this error

Changed `https://icons.duckduckgo.com/ip3/${hostName}.ico` to `https://www.favicon.vip/get.php?url=${hostName}`

![屏幕截图 2024-08-08 194825](https://github.com/user-attachments/assets/f3d74c1c-f0fc-48a6-b1af-676d7f83c1aa)
![屏幕截图 2024-08-08 194730](https://github.com/user-attachments/assets/75c1a0ff-f668-4ec2-9c6b-cec063e48e7f)

### Database

PostgreSQL

### Relevant log output

```shell
consoles logs
---
api.umami.is/v1/updates?v=2.12.1:1 
        
        
        Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
layout-3c6d9626bb7c5cb1.js:1 
        
        
        Uncaught (in promise) TypeError: Failed to fetch
    at b (layout-3c6d9626bb7c5cb1.js:1:622)
    at layout-3c6d9626bb7c5cb1.js:1:1390
    at aW (fd9d1056-32e91c42f6a1484e.js:1:73244)
    at oe (fd9d1056-32e91c42f6a1484e.js:1:84685)
    at ol (fd9d1056-32e91c42f6a1484e.js:1:85323)
    at or (fd9d1056-32e91c42f6a1484e.js:1:85207)
    at ol (fd9d1056-32e91c42f6a1484e.js:1:85303)
    at or (fd9d1056-32e91c42f6a1484e.js:1:85207)
    at ol (fd9d1056-32e91c42f6a1484e.js:1:86268)
    at or (fd9d1056-32e91c42f6a1484e.js:1:85207)
a.png:1 
        
        
        Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
5686-a2a6f3f9292b270f.js:6 
        
        
        DELETE https://mywebsite/api/websites/a7a1bb6a-591a-4366-a702-cb45380c13ec 500 (Internal Server Error)
(匿名) @ 5686-a2a6f3f9292b270f.js:6
(匿名) @ 5686-a2a6f3f9292b270f.js:6
(匿名) @ 5686-a2a6f3f9292b270f.js:6
(匿名) @ 5686-a2a6f3f9292b270f.js:6
G @ 5686-a2a6f3f9292b270f.js:6
X @ 5686-a2a6f3f9292b270f.js:6
K @ 5686-a2a6f3f9292b270f.js:6
(匿名) @ 5686-a2a6f3f9292b270f.js:6
(匿名) @ 5686-a2a6f3f9292b270f.js:6
(匿名) @ 5686-a2a6f3f9292b270f.js:6
(匿名) @ 5686-a2a6f3f9292b270f.js:6
G @ 5686-a2a6f3f9292b270f.js:6
(匿名) @ 5686-a2a6f3f9292b270f.js:6
mutationFn @ 2335-32553f177f1f2f0d.js:9
fn @ 8805-30d19cce27b0db41.js:24
y @ 8805-30d19cce27b0db41.js:24
start @ 8805-30d19cce27b0db41.js:24
execute @ 8805-30d19cce27b0db41.js:24
await in execute
mutate @ 8805-30d19cce27b0db41.js:24
(匿名) @ 8805-30d19cce27b0db41.js:24
x @ 2335-32553f177f1f2f0d.js:9
(匿名) @ 6dfc6103-c33563486ef16c0a.js:1
await in (匿名)
a_ @ fd9d1056-32e91c42f6a1484e.js:1
aR @ fd9d1056-32e91c42f6a1484e.js:1
(匿名) @ fd9d1056-32e91c42f6a1484e.js:1
sF @ fd9d1056-32e91c42f6a1484e.js:1
sM @ fd9d1056-32e91c42f6a1484e.js:1
(匿名) @ fd9d1056-32e91c42f6a1484e.js:1
o4 @ fd9d1056-32e91c42f6a1484e.js:1
iV @ fd9d1056-32e91c42f6a1484e.js:1
sU @ fd9d1056-32e91c42f6a1484e.js:1
uR @ fd9d1056-32e91c42f6a1484e.js:1
uM @ fd9d1056-32e91c42f6a1484e.js:1
```

### Which Umami version are you using? (if relevant)

v2.12.1

### Which browser are you using? (if relevant)

Edge

### How are you deploying your application? (if relevant)

netlify

**Comment by tomastaker** [comment]
Disable ublock, bro)

**Comment by God-2077** [comment]
> Disable ublock, bro)

None of its business, I delete other sites successfully.

**Comment by God-2077** [comment]
This bug shouldn't be easy to reproduce because I deleted several websites and it's the only one with the problem.

**Comment by tomastaker** [comment]
The weirdest thing is that I was getting similar errors, only when blocking certain scripts from ublock
