### ISSUE TITLE
Database error on upgrade: umami.BIN_TO_UUID does not exist

### ISSUE THREAD

**Issue by teledyn** [umami-software/umami#2882]
### Describe the Bug

I was following the README instructions to upgrade, I did the git pull followed by yarn install, but then the yarn build ended with the following:

✗ Command failed: prisma migrate deploy
Error: P3018

A migration failed to apply. New migrations cannot be applied before the error is recovered from. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve

Migration name: 05_add_visit_id

Database error code: 1305

Database error:
FUNCTION umami.BIN_TO_UUID does not exist

Please check the query number 2 from the migration file.

I have appended the umami error log, although the log does not emit timestamps so I have no idea how much of it applies to today's update vs what was there before.

### Database

MySQL

### Relevant log output

```shell
⚠ "next start" does not work with "output: standalone" configuration. Use "node .next/standalone/server.js" instead.
Error: Failed to find Server Action "null". This request might be from an older or newer deployment. Original error: Invariant: Missing 'next-action' header.
    at rv (/var/www/umami/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:1666)
    at /var/www/umami/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:15:7002
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at rg (/var/www/umami/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:15:6317)
    at rz (/var/www/umami/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:24715)
    at /var/www/umami/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:27397
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at Object.wrap (/var/www/umami/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:13:16207)
    at /var/www/umami/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:27287
    at AsyncLocalStorage.run (node:async_hooks:346:14)
 ⨯ Failed to start server
Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1897:16)
    at listenInCluster (node:net:1945:12)
    at Server.listen (node:net:2037:7)
    at /var/www/umami/node_modules/next/dist/server/lib/start-server.js:278:16
    at new Promise (<anonymous>)
    at startServer (/var/www/umami/node_modules/next/dist/server/lib/start-server.js:190:11)
    at nextStart (/var/www/umami/node_modules/next/dist/cli/next-start.js:50:40)
    at /var/www/umami/node_modules/next/dist/bin/next:155:54
    at async main (/var/www/umami/node_modules/next/dist/bin/next:155:5) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '::',
  port: 3000
}
error Command failed with exit code 1.
 ⚠ "next start" does not work with "output: standalone" configuration. Use "node .next/standalone/server.js" instead.
 ⚠ "next start" does not work with "output: standalone" configuration. Use "node .next/standalone/server.js" instead.
 ⚠ "next start" does not work with "output: standalone" configuration. Use "node .next/standalone/server.js" instead.
 ⚠ "next start" does not work with "output: standalone" configuration. Use "node .next/standalone/server.js" instead.
 ⚠ "next start" does not work with "output: standalone" configuration. Use "node .next/standalone/server.js" instead.
Error: Failed to find Server Action "null". This request might be from an older or newer deployment. Original error: Invariant: Missing 'next-action' header.
    at rv (/var/www/umami/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:1666)
    at /var/www/umami/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:15:7002
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at rg (/var/www/umami/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:15:6317)
    at rz (/var/www/umami/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:24715)
    at /var/www/umami/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:27397
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at Object.wrap (/var/www/umami/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:13:16207)
    at /var/www/umami/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:27287
    at AsyncLocalStorage.run (node:async_hooks:346:14)
 ⚠ "next start" does not work with "output: standalone" configuration. Use "node .next/standalone/server.js" instead.
warning You don't appear to have an internet connection. Try the --offline flag to use the cache for registry queries.
 ⚠ "next start" does not work with "output: standalone" configuration. Use "node .next/standalone/server.js" instead.
Error: Failed to find Server Action "null". This request might be from an older or newer deployment. Original error: Invariant: Missing 'next-action' header.
    at rv (/var/www/umami/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:1666)
    at /var/www/umami/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:15:7002
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at rg (/var/www/umami/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:15:6317)
    at rz (/var/www/umami/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:24715)
    at /var/www/umami/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:27397
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at Object.wrap (/var/www/umami/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:13:16207)
    at /var/www/umami/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:27287
    at AsyncLocalStorage.run (node:async_hooks:346:14)
 ⚠ "next start" does not work with "output: standalone" configuration. Use "node .next/standalone/server.js" instead.
 ⚠ "next start" does not work with "output: standalone" configuration. Use "node .next/standalone/server.js" instead.
 ⚠ "next start" does not work with "output: standalone" configuration. Use "node .next/standalone/server.js" instead.
```

### Which Umami version are you using? (if relevant)

2.10.2

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

installed from git src as per the README

**Comment by teledyn** [comment]
searching online suggests that there are db changes which were in conflict with the mysql table rules. where would I find the SQL statement that failed?

**Comment by teledyn** [comment]
I found them under db/mysql/migrations and this statement fails due to the missing function:
```
MariaDB [umami]> UPDATE `website_event` we
    -> JOIN (SELECT DISTINCT
    ->         s.session_id,
    ->         s.visit_time,
    ->         BIN_TO_UUID(RANDOM_BYTES(16) & 0xffffffffffff0fff3fffffffffffffff | 0x00000000000040008000000000000000) uuid
    ->     FROM (SELECT DISTINCT session_id,
    ->             DATE_FORMAT(created_at, '%Y-%m-%d %H:00:00') visit_time
    ->         FROM `website_event`) s) a
    ->     ON we.session_id = a.session_id and DATE_FORMAT(we.created_at, '%Y-%m-%d %H:00:00') = a.visit_time
    -> SET we.visit_id = a.uuid
    -> WHERE we.visit_id IS NULL;
ERROR 1305 (42000): FUNCTION umami.BIN_TO_UUID does not exist
```
I did find https://stackoverflow.com/questions/28251144/inserting-and-selecting-uuids-as-binary16 that provides a function of the same name, but this then fails with 
```
ERROR 1292 (22007): Truncated incorrect DECIMAL value: 'CtF$\x99G\xAD\x19\x18\x89\x19hX\xDE5\x1C'
```

**Comment by teledyn** [comment]
this appears to be a duplicate of https://github.com/umami-software/umami/issues/2693
