### ISSUE TITLE
Internal Server Error when I try to reset a site's data on a team transfered site.

### ISSUE THREAD

**Issue by dmonterde** [umami-software/umami#2967]
### Describe the Bug

Hi guys, I get an "Internal Server Error" when I try to reset a site's data.

This site was transferred to a computer, with sites added and not transferred the application works as expected.

![image](https://github.com/user-attachments/assets/4d8b1b7c-be68-4ddb-a767-0f09ffbd5d4e)

### Database

PostgreSQL

### Relevant log output

```shell
PrismaClientKnownRequestError: 
Invalid `prisma.session.deleteMany()` invocation:


The change you are trying to make would violate the required relation 'SessionToSessionData' between the `SessionData` and `Session` models.
    at _n.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:121:7749)
    at _n.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:121:7057)
    at _n.request (/app/node_modules/@prisma/client/runtime/library.js:121:6741)
    at async l (/app/node_modules/@prisma/client/runtime/library.js:130:9355) {
  code: 'P2014',
  clientVersion: '5.17.0',
  meta: {
    modelName: 'Session',
    relation_name: 'SessionToSessionData',
    model_a_name: 'SessionData',
    model_b_name: 'Session'
  }
}
```

### Which Umami version are you using? (if relevant)

umami:postgresql-latest

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Docker

**Comment by nandi95** [comment]
Has that fix been released? I am also getting the same error when trying to delete a website:
```
PrismaClientKnownRequestError: 
Invalid `prisma.session.deleteMany()` invocation:


The change you are trying to make would violate the required relation 'SessionToSessionData' between the `SessionData` and `Session` models.
    at _n.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:121:7749)
    at _n.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:121:7057)
    at _n.request (/app/node_modules/@prisma/client/runtime/library.js:121:6741)
    at async l (/app/node_modules/@prisma/client/runtime/library.js:130:9355) {
  code: 'P2014',
  clientVersion: '5.17.0',
  meta: {
    modelName: 'Session',
    relation_name: 'SessionToSessionData',
    model_a_name: 'SessionData',
    model_b_name: 'Session'
  }
}
```

**Comment by franciscao633** [comment]
The fix is currently in dev for self-hosted. We will do a release this week.
