### ISSUE TITLE
Map maximum size exceeded

### ISSUE THREAD

**Issue by VolanDeVovan** [umami-software/umami#2988]
### Describe the Bug

I use umami on a high traffic site
After a few days it stops working and spams with a message "**Map maximum size exceeded**"

This error was on older versions as well
It was not solved after updating to the current version

![Screenshot_20241002_164608](https://github.com/user-attachments/assets/db0c9345-3cce-41b2-bd5a-af768c2e3d61)

### Database

PostgreSQL

### Relevant log output

```shell
RangeError: Map maximum size exceeded
    at Map.set (<anonymous>)
    at /app/node_modules/next/dist/server/lib/trace/tracer.js:134:45
    at NoopContextManager.with (/app/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7062)
    at ContextAPI.with (/app/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:518)
    at NoopTracer.startActiveSpan (/app/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18093)
    at ProxyTracer.startActiveSpan (/app/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18854)
    at /app/node_modules/next/dist/server/lib/trace/tracer.js:122:103
    at NoopContextManager.with (/app/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7062)
    at ContextAPI.with (/app/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:518)
    at NextTracerImpl.trace (/app/node_modules/next/dist/server/lib/trace/tracer.js:122:28)
```

### Which Umami version are you using? (if relevant)

2.13.2

### How are you deploying your application? (if relevant)

docker

**Comment by mikecao** [comment]
Where is this error coming from, the tracker or the UI?

**Comment by VolanDeVovan** [comment]
> Where is this error coming from, the tracker or the UI?

I got it from the docker compose logs
so I think it's a server error
Also it stopped writing new data and processing requests

**Comment by mikecao** [comment]
The error seems to indicate it's coming from Next.js telemetry tracing. You can try disabling it.
