### ISSUE TITLE
/api/send responds with 500 due to invalid payload (websiteId field)

### ISSUE THREAD

**Issue by chimpdev** [umami-software/umami#3005]
### Describe the Bug

/api/send returns 500.

![image](https://github.com/user-attachments/assets/548f4dcb-3cef-417d-b60f-0a577dc8561a)
![image](https://github.com/user-attachments/assets/5888688a-4bab-4241-b2fb-58d50009ab1c)

https://github.com/discordplace/discord.place/blob/main/client/app/layout-content.js#L33-L38
https://github.com/discordplace/discord.place/blob/main/client/config.js#L53-L57

### Database

PostgreSQL

### Relevant log output

```shell
PrismaClientValidationError:

Invalid `prisma.websiteEvent.create()` invocation:

{

data: {

id: "57be1bb5-6b82-470b-8f90-9720921f71a8",

sessionId: undefined,

visitId: "40aad27f-0a86-5749-adce-8a174f5b69d2",

urlPath: "/",

urlQuery: undefined,

referrerPath: undefined,

referrerQuery: undefined,

referrerDomain: "",

pageTitle: "Discord Place",

eventType: 1,

eventName: null,

+   websiteId: String

}

}

Argument `websiteId` is missing.

at An (/app/node_modules/@prisma/client/runtime/library.js:114:7526)

at _n.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:121:7392)

at _n.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:121:7057)

at _n.request (/app/node_modules/@prisma/client/runtime/library.js:121:6741)

at async l (/app/node_modules/@prisma/client/runtime/library.js:130:9355)

at async x (/app/.next/server/pages/api/send.js:1:2791)

at async K (/app/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16853)

at async U.render (/app/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:17492)

at async NextNodeServer.runApi (/app/node_modules/next/dist/server/next-server.js:600:9)

at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/next/dist/server/next-server.js:269:37) {

clientVersion: '5.17.0'

}
```

### Which Umami version are you using? (if relevant)

v2.13.2

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Railway, Docker

**Comment by mthmcalixto** [comment]
try `https://api.umami.is/v1/`

**Comment by lightningspirit** [comment]
We are also experiencing the same issue:
```
PrismaClientValidationError: 
Invalid `prisma.eventData.createMany()` invocation:

{
  data: [
    {
      id: "904aff8c-223c-4a66-a316-019c2659d2d1",
      websiteEventId: "91817972-542a-418f-a0f0-4a49148accb2",
      websiteId: undefined,
      dataKey: "term",
      stringValue: "mtic",
      numberValue: null,
      dateValue: null,
      dataType: 1
    }
  ]
}

Argument `websiteId` is missing.
```

**Comment by mikecao** [comment]
It this only happening if you send event data or with normal requests too?

**Comment by chimpdev** [comment]
> It this only happening if you send event data or with normal requests too?

happens in all requests as far as I can see

**Comment by chimpdev** [comment]
I deleted the project from Railway and created & linked it again, no error now.

**Comment by lightningspirit** [comment]
Actually after some digging in the codebase, I've found that activating `REDIS_URL` improved Umami's performance a lot and that change removed the issue, since those  _immutable_ `SELECT`s are now cached.

**Comment by chimpdev** [comment]
> I deleted the project from Railway and created & linked it again, no error now.

The same problem reappeared today. @mikecao 
```
PrismaClientValidationError: 

Invalid `prisma.websiteEvent.create()` invocation:

 

{

  data: {

    id: "6078bfb8-4216-48b7-9473-104b5f064991",

    sessionId: undefined,

    visitId: "c6629b66-8b44-5115-af92-6c7000f8f41d",

    urlPath: "/servers/1200254872059121764",

    urlQuery: undefined,

    referrerPath: undefined,

    referrerQuery: undefined,

    referrerDomain: "",

    pageTitle: "Discord Place - Server discord.place — greatest of all time",

    eventType: 1,

    eventName: null,

    tag: undefined,

+   websiteId: String

  }

}

 

Argument `websiteId` is missing.

    at An (/app/node_modules/@prisma/client/runtime/library.js:114:7526)

    at _n.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:121:7392)

    at _n.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:121:7057)

    at _n.request (/app/node_modules/@prisma/client/runtime/library.js:121:6741)

    at async l (/app/node_modules/@prisma/client/runtime/library.js:130:9355)

    at async x (/app/.next/server/pages/api/send.js:1:2797)

    at async K (/app/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16881)

    at async U.render (/app/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:17520)

    at async NextNodeServer.runApi (/app/node_modules/next/dist/server/next-server.js:598:9)

    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/next/dist/server/next-server.js:269:37) {

  clientVersion: '5.17.0'

}

```
