### ISSUE TITLE
PrismaClientValidationError

### ISSUE THREAD

**Issue by mulder999** [umami-software/umami#3073]
### Describe the Bug

Latest version of application might crash with PrismaClientValidationError.

### Database

PostgreSQL

### Relevant log output

```shell
PrismaClientValidationError: 

Invalid `prisma.websiteEvent.create()` invocation:
... (redacted) ...
Argument `websiteId` is missing.
    at An (/app/node_modules/@prisma/client/runtime/library.js:114:7526)
    at _n.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:121:7392)
    at _n.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:121:7057)
    at _n.request (/app/node_modules/@prisma/client/runtime/library.js:121:6741)
    at async l (/app/node_modules/@prisma/client/runtime/library.js:130:9355)
    at async x (/app/.next/server/pages/api/send.js:1:2797)
    at async K (/app/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16881)
    at async U.render (/app/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:17520)
    at async NextNodeServer.runApi (/app/node_modules/next/dist/server/next-server.js:598:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/next/dist/server/next-server.js:269:37) {
  clientVersion: '5.17.0'
}
```

### Which Umami version are you using? (if relevant)

2.14

**Comment by franciscao633** [comment]
should be fixed in [this ](https://github.com/umami-software/umami/commit/4af275a7ab62afb74d8a034c5d0b440b3c1b5a36) commit
