### ISSUE TITLE
Raw query failed. Code: `42601` when loading page journey

### ISSUE THREAD

**Issue by manuel-rw** [umami-software/umami#3102]
### Describe the Bug

We recently upgraded our instance to  v2.11.3 to v2.14.0 and set up the new page journey report.
When loading the journes for the last 24 hours, the page is loading indefinetly and an error is logged.
![image](https://github.com/user-attachments/assets/31437967-b9b8-472b-8b9e-f2d5617fc0bc)

We upgraded in small steps (eg. v2.11.3 > v2.12.0 > v2.13.0 > v2.14.0) to avoid issues during database migration.

### Database

PostgreSQL

### Relevant log output

```shell
PrismaClientKnownRequestError: 
Invalid `prisma.$queryRawUnsafe()` invocation:
Raw query failed. Code: `42601`. Message: `ERROR: syntax error at or near "event"`
    at _n.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:121:7749)
    at _n.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:121:7057)
    at _n.request (/app/node_modules/@prisma/client/runtime/library.js:121:6741)
    at async l (/app/node_modules/@prisma/client/runtime/library.js:130:9355)
    at async l (/app/.next/server/pages/api/reports/journey.js:1:2069)
    at async K (/app/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16881)
    at async U.render (/app/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:17520)
    at async NextNodeServer.runApi (/app/node_modules/next/dist/server/next-server.js:598:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/next/dist/server/next-server.js:269:37)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/next/dist/server/base-server.js:813:17) {
  code: 'P2010',
  clientVersion: '5.17.0',
  meta: { code: '42601', message: 'ERROR: syntax error at or near "event"' }
}
```

### Which Umami version are you using? (if relevant)

v2.14.0

### How are you deploying your application? (if relevant)

Docker

**Comment by manuel-rw** [comment]
Sorry, didn't see #2800. Will close.
